### PR TITLE
Document how to install on MinGW when setuptools >= 60

### LINKED ISSUE #7222: Cannot install from pip on Msys2 mingw64
### What did you do?

I followed the steps in https://pillow.readthedocs.io/en/latest/installation.html
The zlib package (`mingw-w64-x86_64-zlib `) is installed correctly:
```console
$ file /mingw64/include/zlib.h
/mingw64/include/zlib.h: C source, ASCII text
```

I ran this command as per the documentation:

```console
$ CFLAGS="-I/mingw64/include" python3 -m pip install --upgrade Pillow --no-binary :all:
```

### What did you expect to happen?

To install correctly

### What actually happened?

It failed:
```pytb
Collecting Pillow
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [198 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.mingw_x86_64-cpython-310
      creating build/lib.mingw_x86_64-cpython-310/PIL
[skipping a bunch of useless stuff]
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 993, in <module>
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 809, in build_extensions
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:/msys64/tmp/pip-build-env-ol6lvvu4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1010, in <module>
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
```

The result is the same with`--no-cache-dir`

### What are your OS, Python and Pillow versions?

* OS: MSYS2 MINGW64
* Python: Python 3.10.12 (`/mingw64/bin/python`)

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #7222

Screenshot 2023-06-22 at 6 32 33 pm

### CODE REVIEW

**Comment by hugovk** [comment]
Shall we add this as a `.. Note::`?

**Comment by radarhere** [comment]
I've updated the initial post to include a screenshot of the current version.

Here's how it looks as a note - it's minor, so we can go with it if you want, but I think the smaller code within the note compared to the surrounding code highlights looks odd?

Screenshot 2023-06-22 at 6 32 40 pm

**Comment by hugovk** [comment]
Okay, let's keep it like this. Thank you!

**Comment by MAjeRoK** [comment]
I want to add the information how to set up the variable SETUPTOOLS_USE_DISTUTILS in PowerShell Windows:
`$env:SETUPTOOLS_USE_DISTUTILS="stdlib"`
It helped me with this MSYS2 issue

**Comment by radarhere** [comment]
It seems very similar to what we have documented here? I would have thought it was a relatively simple matter for users to translate `export SETUPTOOLS_USE_DISTUTILS=stdlib` to `$env:SETUPTOOLS_USE_DISTUTILS="stdlib"`?

**Comment by MAjeRoK** [comment]
Yes. It is true. I just want to prevent the mistake I did.

Firstly I used command `SET` for PowerShell and the terminal didn't say anything wrong. So I tried pip and the package wasn't installed. And I thought that this solution isn't for me and spent another one hour trying to find the right solution.

Only by a coincidence I figured out that `SET` works in cmd and not in PowerShell. That is why I left a comment with the right command for PowerShell

**Comment by radarhere** [comment]
Oh, I thought you were suggesting that we update the documentation at https://pillow.readthedocs.io/en/stable/installation.html.

If you just wanted to leave that comment here, sure, no problem.

**Pull request merged**
