### PR TITLE
Do not access uninitialized memory in getink.

### PR DESCRIPTION
**Pull request by lambdafu**
The getink code is a bloodbath, but more importantly, it accesses invalid memory in certain code paths:

```
File Edit Options Buffers Tools Help                                                                                                                                           
_imaging.c: In function ‘getink’:
_imaging.c:474:9: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     int r, g, b, a;
              ^
```

Valgrind complains:
```
[Pillow]$ PYTHONPATH=. valgrind python Tests/test_image.py
==23998== Conditional jump or move depends on uninitialised value(s)
==23998==    at 0x11C0FB0D: getink (_imaging.c:495)
==23998==    by 0x11C1054C: _draw_ink (_imaging.c:2375)
==23998==    by 0x4F178BD: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F186B3: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F175C5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F186B3: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F175C5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F17665: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4F186B3: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4EA45AB: ??? (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4E7FB02: PyObject_Call (in /usr/lib64/libpython2.7.so.1.0)
==23998==    by 0x4E8E95B: ??? (in /usr/lib64/libpython2.7.so.1.0)
```

The patch fixes it and removes some redundancies.  I stopped short of rewriting the whole function (but I am not saying it would be a bad idea :).

### CODE REVIEW

**Comment by wiredfool** [comment]
See also #1663, which is also stuck on failing in appveyor.

**Comment by lambdafu** [comment]
I'm fine with closing this, #1663 covers it well.  Sorry, I didn't check too closely the existing reports.

**Comment by wiredfool** [comment]
No worries. I'll take a look and see how our patches compare. Unfortunately, they appear to be both failing on windows, which is why the other one is stalled.

**Comment by wiredfool** [comment]
I've found the bug on windows in the other PR, and it looks to be more complete, so closing this one in favor of #1663.

**Pull request closed without merging**
