### PR TITLE
Added support for ImageGrab.grab to OS X

### PR DESCRIPTION
**Pull request by radarhere**
As requested in #901

### CODE REVIEW

**Comment by hugovk** [comment]
Might PNG be a better intermediate format then JPEG?

**Comment by hugovk** [comment]
Or some other, lossless format?

**Comment by radarhere** [comment]
Yes, good point. Although png is the format that OS X's keyboard shortcut screenshot uses. I've changed the commit accordingly.

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
