### PR TITLE
GitHub Action to add issue or PR to project

### PR DESCRIPTION
**Pull request by hugovk**
Continuation of https://github.com/python-pillow/Pillow/pull/4071

### CODE REVIEW

**Comment by hugovk** [comment]
Now gives "bad credentials", so at least it's running. 

https://github.com/python-pillow/Pillow/pull/4078/checks?check_run_id=231177672

@aclark4life Perhaps it also needs the repo permission, or some of its sub-permissions: maybe repo:status, repo_deployment, public_repo?

**Comment by aclark4life** [comment]
@hugovk OK new ``GH_PAT`` in effect with ``[*] repo``

**Comment by radarhere** [comment]
Attempted to help by opening #4079 to trigger it again, but did not have success.

image

image

**Comment by hugovk** [comment]
The Action has been updated and v0.1.0 released:

* https://github.com/alex-page/github-project-automation-plus/issues/10#issuecomment-534347768

Will re-open as a new PR to test.

**Pull request closed without merging**
