### PR TITLE
Include tests in coverage reports

### PR DESCRIPTION
**Pull request by hugovk**
As recommended by the author of Coverage.py:

* https://nedbatchelder.com/blog/201908/dont_omit_tests_from_coverage.html

### CODE REVIEW

**Comment by radarhere** [comment]
Why omit check_\*, but not 32bit_segfault_check, bench_\*, import_all, make_hash, threaded_save or versions?

**Comment by hugovk** [comment]
Good question. Let's review whether we still need them at all, can they be deleted? (I'm away from a computer for a few days, so can't check the git logs right now.)

**Comment by radarhere** [comment]
Here is the history
- 32bit_segfault_check.py - Added in #782. PR states 'Test is not run by default. Hangs when run through a testfixture.'
- bench_cffi_access.py - Added in #476. Comment states 'Not running this test by default. No DOS against Travis CI.'
- createfontdatachunk.py - See #789, moving it from a PIL `__main__` to Scripts, and #2645, moving it from Scripts into Tests.
- bench_get.py, import_all.py, make_hash.py, threaded_save.py, versions.py - Added in #35. Commit says 'This is Christoph Gohlke's test suite from his personal PIL package'

**Comment by hugovk** [comment]
> Here is the history
> 
> * 32bit_segfault_check.py - Added in #782. PR states 'Test is not run by default. Hangs when run through a testfixture.'
> * bench_cffi_access.py - Added in #476. Comment states 'Not running this test by default. No DOS against Travis CI.'
> * createfontdatachunk.py - See #789, moving it from a PIL `__main__` to Scripts, and #2645, moving it from Scripts into Tests.
> * bench_get.py, import_all.py, make_hash.py, threaded_save.py, versions.py - Added in #35. Commit says 'This is Christoph Gohlke's test suite from his personal PIL package'

@wiredfool @cgohlke Would you like to keep any of these files in repo?

**Comment by cgohlke** [comment]
>> bench_get.py, import_all.py, make_hash.py, threaded_save.py, versions.py - Added in #35. Commit says 'This is Christoph Gohlke's test suite from his personal PIL package'

> Would you like to keep any of these files in repo?

No

**Comment by hugovk** [comment]
> * 32bit_segfault_check.py - Added in #782. PR states 'Test is not run by default. Hangs when run through a testfixture.'
> * bench_cffi_access.py - Added in #476. Comment states 'Not running this test by default. No DOS against Travis CI.'
> * createfontdatachunk.py - See #789, moving it from a PIL `__main__` to Scripts, and #2645, moving it from Scripts into Tests.

Let's keep them for noq. Added to the ignore list.

> * bench_get.py, import_all.py, make_hash.py, threaded_save.py, versions.py - Added in #35. Commit says 'This is Christoph Gohlke's test suite from his personal PIL package'

Removed.

**Pull request merged**
