### PR TITLE
Add CIFuzz Github Action

### PR DESCRIPTION
**Pull request by wiredfool**
Draft, to trigger the CI.

This PR adds CI support to run the OSS-Fuzz routines on fresh changes.

### CODE REVIEW

**Comment by wiredfool** [comment]
This is failing on a missing item in apt-get, base images need updated.

**Comment by radarhere** [comment]
What's the missing apt-get item?

**Comment by wiredfool** [comment]
I've fixed it upstream, but there are other errors, I need to track down why it's not finding the fuzzers.

**Comment by wiredfool** [comment]
Ok, this is blocked upstream because there isn't actually python support for cifuzz, and it's unclear if it's a small or large problem. https://github.com/google/oss-fuzz/issues/5195

**Comment by radarhere** [comment]
For the record, https://github.com/google/oss-fuzz/issues/5195 has been theoretically resolved.

**Comment by wiredfool** [comment]
Ok, current status here is that 
* the fuzzer is working now
* [ ] Need to get creds to upload the repro cases
* [ ] Fail on a crash to prevent PRs from progressing
* [ ] Remove .yml change so that we're just running on .c/h changes.   (Tho, I will say that ~20% of the security bugs wind up getting fixed with a python change, but I'm not really into adding a 20 minute runtime check to all of our test runs)

**Comment by hugovk** [comment]
> * [ ]  Remove .yml change so that we're just running on .c/h changes.   (Tho, I will say that ~20% of the security bugs wind up getting fixed with a python change, but I'm not really into adding a 20 minute runtime check to all of our test runs)

Add something like this?

```yml
on:
  push:
    paths:
    - '**.c'
    - '**.h'
```

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by wiredfool** [comment]
Yah, that's not the hard part, just a checkbox as the last thing before the merge.

(and the yml change is actually something I added in the valgrind test, not here. memory is going. )

**Comment by wiredfool** [comment]
Ok, I think I understand what's going on here -- it's only a failure if it fails on the branch but not the original.

**Pull request merged**
