### PR TITLE
Added S to list of I;16 formats

### LINKED ISSUE #1244: Trying to seek in multipage TIFF
For simplicity, we try seeking to the beginning (where we already are). However, this error can be found for other locations, as well. Whether or not the mode is specified, this still fails.

```
>>> from PIL import Image
>>> im = Image.open("./ITPT044_S001_F01_002.tif", mode='r')
>>> im.seek(0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-864e01ab7a06> in <module>()
----> 1 im.seek(0)

/home/kirkhamj/miniconda/envs/nanshenv/lib/python2.7/site-packages/PIL/TiffImagePlugin.pyc in seek(self, frame)
    646         # different size/mode.
    647         Image._decompression_bomb_check(self.size)
--> 648         self.im = Image.core.new(self.mode, self.size)
    649 
    650     def tell(self):

ValueError: unrecognized mode
>>> im.mode
'I;16S'
```

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #1244 - loading of I;16S images

There is a list of I;16 modes - I;16, I;16L, I;16B and I;16N. I presume that I;16S was simply forgotten in that list, rather than being excluded for any particular reason.

### CODE REVIEW

**Comment by wiredfool** [comment]
I wouldn't be surprised if I;16S isn't fully baked. I know that there are no conversions from I;16S to anything else, and I don't think that there are actually any pixel access methods for it. I think basically the only thing that can be done with it is to offload to numpy/scipy.

**Comment by wiredfool** [comment]
We need to find a distributable I;16S image to test with, I think this might be a GIS image format.

**Comment by wiredfool** [comment]
I'll look.

Fwiw, the signed modes are a pain because they are not really supported in the backend. Some operations may work, but anything dealing with pixel values is going to be broken. (And broken meaning that the results will be wrong, not that it will crash) There are really three options:

* convert to unsigned for storage, use the signed formats only for reading and writing
* write converters to and from signed so that we can store in signed, but can losslessly convert to do operations on the data. 
* push full signed access through.

**Comment by wiredfool** [comment]
The access part is wrong, as it's returning a uint16, not an int16. Unpack is probably ok, but there's probably some issues related to endianness, either big, little or native. I think that in this case, it's probably going to wind up being native.   There are existing unpack methods for all of the I;16*S methods -> I. There are some existing pack methods, but they don't cover all of the permutations. 

I'm kind of thinking that the best move might be to make the I;16S modes store as I (aka, I32 or I32S), and leave out the I;16 storage for now.

**Comment by homm** [comment]
successor: https://github.com/python-pillow/Pillow/pull/2577

**Pull request closed without merging**
