### PR TITLE
Fix Exception when installing jpeg

### PR DESCRIPTION
**Pull request by hansmosh**
`python3.4 setup.py install` is not working on my computer. While I didn't fix the issue, I did come across another one here.

### CODE REVIEW

**Comment by radarhere** [comment]
+1. Nice work.

**Comment by wiredfool** [comment]
Damn. What idiot wrote that code originally.

**Comment by hansmosh** [comment]
@wiredfool Not "idiot". "Fool".

I also considered changing `in ('jpeg', 'libz')` to `in feature.required` but wanted to keep my first PR to the repo real simple.

**Comment by wiredfool** [comment]
`in feature.required` isn't going to be correct because it's mutable by adding an `--enable-foo` flag.

**Comment by wiredfool** [comment]
Thanks for finding and fixing that.

**Pull request merged**
