### PR TITLE
Give correct extrema for I;16 format images

### PR DESCRIPTION
**Pull request by bz2**
Currently gives None for a 16 bit greyscale image rather than the true min and max values in the 0-65536 range. The internal `ImagingGetProjection` function already supports `I;16` but the `_getextrema` needs to know to unpack the result.

### CODE REVIEW

**Comment by bz2** [comment]
The appveyor failure looks spurious to me?

**Comment by hugovk** [comment]
Yes, it's unrelated, see https://github.com/python-pillow/Pillow/issues/3363.

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/issues/3363 has been fixed, you can rebase/merge master if you'd like to include it.

**Comment by bz2** [comment]
@hugovk @radarhere Thanks! Rebase done, gating rerunning now.

**Pull request merged**
