### PR TITLE
Enabled page heap verification

### PR DESCRIPTION
**Pull request by radarhere**
Suggested in https://github.com/python-pillow/Pillow/issues/3618#issuecomment-478872426

Helps prevent https://github.com/python-pillow/Pillow/issues/4152#issuecomment-544619189

Used https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/example-12---using-page-heap-verification-to-find-a-bug

As a demonstration, this will fail until #4160 is merged.

### CODE REVIEW

**Comment by hugovk** [comment]
Very good! 

Do you know if this is possible with GitHub Actions?

**Comment by radarhere** [comment]
Okay, added it to GHA as well.

**Comment by nulano** [comment]
I was just working on this a week ago, but I wanted to add crash dumps, and got sidetracked with a ton of other work.

My WIP branch is here, if you would like to finish the dump part (it was exiting with the wrong exit code): https://github.com/nulano/Pillow/commits/heap

**Comment by hugovk** [comment]
Thanks both, let's merge this now and further improvements always welcome in the future!

**Pull request merged**
