### PR TITLE
FIX: fix C90 compilation error for Tcl / Tk stuff

### PR DESCRIPTION
**Pull request by matthew-brett**
Tk stuff introduced a warning about compilation of new Tk code, and thence an error.   Slight rephrase of C code to fix.

Should fix
https://github.com/python-pillow/Pillow/issues/2017

### CODE REVIEW

**Comment by wiredfool** [comment]
Thanks @matthew-brett. @mzbqhbc, @Fak3  Does this fix your issue?

**Comment by wiredfool** [comment]
Ping:  @mzbqhbc, @Fak3 Does this fix your issue?

**Comment by Fak3** [comment]
@wiredfool yes, i just installed that branch successfully

**Comment by wiredfool** [comment]
Great, Thanks.

**Pull request merged**
