### PR TITLE
Make OleFileIO VT dict building more comprehensive

### PR DESCRIPTION
**Pull request by vperron**
Mainly a style fix.

### CODE REVIEW

**Comment by decalage2** [comment]
Looks good, I will test it and merge it upstream into olefile (http://www.decalage.info/olefile)

**Comment by decalage2** [comment]
I would be interested in details about the RuntimeError you mentioned, if there is any issue I need to fix in olefile.

**Comment by vperron** [comment]
Well the runtime error did happen in a non-easily reproducible way and was about the vars() dictionary being modified upon iteration.

That's why I refer to it as a style fix.

**Comment by hugovk** [comment]
@decalage2 Let us know if you merge it upstream as is, and we can just hit the merge button here.

**Comment by aclark4life** [comment]
@decalage2 Any progress on this?

**Comment by radarhere** [comment]
Given that it's been a while, and that substantial changes to OleFileIO have already been merged with #1226, is it time to merge this?

**Comment by aclark4life** [comment]
I think we need to hear from @decalage2 and if we don't, decide if we want to merge anyway… or not. I'm not *exactly* sure what's appropriate or needed.

**Comment by radarhere** [comment]
With the merging of #2199, this is no longer applicable.

**Pull request closed without merging**
