### PR TITLE
Imaging.h: confusion with system

### PR DESCRIPTION
**Pull request by ax3l**
The file `libImaging/Imaging.h` gets installed [on Ubuntu flat into the public Python includes](https://packages.ubuntu.com/search?searchon=contents&keywords=Imaging.h&mode=exactfilename&suite=focal&arch=any).

When building a newer version of Pillow from source and hinting the Python includes "too early" in includes, e.g. in [package managers](https://github.com/spack/spack/issues/18589#issuecomment-693165252), this can confuse the two files and pick up the external file over the internal one. With different versions, this mismatch can lead to build errors, e.g. undefined macros.

The most robust way to avoid this is to prefix the internal include accordingly, so that the relative path to the including file has to match as well.

### CODE REVIEW

**Comment by radarhere** [comment]
I've created https://github.com/ax3l/Pillow/pull/1 as a suggestion to expand on this - prefixing more header includes.

**Comment by wiredfool** [comment]
I think this is a bug in the debian packaging. `Imaging.h` is an internal file, not a supported set of external interfaces. 

Following the debian rules for splitting and naming packages, if the header is actually required (e.g, for other debian packages), it should be in a package named python-pillow-dev, not in the primary python-pillow package. (e.g, libfoo and libfoo-dev for compilation).

**Comment by radarhere** [comment]
If it's not a problem though, is it worth doing just because it makes it clearer to the reader where the header file is located?

**Comment by ax3l** [comment]
I think even if it were in a `-dev` package, we would have the same problem.

**Review by radarhere — APPROVED** [review]

**Review by hugovk — APPROVED** [review]

**Comment by ax3l** [comment]
Thank you for the update, LGTM.

**Comment by nulano** [comment]
I tried to remove the `libImaging` directory from the includes added in `setup.py` so future includes can't omit the prefix by accident, but this causes a failure building `_imagingft.c` on systems without libraqm. Fixing this requires changing
```c
#include <raqm.h>
```
to
```c
#include "libImaging/raqm.h"
```
so I'm not sure it is worth it. Thoughts?

https://github.com/ax3l/Pillow/compare/fix-imagingHinclude...nulano:fix-imagingHinclude

**Comment by ax3l** [comment]
Oh, but that means instead of the internally shipped `raqm.h` it was picking up a system one already. Yes, would add this.

**Comment by hugovk** [comment]
Merged in `master` to include https://github.com/python-pillow/Pillow/pull/4978 to fix the unrelated CI failure.

**Pull request merged**
