### PR TITLE
Added writing of subIFDs

### LINKED ISSUE #4215: "tuple index out of range" when using exif_transpose
I took a picture with my phone and am trying to call `exif_transpose()` on it, but I'm getting a "tuple index out of range" error.

Here's the traceback:

```python
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 108, in sentry_patched_wsgi_handler
    return SentryWsgiMiddleware(bound_old_app)(environ, start_response)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 120, in __call__
    reraise(*_capture_exception(hub))
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 116, in __call__
    _sentry_start_response, start_response, span
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 140, in sentry_patched_get_response
    return old_get_response(self, request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stavros/Code/Django/imgz/main/views.py", line 102, in image_upload
    image = Image.objects.create(data=data, user=user, name=name)
  File "/home/stavros/Code/Django/imgz/main/models.py", line 82, in create
    return super().create(*args, **kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/stavros/Code/Django/imgz/main/models.py", line 168, in save
    self.transpose_image()
  File "/home/stavros/Code/Django/imgz/main/models.py", line 160, in transpose_image
    transposed = ImageOps.exif_transpose(img)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/ImageOps.py", line 549, in exif_transpose
    transposed_image.info["exif"] = exif.tobytes()
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/Image.py", line 3212, in tobytes
    ifd[tag] = value
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 540, in __setitem__
    self._setitem(tag, value, self.legacy_api)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 605, in _setitem
    dest[tag] = values[0]
IndexError: tuple index out of range
```

Here is the EXIF data. You can see that the cause is `(34853, {})`:

```
[(36864, b'0220'), (37121, b'\x01\x02\x03\x00'), (37377, (4321, 1000)), (36867, '2019:11:19 03:47:56'), (36868, '2019:11:19 03:47:56'), (37378, (161, 100)), (37379, (-383, 100)), (37380, (0, 6)), (37381, (161, 100)), (37383, 2), (37384, 21), (37385, 16), (37386, (4770, 1000)), (40961, 1), (40962, 4000), (41990, 0), (37520, '679949'), (37521, '679949'), (37522, '679949'), (40963, 3000), (257, 3000), (271, 'Xiaomi'), (272, 'Redmi K20'), (41495, 1), (531, 1), (33434, (1, 20)), (40965, 717), (282, (72, 1)), (33437, (175, 100)), (41729, b'\x01'), (283, (72, 1)), (34850, 2), (34853, {}), (34855, 983), (296, 2), (41986, 0), (40960, b'0100'), (256, 4000), (41987, 0), (306, '2019:11:19 03:47:56'), (41989, 26), (34665, 212)]
```

Is there any way I can work around this?

### LINKED ISSUE #4896: Metadata Warning, tag 34853 had too many entries
### What did you do?
Open an image and then use ImageOps.exif_transpose operation.

### What did you expect to happen?
No warning.

### What actually happened?
```
/home/zeyang/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:594: UserWarning: Metadata Warning, tag 34853 had too many entries: 10, expected 1
  % (tag, len(values))
```
### What are your OS, Python and Pillow versions?

* OS: ubuntu 16.04
* Python: 3.7.1
* Pillow: 7.2.0

```python
# codes to reproduce the warning
from PIL import Image, ImageOps
img = Image.open('d9af31bc74d18334.jpg')
img = ImageOps.exif_transpose(img)
```

[Image](https://user-images.githubusercontent.com/42920710/91961072-471b9780-ed3d-11ea-969b-cffc4af119b4.jpg) used for reproducing this error.

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #4215
Resolves #4896

When writing EXIF data, the format it is saved in is called Image File Directory, made up of various entries. However, an IFD entry can also link to a subIFD. One example is the [GPS IFD](https://www.awaresystems.be/imaging/tiff/tifftags/gpsifd.html) tag. It does so by writing a LONG of the offset to the new IFD.

At present, Pillow does not do anything to handle subIFDs. The dictionary of data, such as https://github.com/python-pillow/Pillow/blob/398a591e7e738e7907c18b11b281a68b31b62ae3/Tests/test_file_jpeg.py#L231-L237

comes in, and then Pillow converts it to a tuple of its keys.
https://github.com/python-pillow/Pillow/blob/398a591e7e738e7907c18b11b281a68b31b62ae3/src/PIL/TiffImagePlugin.py#L570

The unusual part of #4215 is that it has no values in its GPS IFD. So when Pillow sees that the GPS LONG doesn't have one value like it is supposed to, it tries to get the first value,

https://github.com/python-pillow/Pillow/blob/398a591e7e738e7907c18b11b281a68b31b62ae3/src/PIL/TiffImagePlugin.py#L598

and throws an error.

This PR fixes it so that the actual subIFD is written. First, it ensures that we don't convert the dictionary into a tuple, and then it sets up the data when writing.

### CODE REVIEW

**Comment by radarhere** [comment]
Ok, I've add a test with the [smaller image](https://github.com/python-pillow/Pillow/pull/4851#issuecomment-673164846)

**Comment by hugovk** [comment]
Thanks! Do we need release notes?

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by radarhere** [comment]
I've added #4972 as release notes.

**Comment by kunalbathija** [comment]
Hi, I am still facing same issue, I am on latest version 8.4.0

**Comment by radarhere** [comment]
@kunalbathija could you create a new issue with more detail? Self-contained example code?

**Comment by kunalbathija** [comment]
@radarhere I had used 163kb tif file and was getting this error then I used 71kb file and didn't get this error.

**Comment by radarhere** [comment]
This problem has moved to #5852

**Pull request merged**
