### PR TITLE
Added PDF multipage saving

### PR DESCRIPTION
**Pull request by radarhere**
Contribution to #733

### CODE REVIEW

**Comment by aclark4life** [comment]
@radarhere You are welcome to create branches in the Pillow repo (vs forking to your personal repo) FWIW

**Comment by hugovk** [comment]
There's an advantage to branching in one's own repo: the (pre-PR) build will be done with your own Travis CI account and so with another build queue and so things get built quicker.

**Comment by aclark4life** [comment]
@hugovk Ah, nice

**Comment by radarhere** [comment]
For various reasons, I think I will just keep branching from my own repo, but thanks for letting me know that I have the freedom @aclark4life

**Comment by aclark4life** [comment]
I'd probably go so far to say I'd prefer folks use branches in the Pillow repo, but @hugovk makes a good point :-)

**Comment by wiredfool** [comment]
I like having branches in my repo, just to keep the state of the main repo clean. Also, my checkouts of the main repo tend to use the https url, so that I'm not actually logged in to it so that I can't accidentally push and delete history. 

The one thing I'd really like to figure out is how to do collaborative pull requests, so that more than one person can easily contribute to a PR as they get worked on.

**Comment by aclark4life** [comment]
@wiredfool You can do that in the Pillow repo:

```
git branch aclark-and-wiredfool
git checkout aclark-and-wiredfool
git push --set-upstream origin aclark-and-wiredfool
```

Now create a PR from **aclark-and-wiredfool** to **master**; anything anyone commits and pushes to the aclark-and-wiredfool branch will be automatically added to it.

**Comment by wiredfool** [comment]
Usually it's more the case that I want to add something to a pr that someone else has created, like in #1393 or #1246. I can get the code from upstream/pr/#### in my git directory  (which I think I needed to setup), but then if I push back somewhere, it's disconnected from the PR thread for review.

**Comment by aclark4life** [comment]
You don't want the code from the PR you want the branch, which you can't easily commit to because it exists in the personal repository of the contributor (at least in the case of #1393); hence my preference for all-Pillow-repo-development-all-the-time.

**Comment by wiredfool** [comment]
So the maintainers can easily push on any branch in the main repo, but often the branches that really need the work aren't from the maintainers. So, it really doesn't matter. 

Then again, if you saw the state of branches in my repo, it's probably better that they're there and not on the main repo.

**Comment by radarhere** [comment]
I've added a note to docs/handbook/image-file-formats.rst to let people know about save_all for the PDF format. If you have ideas for further documentation, let me know.

**Pull request merged**
