### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by homm**

### CODE REVIEW

**Comment by homm** [comment]
@wiredfool Tests fails with segmentation fault on `TestJ2kEncodeOverflow.test_j2k_overflow`. Do we need to replace `SIZE_MAX` with `INT_MAX` there?

**Comment by homm** [comment]
By the way:

```c
size_t size1 = SIZE_MAX;
unsigned size2 = SIZE_MAX;

printf("%p\n", size1);
printf("%p\n", size2);
```

```
0xffffffff
0xffffffffffffffff
```

**Comment by wiredfool** [comment]
The SIZE_MAX is fixed in the malloc check branch, so I'd leave it to that.

**Comment by homm** [comment]
removed Jpeg2KEncode fix from this pr

**Comment by wiredfool** [comment]
cherry-picked b4e0ba1

**Comment by homm** [comment]
> The SIZE_MAX is fixed in the malloc check branch, so I'd leave it to that.

I'm still seeing warnings.

```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
ccache gcc -mavx2 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_LIBJPEG -DHAVE_OPENJPEG -DHAVE_LIBZ -DHAVE_LIBIMAGEQUANT -DHAVE_LIBTIFF -I/usr/include/freetype2 -I/usr/include/openjpeg-2.1 -I/home/homm/Code/Pillow/libImaging -I/home/homm/env/env_ucare/include -I/usr/local/include -I/usr/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -c libImaging/Jpeg2KEncode.c -o build/temp.linux-x86_64-2.7/libImaging/Jpeg2KEncode.o
libImaging/Jpeg2KEncode.c: In function ‘j2k_encode_entry’:
libImaging/Jpeg2KEncode.c:271:5: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     unsigned _SIZE__MAX = SIZE_MAX;
     ^
```

**Comment by wiredfool** [comment]
SIZE_MAX isn't in Jpeg2kEncode.c in master at all.

**Comment by homm** [comment]
Woops. Looks like some problem with `ccache` or I just was not careful enough.

**Pull request closed without merging**
