### PR TITLE
Update of Pr #2284, Complex Text Support

### PR DESCRIPTION
**Pull request by wiredfool**
Includes #2284.

So far, fixes:
* rebased
* feature detection
* Testing both branches when raqm is installed

Todo/test/check
- [x] install docs/alternate platforms
   - 5 of the dockers now have raqm available. 
- [x] install detection/enable/disable
- [x] font license
- [x] review docs
- [x] ppa check

Additional note, we should add the Deja license to the font licence directory as well: https://dejavu-fonts.github.io/License.html

### CODE REVIEW

**Comment by Fahad-Alsaidi** [comment]
to build libraqm natively on windows or OSX, you can [libraqm-cmake](https://github.com/HOST-Oman/libraqm-cmake) repo.

**Comment by wiredfool** [comment]
Raqm is not building on freebsd-11:
```
...
checking pkg-config is at least version 0.20... yes
checking for FREETYPE... yes
checking for HARFBUZZ... yes
checking for FRIBIDI... yes
checking for GLIB... yes
checking for hb_ft_font_create_referenced... yes
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.14 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating raqm.pc
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating docs/Makefile
config.status: creating docs/version.xml
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
--- all ---
make  all-recursive
--- all-recursive ---
Making all in src
--- libraqm_la-raqm.lo ---
  CC       libraqm_la-raqm.lo
--- libraqm.la ---
  CCLD     libraqm.la
Making all in docs
Making all in tests
make[2]: "/usr/home/erics/Pillow/depends/raqm-0.2.0/tests/Makefile" line 1077: Missing dependency operator
make[2]: "/usr/home/erics/Pillow/depends/raqm-0.2.0/tests/Makefile" line 1078: Missing dependency operator
make[2]: Fatal errors encountered -- cannot continue
make[2]: stopped in /usr/home/erics/Pillow/depends/raqm-0.2.0/tests
*** [all-recursive] Error code 1

make[1]: stopped in /usr/home/erics/Pillow/depends/raqm-0.2.0
1 error

make[1]: stopped in /usr/home/erics/Pillow/depends/raqm-0.2.0
*** [all] Error code 2

make: stopped in /usr/home/erics/Pillow/depends/raqm-0.2.0
1 error

make: stopped in /usr/home/erics/Pillow/depends/raqm-0.2.0
```

**Comment by wiredfool** [comment]
Fedora is good.

**Comment by khaledhosny** [comment]
Any idea what corresponds to these failing lines in Makefile.am?

**Comment by wiredfool** [comment]
No, I'm afraid I haven't dived into automake. 

But I _just_ tried it with the cmake version and it builds and passes tests with that version. So that part is good anyway.  I've noticed that the cmake and other repo are slightly out of sync -- would it be possible to sync them up and declare a 0.3.0 release, or add the cmake portions to the main repo?

**Comment by wiredfool** [comment]
With the cmake version of libraqm, I'm getting one test failure on osx:
```
(vpy27)Erics-MacBook-Air:Pillow erics$ ./test-installed.py Tests/test_imagefontctl.py
..F.......
======================================================================
FAIL: TestImagecomplextext.test_complex_unicode_text
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erics/Pillow/Tests/test_imagefontctl.py", line 55, in test_complex_unicode_text
    self.assert_image_similar(im, target_img, .5)
  File "/Users/erics/Pillow/Tests/helper.py", line 110, in assert_image_similar
    ave_diff, epsilon))
AssertionError:  average pixel value difference 12.5302 > epsilon 0.5000
```

With an image like this:
complex_unicode

Which is clearly completely failing. 

Install procedure here was roughly:
```
brew install fribidi harfbuzz cmake
```
* clone libraqm-cmake
* build with prefix /usr/local
* build pillow.

**Comment by Fahad-Alsaidi** [comment]
It is weird. I see this  `draw.text((0, 0), u'السلام عليكم', font=ttf, fill=500) `  but there is no `u` notation in the other tests. Is it OK? try to remove it to be synced with the other tests.

**Comment by wiredfool** [comment]
Ok. Current state is:
- Generally, all un*x platforms work that I've tried. linux, freebsd, mac/brew 
- Windows is going to be a treat due to getting harfbuzz and firbidi compiled with msvc. 
- Just added direction/features to getsize. Need to test that with some of the features, kerning, possibly ttb. 

Almost ready at this point.

**Comment by Fahad-Alsaidi** [comment]
For windows, you can benefit from [Raqm dependencies project ](https://github.com/HOST-Oman/raqm-dependencies).

**Comment by wiredfool** [comment]
The trouble with the dependencies on windows is that as far as I know, Python needs the compiler to be consistent between the Python version and its extensions. So mingw isn't going to work. 

I'm going to merge for now and we'll deal with windows later. The compilation issues are only going to get better over time.

**Pull request merged**
