### PR TITLE
Allow truetype() to search for extensions other than .ttf

### PR DESCRIPTION
**Pull request by radarhere**
After the discussion in #1115, this allows truetype() to search for extensions other than .ttf if no extension is provided.

### CODE REVIEW

**Comment by radarhere** [comment]
Hmm. I don't know why this isn't passing. At first, I thought that a non-ttf font with the name Arial might be taking precedence, but I guess not.

**Comment by aclark4life** [comment]
Can this go in before and/or without #1115 ?

**Comment by radarhere** [comment]
These commits are intended to be instead of #1115, so yes, it can go without that.

**Comment by aclark4life** [comment]
Got it, thanks. Any chance for a test to accompany this?

**Comment by radarhere** [comment]
So, in addition to the existing test for finding a TTF font with the extension specified, there are now tests for finding a TTF font without the extension specified, finding a non-TTF font without the extension specified and a test for preferring TTF over other extensions if there is no extension specified.

**Comment by aclark4life** [comment]
Thanks

**Pull request merged**
