### PR TITLE
Migrate to container-based infrastructure

### PR DESCRIPTION
**Pull request by homm**
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

### CODE REVIEW

**Comment by hugovk** [comment]
I'm all for container-based infra, and this is a good start, but there's still a bit of work to complete the migration. 

At least these still use sudo and won't build, so not everything will get tested:

```
 # webp
  - pushd depends && ./install_webp.sh && popd

  # openjpeg
  - pushd depends && ./install_openjpeg.sh && popd
```

See also #1371 where this has been discussed a bit.

PS I recommend enabling Travis CI and Coveralls for your own repo builds:
https://travis-ci.org/homm/Pillow/
https://coveralls.io/repos/new
It's useful for when the main Pillow build queue gets a bit long, and especially when the Travis legacy [capacity](https://www.traviscistatus.com/) is maxed out.

**Comment by homm** [comment]
I just noticed what other pull requests stuck for more than 4 hours and decided to try this hint from Travis. But this build also still in progress, so obvious it is something else.

**Comment by hugovk** [comment]
Yeah, it's going *much* slower than usual today...

**Comment by hugovk** [comment]
Coverage dropped from 75.97% to 75.09% as OpenJPEG and WebP are not built:

https://travis-ci.org/python-pillow/Pillow/jobs/79340536#L1566

**Comment by homm** [comment]
not an issue anymore

**Comment by radarhere** [comment]
Why is it not an issue anymore?

**Comment by homm** [comment]
There are were the troubles with Travis CI, it hasn't worked properly. I was trying to fix it with migration container-based infrastructure. But for now everything works perfect on the old infrastructure.

**Comment by radarhere** [comment]
Okay. Thanks for answering.

**Comment by homm** [comment]
Most likely we still can speed builds up by migration, but Travis builds run in parallel and they are ready 3-4 times faster than AppVeyor's one.

**Pull request closed without merging**
