### PR TITLE
Fix PyAccess module and tests

### PR DESCRIPTION
**Pull request by homm**
Fixes bug found in https://github.com/python-pillow/Pillow/pull/2008.

### Tests

Clean up global variable `Image.USE_CFFI_ACCESS` after tests to not use PyAccess on CPython or CPython interface on PyPy.

Do not run tests twice via `test_put` and `test_get`.

### PyAccess module

```python
from PIL import Image
Image.USE_CFFI_ACCESS = True
size = 10

print 'img is unreferenced (garbage)'
px = Image.new('L', (size, 1), 0).load()
print '>>>', [px[i, 0] for i in range(size)]

print 'img is referenced (zeroes)'
img = Image.new('L', (size, 1), 0)
px = img.load()
print '>>>', [px[i, 0] for i in range(size)]
```

Output:
```
img is unreferenced (garbage)
>>> [103, 46, 115, 111, 46, 56, 0, 0, 33, 0]
img is referenced (zeroes)
>>> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

After the fix:
```
img is unreferenced (garbage)
>>> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
img is referenced (zeroes)
>>> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

### CODE REVIEW

**Comment by homm** [comment]
The error doesn't happen in PyPy due to lack of reference counting. The `im` object was alive some time until next garbage collection.

**Comment by homm** [comment]
Test added.

**Comment by CTPaHHuK-HEbA** [comment]
+        self._im = img.im

**Comment by CTPaHHuK-HEbA** [comment]
+        # Keep pointer to im object to prevent dereferencing.
+        self._im = img.im

Thx. This fix prevents the fall pypy:
https://bitbucket.org/pypy/pypy/issues/2338/windows-pillow-appcrash

**Comment by homm** [comment]
@CTPaHHuK-HEbA You can close pypy issue because this is exclusively Pillow bug.

**Pull request merged**
