### PR TITLE
Added .editorconfig to manifest

### PR DESCRIPTION
**Pull request by radarhere**
Adds .editorconfig to the manifest, after #1489

### CODE REVIEW

**Comment by wiredfool** [comment]
We don't need to distribute .editorconfig in binaries, it's a development only thing, nor the .gitattributes. 

I'm not sure about tox.ini, as that's potentially something used with a real install.

**Comment by radarhere** [comment]
Fair enough. I presumed this was the solution, given that Travis is currently failing - https://travis-ci.org/python-pillow/Pillow/builds/99594421

Ideas for an alternative solution?

**Comment by wiredfool** [comment]
Check-manifest is being too picky. We shouldn't have development time or source control cruft in there. e.g. the top level .gitignore isn't included in the Manifest, and that's probably the most important one of all of them. This should just be the items that we want to distribute for a source build.

**Comment by wiredfool** [comment]
This is in check-manifest:
```
# it's fine if any of these are missing in the VCS or in the sdist
IGNORE = [
    'PKG-INFO',     # always generated
    '*.egg-info',   # always generated
    '*.egg-info/*', # always generated
    'setup.cfg',    # always generated, sometimes also kept in source control
    # it's not a problem if the sdist is lacking these files:
    '.hgtags', '.hgignore', '.gitignore', '.bzrignore',
    '.travis.yml',
    # it's convenient to ship compiled .mo files in sdists, but they shouldn't
    # be checked in
    '*.mo',
]
```

So we should probably be ignoring more stuff manually in check-manifest.

**Comment by wiredfool** [comment]
Alternately, we can either ignore it in MANIFEST.in or in setup.py.

**Comment by radarhere** [comment]
So just `exclude` rather than `include` in MANIFEST.in?

**Pull request merged**
