### PR TITLE
Enable copr builds and add packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact @packit-service

The spec you see in this PR was fetched from your package's Fedora dist-git.

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR! 

This would probably be fine from me. I doubt I'd personally use the RPM packages for testing, but if this makes things easier for downstream packaging (does it?) then that's good.

And it would be good to be in Rawhide to potentially get feedback on new things in master before our main releases and Fedora releases. 

Some questions.

What sort of maintenance would these files need in the future? Would we do that or someone else?

Please could you link to another repo that already uses this, so we can see how it'd look? 

The lint check is failing because check-manifest didn't find any rules for the new files. Should they be included in the sdist or left out? Please could you update the manifest file?

Please could you remove the Python 2 stuff? The next release will drop it. 

I don't have access to add apps to this repo. @wiredfool or @aclark4life, what do you think about this PR and could you add the app?

**Comment by wiredfool** [comment]
* Half of the changes are a RH changelog of the RPM packages. I'm not clear that this repo is the appropriate place for that, nor is it likely to be maintained here going forward. 
* There's a hardcoded version in the spec file. We currently have a single version in the repo (src/PIL/_version.py). Inevitably, this will lead to version X.Y.Z being labeled with X-1.Q.W. For example, it's already out of date. 
* I'm not sure what constitutes a release where this would create an installable package that should be used by non-bleeding edge testers. We don't want to support anything except the most recent numerical releases. We wouldn't want people relying on random master snapshots. (Though, we can't prevent that with source installs, it's much less likely, as they need to at least assemble some dependencies and check out the code)

On the other hand, if this provides actual CI testing on non-x86 architectures (big-endian, ppc, ibm mainframes) then it's probably worth it. I'm not sure it's worth dropping our docker images for Fedora, as they do provide

**Comment by hugovk** [comment]
Thanks for the PR! 

This would probably be fine from me. I doubt I'd personally use the RPM packages for testing, but if this makes things easier for downstream packaging (does it?) then that's good.

And it would be good to be in Rawhide to potentially get feedback on new things in master before our main releases. 

Some questions.

What sort of maintenance would these files need in the future? Would we do that or someone else?

Please could you link to another repo that already uses this, so we can see how it'd look? 

The lint check is failing because check-manifest didn't find any rules for the new files. Should they be included in the sdist or left out? Please could you update the manifest file?

Please could you remove the Python 2 stuff? The next release will drop it. 

I don't have access to add apps to this repo. @wiredfool or @aclark4life, what do you think about this PR and could you add the app? 

Thanks!

**Comment by hugovk** [comment]
(Sorry for double posting, the first one didn't show up for some reason. Deleted!)

**Comment by aclark4life** [comment]
Thanks @dhodovsk ! 

@hugovk @wiredfool Yeah let's leave this one open for a while and see if we get some overwhelming support and/or desire by users for Fedora RPMs … otherwise, not necessarily screaming "must have" to me for Pillow at this point.

**Comment by TomasTomecek** [comment]
Dominika asked me to help her with answering your questions here. You asked good ones!

> And it would be good to be in Rawhide to potentially get feedback on new things in master before our main releases and Fedora releases.

That's exactly the intention here.

> What sort of maintenance would these files need in the future? Would we do that or someone else?

Our team (developers of the [packit project](https://packit.dev/)) would be glad to help.

For the RPM spec file - I understand it's pretty challenging to maintain that
file, so one of the solutions could be to work with the Fedora downstream
maintainer.

On the other hand, we can set this up in a way that the RPM spec file is
downloaded from Fedora git repositories all the time and not part of this PR.
This way you'd have the latest greatest (with all the ups and downs).

> Please could you link to another repo that already uses this, so we can see how it'd look?

Here's an example with RPM builds followed by testing in clean Fedora VMs:

https://github.com/ansible-community/ansible-bender/pull/190

> The lint check is failing because check-manifest didn't find any rules for the new files. Should they be included in the sdist or left out? Please could you update the manifest file?

They should be left out.

> Please could you remove the Python 2 stuff? The next release will drop it.

+1


>     * Half of the changes are a RH changelog of the RPM packages. I'm not clear that this repo is the appropriate place for that, nor is it likely to be maintained here going forward.

I'm assuming that the better variant would be then to download the RPM spec
file from Fedora and not store it here.

>     * There's a hardcoded version in the spec file. We currently have a single version in the repo (src/PIL/_version.py). Inevitably, this will lead to version X.Y.Z being labeled with X-1.Q.W. For example, it's already out of date.

When the spec file is used for building a PR, the version is replaced. Packit
gets version from git using `git describe`.

>     * I'm not sure what constitutes a release where this would create an installable package that should be used by non-bleeding edge testers. We don't want to support anything except the most recent numerical releases. We wouldn't want people relying on random master snapshots. (Though, we can't prevent that with source installs, it's much less likely, as they need to at least assemble some dependencies and check out the code)

You'll get an RPM for every PR with instructions how to install it - yep it's
really for people to test pull requests while they are being reviewed.

In packit, we don't support building the master branch for a project, yet.

> On the other hand, if this provides actual CI testing on non-x86 architectures (big-endian, ppc, ibm mainframes) then it's probably worth it. I'm not sure it's worth dropping our docker images for Fedora, as they do provide

These are the supported arches so far: fedora-rawhide-aarch64, fedora-rawhide-i386, fedora-rawhide-ppc64le, fedora-rawhide-x86_64

**Comment by radarhere** [comment]
> Yeah let's leave this one open for a while and see if we get some overwhelming support and/or desire by users for Fedora RPMs … otherwise, not necessarily screaming "must have" to add to Pillow at this point.

Closing, as there hasn't been movement here in over six months.

**Pull request closed without merging**
