### PR TITLE
Add Travis CI's Python versions to matrix

### PR DESCRIPTION
**Pull request by hugovk**
https://github.com/python-pillow/Pillow/blob/master/docs/installation.rst#platform-support

Travis CI uses Ubuntu 12.04 LTS Server Edition 64 bit, and is also tested on 3.4 and 3.5.

Travis CI also uses OS X Mavericks, and is also tested on 3.2 and 3.3. I've left out 3.5 because it's not yet passing.

---

We've been testing on Travis with Linux for a looong time, and on OS X for quite some time, but we only have Pillow 2.6.1 listed.

Should we also add all the versions since then, up to 3.0.0? 

For brevity, perhaps the point releases don't need listing, or just the latest point releases.

Examples:

 * 2.6.1,2.7.0,2.8.0,2.9.0,3.0.0

 * 2.6.2,2.7.0,2.8.2,2.9.0,3.0.0

### CODE REVIEW

**Comment by hugovk** [comment]
We should also add details for Windows builds on AppVeyor. Pythons 2.7, 3.3 and 3.4 are currently tested. What's the OS version?

https://ci.appveyor.com/project/Pythonpillow/pillow

**Comment by wiredfool** [comment]
It's Windows Server 2012 R2 (x64)  (from here: http://www.appveyor.com/docs/installed-software#operating-system)

**Comment by wiredfool** [comment]
I'd just leave the most recent one tested. We don't need a full list.

**Comment by hugovk** [comment]
Thanks, PR updated with only most recently tested and AppVeyor details.

**Pull request merged**
