### PR TITLE
Deprecate ImageOps undocumented functions

### PR DESCRIPTION
**Pull request by homm**
Todo: add release notes for ImageFilter.BoxBlur

### CODE REVIEW

**Comment by hugovk** [comment]
How long would this be deprecated before removing?

**Comment by wiredfool** [comment]
It's hard to tell from code searches, but it doesn't appear that many people are using this. 

Most of the hits are from our tests, or a blanket "from PIL.ImageOps import *" in PIL_compat template code.

**Comment by homm** [comment]
> How long would this be deprecated before removing?

This is not so huge change. I believe 2-3 versions or Pillow 5, if it comes earlier.

**Comment by homm** [comment]
release notes added

**Comment by wiredfool** [comment]
Still need to call out the deprecated functions in the release notes #2664

**Pull request merged**
