### PR TITLE
Add release notes for #3608, #3861 and #3886

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by olt** [comment]
Here is a snippet for the release notes for #3886, to avoid further last minute merge conflicts.

```
Image quality for JPEG compressed TIFF 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The TIFF encoder accepts a ``quality`` parameter for ``jpeg`` compressed TIFF files.
A value from 0 (worst) to 100 (best) controls the image quality, similar to the JPEG encoder. The default is 75. Example:``im.save("out.tif", compression="jpeg", quality=85)``
```

**Comment by hugovk** [comment]
Thanks! I'll add it to this PR.

**Comment by hugovk** [comment]
Added!

**Comment by hugovk** [comment]
Azure Pipelines passes. Not going to wait for Travis CI or AppVeyor to merge for this one.

**Pull request merged**
