### PR TITLE
Add a basic DDS image plugin with tests

### LINKED ISSUE #252: Request DDSImagePlugin
I would like to request the .dds(direct draw surface) format be decoded and added as an image plugin. I guess this is the right place for requests...?

I found this as a start. It doesn't do all dxt formats but some basic ones.
http://nullege.com/codes/show/src%40p%40i%40pilgrim-HEAD%40pilgrim%40codecs%40__init__.py/9/dds.DDS/python

### PR DESCRIPTION
**Pull request by hugovk**
This builds on PR https://github.com/python-pillow/Pillow/pull/1644 by @jleclanche.

Add unit tests with @Metallicow's test images from https://github.com/python-pillow/Pillow/pull/1644#issuecomment-169101551 ("License CC0/Public domain/PIL whatever").

I just picked the smallest of each image format.

DdsImagePlugin.py  is now [97.59% covered](https://coveralls.io/builds/4636297/source?filename=PIL%2FDdsImagePlugin.py); just four lines uncovered. They could perhaps be exercised with other test images.

Closes  #1644 and fixes #252.

### CODE REVIEW

**Comment by hugovk** [comment]
Should `decode565()`, `dxt1()` and `dxt5()` be prefixed with underscores to denote internal functions?

**Comment by jleclanche** [comment]
Like I was telling @wiredfool the other day, dxt1 and dxt5 should be implemented as pixel formats in `decode.c`if you really wanted to do it right.
And *ideally*, users should be able to pass pixel format decoders as callables rather than just strings (which forces you to implement them in decode.c).

But yeah the plugin I provided is meant to be a starting point.

**Comment by hugovk** [comment]
Yep, might be an idea to add that as TODOs in the code for now.

**Comment by jleclanche** [comment]
I filed the todo in #1652 where it won't bitrot.

Consider squashing some of your commits but the code looks good.

**Comment by wiredfool** [comment]
See #1654

**Pull request closed without merging**
