### PR TITLE
Fix bits value for RGB;16N unpackers

### LINKED ISSUE #3770: Compressed GeoTiff with GDAL no longer plotting with version 6.0.0
### What did you do?
Plotting an image with matplotlib `imshow()` broke with version 6.0.0

I have a compressed (LZW) GeoTiff that was produced by GDAL (v 2.4.1, released 2019/03/15). After upgrading from Pillow 5.4.1. to 6.0.0 the background image for a plot was no longer plotting properly.

### What are your OS, Python and Pillow versions?

* OS: Mac OS X and Linux
* Python: 3.7.3
* Pillow: 6.0.0

Code to reproduce:
```python
# Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
import matplotlib.pyplot as plt
plt.figure()
plt.imshow(plt.imread('/Path/To/sample.tiff'))
plt.show()
```

## With Pillow 5.4.1
pillow-5 4 1

## With Pillow 6.0.0
pillow-6

Used image: [sample.tif.zip](https://github.com/python-pillow/Pillow/files/3045702/sample.tif.zip)

## Compressed with GDAL (2.4.1):
```
gdal_translate -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER -co NUM_THREADS=ALL_CPUS -co COPY_SRC_OVERVIEWS=YES
```

### LINKED ISSUE #3832: 16 Bit Deflate tiff Image Corrupt
### What did you do?

i just opened 16bit deflate tiff files with Pillow Image.open function
and when i saved the file it just save the corrupted image

```python
im=Image.open("deflate_tif_1.tif")
im.save("bad_image_1.jpg")
```

### What did you expect to happen?

it should save the correct/same image

### What actually happened?

it is saving corrupted image

### What are your OS, Python and Pillow versions?

* OS: ubuntu

* Python: 2.7
* Pillow: 6.0.0

Sample Images

Deflate tiff (input file)
https://www.dropbox.com/s/hlm50c6z99hh9d2/deflate_tif_1.tif?dl=0

Bad Image produces
https://www.dropbox.com/s/csewdhjz2dhitek/bad_image_1.jpg?dl=0

```python

im=Image.open("deflate_tif_1.tif")
im.save("bad_image_1.jpg")

```

### PR DESCRIPTION
**Pull request by kkopachev**
Fixes #3770 . Fixes #3832. 

Changes proposed in this pull request:

Change bits value for `RGB;16N` unpackers. `bits` used in `TiffDecode.c` to calculate row size of a tile in bytes.

### CODE REVIEW

**Comment by kkopachev** [comment]
It was originally introduced in https://github.com/python-pillow/Pillow/commit/768668c1d7b1d78929e33a667bf1faa0592efceb but I guess `bits` are not directly used as much as I expected, so it became a problem when newer tiff decode code started relying on `bits` in #3489

**Comment by kkopachev** [comment]
Appveyor failure is totally unrelated to the proposed changes.

**Comment by radarhere** [comment]
Thanks for this. Are you able to add tests, that fail without this PR and pass with it?

**Comment by kkopachev** [comment]
I can only think about adding reading 16bit Tiff file as a test, but that would be indirect test. Not sure how to test just for bits value. Any suggestions?

**Comment by radarhere** [comment]
Reading a 16-bit TIFF file and comparing the result to another image should be right - testing just the unpacker entry value sounds rather specific.

**Comment by kkopachev** [comment]
Added test.

Test image is derived from existing test image `Tests/images/tiff_16bit_RGBa.tiff` using 
```
gdal_translate -co "TILED=YES" -co COMPRESS=DEFLATE tiff_16bit_RGBa.tiff -b 1 -b 2 -b 3 tiff_16bit_RGB.tiff
```

**Comment by radarhere** [comment]
I rebased on master so that AppVeyor could try again. Although Azure is now experiencing problems, at least Travis and AppVeyor are passing now.

**Pull request merged**
