### PR TITLE
Added width and height properties

### PR DESCRIPTION
**Pull request by radarhere**
As per the suggestion in #1279

This adds width and height properties to Image, so that in addition to `im.size`, users can also call `im.width` and `im.height`

### CODE REVIEW

**Comment by radarhere** [comment]
Like [the comment in #1298](https://github.com/python-pillow/Pillow/pull/1298#issuecomment-115579804), the AppVeyor build is experiencing problems getting the commit. However, [it passes on my own account](https://ci.appveyor.com/project/radarhere/pillow/build/2.9.pre.52)

**Comment by hugovk** [comment]
(Reported to AppVeyor here: https://github.com/appveyor/ci/issues/315 )

**Comment by hugovk** [comment]
Thanks!

PS a tip, writing something like "Fixes #1279" in the PR description will auto-close it once the PR is merged. Also works with commit messages:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by radarhere** [comment]
Thanks for the tip! Useful.

**Pull request merged**
