### PR TITLE
Add reading old-JPEG compressed TIFFs

### LINKED ISSUE #671: OJPEGPostDecode: Assertion `sp->libjpeg_session_active!=0' failed
While trying to save a, what seems to be broken, TIFF image as PPM the python interpreter crashes with the following error:

```python
>>> from PIL import Image
>>> image = Image.open(open("./bad.tiff"))
>>> image.save(open("/tmp/bad.ppm", "wb"), "PPM")
python: tif_ojpeg.c:848: OJPEGPostDecode: Assertion `sp->libjpeg_session_active!=0'    failed.
Aborted
```

This is happening with Python2.7.6 and Pillow2.4.0 running on Debian 6. 

Please let me know if I can provide you with any more information.

### LINKED ISSUE #3132: TIF old style jpeg compression
### What did you do?
I am trying to open and save a tif file. The problem with the file is that it uses old jpeg compression. You can replicate the issue with the one provided at https://github.com/openpreserve/format-corpus/tree/master/tiff-examples/old-style-jpeg-compression.

### What did you expect to happen?
Showing and saving the tif correctly.

### What actually happened?
With libtiff < 4.0.9 Pillow completely freezes and never returns anything or does not throw any exception. With libtiff 4.09 I receive the error ```OSError: -2``` and ```<PIL.TiffImagePlugin.TiffImageFile image mode=YCbCr size=4160x870 at 0x7FCF45E6C7F0>```.

### What versions of Pillow and Python are you using?

Python 3.6
Pillow 5.1.0
Libtiff 4.0.9

```python
from PIL import Image
img = Image.open('old-style-jpeg-compression.tif')
img
```

Identifying it in linux gives me 

```
identify: Unknown field with tag 33000 (0x80e8) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/881.
identify: Depreciated and troublesome old-style JPEG compression mode, please convert to new-style JPEG compression and notify vendor of writing software. `OJPEGSetupDecode' @ warning/tiff.c/TIFFWarnings/881.
```

Converting it with imagemagick gives me the same warnings, but successfully converts it to e.g., PNG which I can also read.

### PR DESCRIPTION
**Pull request by kkopachev**
Old-style JPEG compression in TIFFs are able to be read using Strip/Tile APIs. Although, it should be possible to read them using Scanline API, it does not work for some reason.  Anyway, reading subsampled YCbCr formats through Strip/Tile/Scanline libtiff API does not de-subsample the data, so caller should unpack data to whatever format is appropriate.  New-style JPEG compressed images were already read through libtiff as RGB images (https://github.com/python-pillow/Pillow/pull/3227). Unfortunately, there is no flag to ask libtiff to de-subsample old jpeg, but it provides a way to read any image as 32bit RGBA.  This commit adds ability to read old-style JPEG TIFFs through reading *all* YCbCr images as RGBX using Tile and Strip reading API. This supersedes previous work (PR #3227) to read new-style JPEG-TIFFs.

Fixes #671
Fixes #3132

Test image is from https://github.com/openpreserve/format-corpus/tree/master/tiff-examples/old-style-jpeg-compression and said there it's under CC0 license

### CODE REVIEW

**Comment by kkopachev** [comment]
@hugovk I fixed your comments. Should be better now.

**Comment by hugovk** [comment]
@homm I see you self-requested a review. Is this good to merge for the 2018-01-01 release, or would you like more time to check it?

**Comment by kkopachev** [comment]
@hugovk release notes added.

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
