### PR TITLE
Updated codecov action to v3

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by radarhere** [comment]
It does indeed perform this task - https://docs.renovatebot.com/modules/manager/github-actions/

I'm seeing good reviews on Google, so if you're also giving it a good review so far, I'm game.

**Comment by radarhere** [comment]
Adding Renovate should also improve our OpenSSF scorecard.

**Comment by hugovk** [comment]
Let's hold off on pinning these for now, there's some discussion and pushback on whether this is worthwhile:

https://tideliftlifters.slack.com/archives/C03NR6M8ELQ/p1661336955651269?thread_ts=1661336955.651269&cid=C03NR6M8ELQ

**Comment by radarhere** [comment]
Main has started failing in both [Test](https://github.com/python-pillow/Pillow/actions/runs/3116622673) and [Test MinGW](https://github.com/python-pillow/Pillow/actions/runs/3116415844). This PR would resolve those issues, by replacing the bash uploader with the GitHub action.

**Comment by hugovk** [comment]
Okay, let's get this merged!

First, I'll check the box at https://github.com/python-pillow/Pillow/issues/6604 to trigger Renovate so we can see it in action.

**Pull request merged**
