### PR TITLE
Add more detail to the appveyor test runs

### PR DESCRIPTION
**Pull request by wiredfool**
Allows us to see where a test is hanging on appveyor.

### CODE REVIEW

**Comment by radarhere** [comment]
I understand that you've added the verbose flag to AppVeyor, and I like the change to test-installed.py.

Why the s flag though? The man reads as 'don't add user site directory to sys.path'. What is the expected difference of this on AppVeyor builds?

**Comment by wiredfool** [comment]
It's from nosetests, short for `--nocapture`: don't capture stdout and let it flow unbuffered.

**Comment by radarhere** [comment]
Right, because if it was an argument applying to Python it would have to come before the reference to test-installed.py. Thanks for the explanation.

**Comment by homm** [comment]
👍

**Pull request merged**
