### PR TITLE
Test ImageDraw2

### PR DESCRIPTION
**Pull request by hugovk**
Changes proposed in this pull request:

* ImageDraw2.py was completely untested ([eg.](https://codecov.io/gh/python-pillow/Pillow/src/5ca35bbcb3837826e266b9f5a341f36fa99ca573/src/PIL/ImageDraw2.py))

* This tests it with 84% coverage

* Based on test_imagedraw.py

* Also removes `ImageDraw2.symbol`, which has only done `raise NotImplementedError("not in this version")` since PIL 1.1.6 (December 2006)

* Also test `ImageDraw.getdraw`, which returns `ImageDraw2` when no aggdraw found
  * Bumps ImageDraw.py coverage from 88% to 93%

* Helps towards #722

### CODE REVIEW

**Comment by hugovk** [comment]
This is failing on PyPy3 on AppVeyor, same thing as https://github.com/python-pillow/Pillow/issues/2992.

**Comment by hugovk** [comment]
Or rather, it's failing on AppVeyor, full stop.

Let's skip font tests on AppVeyor, like already done with ImageFont:

https://github.com/python-pillow/Pillow/blob/c013188594ba44fcd42e1adca3e4744e3983c2a0/Tests/test_imagefont.py#L45

**Comment by radarhere** [comment]
Looks like this Needs Rebase after #3133

**Comment by hugovk** [comment]
Rebased.

**Pull request merged**
