### PR TITLE
Removed use of spaces in TIFF kwargs, deprecated in 2.7

### PR DESCRIPTION
**Pull request by radarhere**
The discussion in #1087 indicates that this is not to be merged yet, to avoid skipping over deprecation warnings.

However, I thought I'd put this up with a 'Do Not Merge' label, so that it can be merged in the future.

### CODE REVIEW

**Comment by radarhere** [comment]
Now that 3.1 has been released, I've removed the 'Do Not Merge' label.

**Comment by wiredfool** [comment]
Deb Stretch freezes 2017-02-05, and until that point, the stable version is 2.6.x.  Unfortunately, the Jessie freeze was 1 month before the deprecation here, so we've hit the worst case on notification to debian.

**Comment by radarhere** [comment]
So then, if a similar freeze takes place after that, is it fair to merge this in for Pillow 3.6, for release in April 2017?

**Comment by wiredfool** [comment]
Yeah, should be.

**Comment by aclark4life** [comment]
Re-adding do not merge (until early January 2017) along with 3.6.0 milestone.

**Comment by radarhere** [comment]
Now that the master branch is 4.1.0dev0, this can be merged.

**Pull request merged**
