### PR TITLE
Move code from pillow-wheels

### PR DESCRIPTION
**Pull request by radarhere**
Helps #7390

As suggested in that issue, moves the https://github.com/python-pillow/pillow-wheels code into this main repository, in order to simplify the release process.

I have setup the new "Wheels" job to be triggered on
- manual builds
- changes to the workflow file or the wheels directory
- tags.

Regarding TravisCI
- I re-enabled branches and pull requests at https://app.travis-ci.com/github/python-pillow/pillow/settings.
- While I've added a commit to only run it on tags, it does not seem possible to filter TravisCI builds based on file changes. There is no mention of this at https://docs.travis-ci.com/user/conditions-v1, and https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979 said it wasn't possible earlier this year. I think we can work around this by triggering manual builds to test it when it is necessary.
- TravisCI will obviously not upload the wheels as GitHub Actions artifacts. It instead uploads them to GitHub releases. Maybe that's better?

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for starting on this!

Would it be possible to add the new files, preserving Git history from the old repo where possible? You never know when that info will be useful done the line. 

For example, there's a few options at https://stackoverflow.com/q/1365541/724176

**Comment by hugovk** [comment]
> * While I've added a commit to only run it on tags, it does not seem possible to filter TravisCI builds based on file changes. There is no mention of this at https://docs.travis-ci.com/user/conditions-v1, and https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979 said it wasn't possible earlier this year. I think we can work around this by triggering manual builds to test it when it is necessary.

Hmm, that's unfortunate, it's been requested since at least 2016, and I think only admins of this repo/org can trigger manual builds now? 

There's a couple of workarounds at https://github.com/travis-ci/travis-ci/issues/6301#issuecomment-313559284 and https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979/12?u=hugovk

But probably worth splitting out from this PR to make things easier to test/review.



> * TravisCI will obviously not upload the wheels as GitHub Actions artifacts. It instead uploads them to GitHub releases. Maybe that's better?

Yes, that sounds good, it's what it did in the old repo.

**Comment by radarhere** [comment]
> Would it be possible to add the new files, preserving Git history from the old repo where possible?

Ok, done.

**Comment by aclark4life** [comment]
Not entirely sure why, but I'm excited about the pillow-wheels code moving here (rollin' rollin' rollin') thanks @radarhere @hugovk

**Comment by hugovk** [comment]
> > * While I've added a commit to only run it on tags, it does not seem possible to filter TravisCI builds based on file changes. There is no mention of this at [docs.travis-ci.com/user/conditions-v1](https://docs.travis-ci.com/user/conditions-v1), and [travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979](https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979) said it wasn't possible earlier this year. I think we can work around this by triggering manual builds to test it when it is necessary.
> 
> Hmm, that's unfortunate, it's been requested since at least 2016, and I think only admins of this repo/org can trigger manual builds now?
> 
> There's a couple of workarounds at [travis-ci/travis-ci#6301 (comment)](https://github.com/travis-ci/travis-ci/issues/6301#issuecomment-313559284) and [travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979/12?u=hugovk](https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979/12?u=hugovk)
> 
> But probably worth splitting out from this PR to make things easier to test/review.

I'm currently most concerned about not being able to run Travis CI except during releases. I don't want us to find out on release day something has broken.

Can we try these workarounds and/or split Travis CI into its own PR?

**Comment by radarhere** [comment]
Ok, I've pushed a commit. TravisCI will run every time, but will exit early if the conditions are not met.

**Comment by hugovk** [comment]
Thanks!

Hmm, now I'm wondering if (lots of builds) x (exiting early) will nevertheless eat up our credits...

However, it looks like non-admins like us can restart builds and jobs (e.g. at https://app.travis-ci.com/github/python-pillow/Pillow/builds/266245399), and also trigger new builds, which is good.

@aclark4life The credits page that is only visible by admins. Please can you paste some screenshots of the current credits usage?

https://app.travis-ci.com/organizations/python-pillow/plan

**Comment by aclark4life** [comment]
Screenshot 2023-09-28 at 7 18 02 AM

**Comment by radarhere** [comment]
If tags and manual builds are too infrequent,
and early exiting all of the time (and continuing when relevant) is too frequent,
is tags, manual builds and a cron the middle path?

**Comment by hugovk** [comment]
At first I thought only admins could do manual builds, and thought that we'd only get builds for tags during release, which would be too infrequent. But happily I was wrong about that.

What we need is to build from tags for releases. That's fine.

Plus to be able to do some builds in between releases to prevent surprises. Manual builds is okay for that.

Plus, what I think is missing is to be able to see the results of PR changing the Travis related files. I guess we'll just have to hope for the best, merge, then do a manual build and iterate as needed?

**Comment by radarhere** [comment]
Ok, I've removed the commit to run Travis every time.

> Plus, what I think is missing is to be able to see the results of PR changing the Travis related files.

If there was concern, which I expect there isn't most of the time, we could push the PR as a branch to Pillow, and then trigger a Travis build of that Pillow branch.

**Comment by hugovk** [comment]
Yes, good idea! Thanks!

**Review by hugovk — APPROVED** [review]

**Comment by radarhere** [comment]
Previously, when we've done point releases, dependency updates merged into pillow-wheels are automatically incorporated into the newly released wheels.

It is worth noting that now that pillow-wheels is incorporated into this repository, we may want to take a moment when creating point releases to consider whether any dependency updates are important and should be cherry-picked in.

**Comment by hugovk** [comment]
Yes, good idea, let's keep it in mind when planning point releases.

**Pull request merged**
