### PR TITLE
Use Codecov for coverage

### PR DESCRIPTION
**Pull request by hugovk**
Because Coveralls has sometimes been a bit iffy and they rarely respond to support requests (eg. ["Changes Unknown when pulling X on branch into ** on master**"](https://github.com/lemurheavy/coveralls-public/issues/351) / ["First build on master"](https://github.com/lemurheavy/coveralls-public/issues/610)), I'd like to trial using Codecov for a while.

For example: https://codecov.io/gh/python-pillow/Pillow

We could use both Coveralls and Codecov in parallel for a while, to make sure they agree, and fine tune Codecov's notifications, and then decide which one to keep.

Here's some example PRs:
* https://github.com/hugovk/Pillow/pull/17: increase coverage
* https://github.com/hugovk/Pillow/pull/18: decrease coverage
* https://github.com/hugovk/Pillow/pull/19: increase and decrease

Thoughts?

### CODE REVIEW

**Comment by wiredfool** [comment]
Fine with me, as long as it doesn't spam each PR thread.

**Comment by hugovk** [comment]
[By default](https://docs.codecov.io/v4.3.6/docs/pull-request-comments) it only adds one comment and edits it on changes, but I've added a config file to disable commenting entirely.

Instead we can enable the GitHub status API, like we have for Travis, AppVeyor and Coveralls. That may need a webhook enabling at https://docs.codecov.io/v4.3.6/docs/commit-status by someone with more repo permissions than me.

**Comment by wiredfool** [comment]
It looks like the github integration is for github enterprise only. (https://github.com/integrations/codecov ) I'm not seeing any other way to get the status back into github, other than the comments.

**Comment by hugovk** [comment]
Let's just merge and see how it works on new PRs, and I'll get in touch with them if it's not working.

**Comment by hugovk** [comment]
@wiredfool I checked with Codecov, and the GitHub integration isn't just for GitHub Enterprise. Please could you install it? https://github.com/integration/codecov

**Comment by wiredfool** [comment]
I've enabled it, we'll see how it goes.

**Pull request merged**
