### PR TITLE
[WIP] Add a loader for the FTEX format from Independence War 2: Edge of Chaos

### PR DESCRIPTION
**Pull request by jleclanche**
This PR adds a CC0 loader for the ftex format from IW2:EOC.

FTEX has two modes: Uncompressed (rgb) and dxt1. Uncompressed files bear the .ftu extension, while compressed files use .ftc. The guys from Particle Systems were kind enough to have all their image files in both formats, which serves as a great test bed. I have included one of the uncopyrightable images from their set, in ftc and ftu.

This is useful as a battle-test of the dxt1 decoder which currently resides in PIL.DdsImagePlugin, and which I'd like to see moved to decode.c using a free library instead (see #1652 for more details). As it happens, the dxt1 decoder fails:

out

I'm not sure if the error is in the image plugin or in the decoder itself. I think it might be in the decoder. Regardless, since the RGB part of this works fine, I am filing this PR as a WIP to get a second pair of eyes on it.

### CODE REVIEW

**Comment by wiredfool** [comment]
See my ftex branch, will pr later. https://github.com/wiredfool/Pillow/tree/ftex

* The rawmode of the output of the _dxt1 decoder is 'RGBA' or 'RGBX', not 'RGB' (it kicks out 32b/pixel)
* The target image of the dxt1 decoder is uncompressed, so there are compression artifacts in the dxt1, so it's an imagesimilar compare. 
* It wasn't added to the PIL/__init__.py list for importing. 
* Mixing tabs and spaces. Fixed.

**Comment by jleclanche** [comment]
Sorry about the tabs. I develop with tabs; forgot to sed them out.

**Comment by jleclanche** [comment]
@wiredfool I squashed some commits and updated this PR.

**Comment by wiredfool** [comment]
No worries about the tabs, I get that on my work code base too.  I just managed to get that commit combined with the bug fix.

**Comment by wiredfool** [comment]
This is getting held up with manifest stuff, I'd like to wait on merging this till we have #1656 merged, and then we should be able to remove all of the manifest changes from this PR.

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/pull/1656 is now merged.

**Comment by jleclanche** [comment]
Shall I just remove a4efd51?

**Comment by wiredfool** [comment]
I've removed that one and rebased to master in my ftex branch, and it appears to be passing except for the known hangs in jpeg2k code.

**Comment by wiredfool** [comment]
I'll just merge that branch, now that the rerun test passed.

**Pull request closed without merging**
