### PR TITLE
Move auxiliary mypy requirements to a requirements file

### PR DESCRIPTION
**Pull request by akx**
For easier installation of those requirements outside tox.

### CODE REVIEW

**Comment by radarhere** [comment]
And the reason that you're not just moving these into .ci/requirements-mypy.txt is in case someone wants to use a type-checking system other than mypy?

That might be reasonable, sure, I just hope that we're not going to start down the road of trying to satisfy more than one type-checking tool at the same time.

**Comment by akx** [comment]
> And the reason that you're not just moving these into .ci/requirements-mypy.txt is in case someone wants to use a type-checking system other than mypy?

No, it was because I wasn't sure if there was a reason for these to have been in the toxfile to begin with 😅 

I can absolutely put them in `requirements-mypy.txt` too!

**Comment by akx** [comment]
Moved 'em all to `requirements-mypy.txt`.

**Comment by radarhere** [comment]
Thanks

**Pull request merged**
