### PR TITLE
Consider all frames when optimizing a GIF image

### PR DESCRIPTION
**Pull request by radarhere**
https://github.com/python-pillow/Pillow/issues/2314#issuecomment-274265583 raises a bug.

From what I can see, the problem is that not all of the frames in the image are being considered when optimizing. This PR fixes that.

### CODE REVIEW

**Comment by wiredfool** [comment]
I think what's going on here for subsequent frames is: 
1) The image difference doesn't take palette into account, it's essentially the `P` mode bytes interpreted as `L`. 
2) I don't think we're writing a local color table if the palette is different than the palette from the first image. 

I don't think stuffing all of the palettes into the first palette is going to be the right solution.

**Comment by wiredfool** [comment]
The test, at least, should be cherry picked into whatever solution comes up.

**Comment by radarhere** [comment]
I deleted this quickly after your initial comment, because I agreed that local color tables were a better idea.

However, in my further investigation of this, I came to a different conclusion about what the bug was - see PR #2375.

**Comment by wiredfool** [comment]
I think that 1 is still an issue, but I'm not sure on 2.

**Pull request closed without merging**
