### PR TITLE
Enable downloadable wheel builds on Appveyor

### PR DESCRIPTION
**Pull request by techtonik**
Addresses this problem - https://github.com/python-pillow/Pillow/issues/1811#issuecomment-206599115

An example - https://ci.appveyor.com/project/techtonik/pillow/build/3.3.pre.11/artifacts

### CODE REVIEW

**Comment by wiredfool** [comment]
Is there anything in the build script that has to change for this to work?

I think I'm going to merge this with a branch that's uploading to s3, so that they're hosted somewhere.

**Comment by techtonik** [comment]
Build script needed change to run two commands instead of one. Artifacts are hosted on Appveyor, but could be uploaded anywhere.

**Comment by radarhere** [comment]
So in light of #1818 being merged, this PR can either be closed, or at the very least reworked.

**Comment by techtonik** [comment]
Why pushing to S3 is better than leaving nighties on Appveyor?

**Comment by wiredfool** [comment]
Don't close, I'm going to pick bits from this.  #1818 does eggs, this does wheels, I think the wheels are probably better to use than the eggs. 

s3 gives up a record, it doesn't kill the ones on appveyor.

**Comment by techtonik** [comment]
Rebased.

**Comment by wiredfool** [comment]
Functionality included in #1927

**Pull request closed without merging**
