### PR TITLE
Fix comment about palette class in quantize method

### PR DESCRIPTION
**Pull request by kkopachev**
Changes documentation to reflect correct expected class

### CODE REVIEW

**Comment by wiredfool** [comment]
Palette is an image, see the remainder of the method:

```
        if palette:
             # use palette from reference image
             palette.load()
             if palette.mode != "P":
                 raise ValueError("bad mode for palette image")
             if self.mode != "RGB" and self.mode != "L":
                 raise ValueError(
                     "only RGB or L mode images can be quantized to a palette"
                     )
             im = self.im.convert("P", 1, palette.im)
             return self._new(im)
```

**Comment by kkopachev** [comment]
@wiredfool My attempt was to change doc so it says that palette is an image.
With current docs I was under impression that I have to pass `PIL.ImagingPalette` as an argument, which supposed to be extracted from `im.palette`. However, `quantize` wants `PIL.Image` object woth attached palette, not palette object itself. 
Do you see my intent here?

**Comment by wiredfool** [comment]
Sorry, I got that exactly backwards.

**Comment by wiredfool** [comment]
Thanks for catching this.

**Pull request merged**
