### PR TITLE
Test pypy2-v5.9.0-win32 [Do not merge]

### PR DESCRIPTION
**Pull request by cgohlke**
Pillow 4.3.0 segfaults on pypy2-v5.9.0-win32:

```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 4.3.0
platform     win32 2.7.13 (c2437cf9b7f1, Sep 24 2017, 17:23:53)
             [PyPy 5.9.0 with MSC v.1500 32 bit]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.1)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
*** RAQM support not available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
```

```
TestDecompressionCrop.testEnlargeCrop ... ok
RPython traceback:
  File "pypy_module_cpyext.c", line 6693, in wrapper_second_level__star_1_3
  File "pypy_module_cpyext_1.c", line 38392, in make_ref__StdObjSpaceConst_SomeInstance_NoneCons
Fatal RPython error: AssertionError

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

### CODE REVIEW

**Comment by cgohlke** [comment]
Confirmed. Also crashes on Appveyor.

**Comment by hugovk** [comment]
Do you think this is a Pillow or PyPy problem?

**Comment by cgohlke** [comment]
Probably a PyPy bug but I am not set up to debug on pypy...

**Comment by wiredfool** [comment]
FWIW, I'm not seeing this on pypy for ubuntu.

**Comment by hugovk** [comment]
It's coming from a `import PIL._webp`.

Here's the error on AppVeyor:
```
%PYTHON%\%EXECUTABLE% selftest.py --installed
--------------------------------------------------------------------
Pillow 4.4.0.dev0 TEST SUMMARY 
--------------------------------------------------------------------
Python modules loaded from C:\vp\pypy2\site-packages\pillow-4.4.0.dev0-py2.7-win32.egg\PIL
Binary modules loaded from C:\Users\appveyor\AppData\Local\Python-Eggs\Python-Eggs\Cache\pillow-4.4.0.dev0-py2.7-win32.egg-tmp\PIL
--------------------------------------------------------------------
--- PIL CORE support ok
--- TKINTER support ok
--- FREETYPE2 support ok
--- LITTLECMS2 support ok
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
RPython traceback:
  File "pypy_module_cpyext.c", line 6693, in wrapper_second_level__star_1_3
  File "pypy_module_cpyext_1.c", line 38392, in make_ref__StdObjSpaceConst_SomeInstance_NoneCons
Fatal RPython error: AssertionError
Command exited with code 3
```

It's failing in [features.py](https://github.com/python-pillow/Pillow/blob/master/PIL/features.py#L18):

```python
    try:
        imported_module = __import__(module)  # <--- HERE
        return True
    except ImportError:
        return False
```


Where `module == "PIL._webp"`, called from [selftest.py](https://github.com/python-pillow/Pillow/blob/master/selftest.py#L189).

**Comment by hugovk** [comment]
On a [pass build](https://ci.appveyor.com/project/Python-pillow/pillow/build/2997/job/thwsn5agm4r5la8g#L2696):
```
Done with pypy2: 0
```

On an [error build](https://ci.appveyor.com/project/Python-pillow/pillow/build/2996/job/ak1eoh9bx8roixi3#L2697):
```
Done with pypy2: 1
```

(Maybe we should end builds for non-zero statuses? https://github.com/python-pillow/Pillow/blob/master/winbuild/build.py#L44)

---

Error builds also have:
`error: [Error 32] The process cannot access the file because it is being used by another process: c:\users\appveyor\appdata\local\temp\1\easy_install-ggf5wq\olefile-0.44\olefile\README.rst
`

---

And are missing the confirmation `Finished processing dependencies for Pillow==4.4.0.dev0`:

image

**Pull request closed without merging**
