### PR TITLE
transpose() with multi-band format

### PR DESCRIPTION
**Pull request by yoursunny**

### CODE REVIEW

**Comment by radarhere** [comment]
This is an update for #8157 by one of the original authors, so I'm just going to merge it.

**Comment by aclark4life** [comment]
Yes, thanks! @yoursunny is the sole author of the fix for #1888 and @yoursunny please feel free to send additional PRs here. Thanks all ✨

**Comment by Yay295** [comment]
> @yoursunny is the sole author of the fix for #1888

Is no one else allowed to work on that or something? My apologies for attempting to improve the test coverage for the various image modes and data access methods I guess.

**Comment by aclark4life** [comment]
@Yay295 PRs welcome

**Comment by Yay295** [comment]
I've been adding tests. #7209 #7921

**Pull request merged**
