### PR TITLE
Fix exception handling when saving images

### PR DESCRIPTION
**Pull request by liZe**
The e variable is already used in the for loop, use exc to store the exception.

### CODE REVIEW

**Comment by radarhere** [comment]
Thanks for this. Is there a test situation that you know of that triggers the bug, so that we can add it to the test suite and prevent this from re-appearing in the future?

**Comment by liZe** [comment]
> Thanks for this. Is there a test situation that you know of that triggers the bug, so that we can add it to the test suite and prevent this from re-appearing in the future?

Sure!

```python
from io import BytesIO
from PIL import Image
Image.new('P', (1, 1)).save(BytesIO(), 'JPEG2000')
```

This should raise the OSError, not `TypeError: exception causes must derive from BaseException`.

**Comment by radarhere** [comment]
@liZe you've deleted your Pillow repository. I'd like to add the test situation you've mentioned though, so I've recreated this PR as #4885. Let us know if you have anything further to add.

**Comment by liZe** [comment]
> I'd like to add the test situation you've mentioned though, so I've recreated this PR as #4885. Let us know if you have anything further to add.

Sorry, I didn’t check, I thought it was already merged.

#4885 is OK for me!

**Pull request closed without merging**
