### PR TITLE
GitHub Action to add issue or PR to project

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/python-pillow/Pillow/issues/3844.

Changes proposed in this pull request:

 * When a PR or issue is opened, automatically add it to the "New Issues" column of the [Pillow](https://github.com/python-pillow/Pillow/projects/1) board

### CODE REVIEW

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/pull/4071/checks?check_run_id=226971660 shows:

```
Run alex-page/github-project-automation-plus@v0.0.3
#[error]GraphqlError: Resource not accessible by integration
##[error]Resource not accessible by integration
##[error]Node run failed with exit code 1
```

---

@aclark4life Please could you do steps 1 and 2 of https://github.com/alex-page/github-project-automation-plus#private-repositories?

> # Private repositories
> 
> In some cases you may want to do add this functionality for a private repository or one you do not have admin rights to. You may get an error like:
> ```shell
> GraphqlError: Resource not accessible by integration
> ```
> 
> When this happens you will need to:
> 1. Create a [personal access token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)
> 2. [Create a secret](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) containing the personal access token, call it `GH_PAT`
> 3. Change the `repo-token` in the `backlog-automation.yml`  to reference your new token name:
> ```yaml
> repo-token: ${{ secrets.GH_PAT }}
> ```

**Comment by aclark4life** [comment]
@hugovk Will do

**Comment by aclark4life** [comment]
@hugovk Hmmm, which perms do I need here?

Screen Shot 2019-09-20 at 9 08 56 AM

**Comment by hugovk** [comment]
I asked at https://github.com/alex-page/github-project-automation-plus/issues/10, let's try with `admin:org`.

**Comment by aclark4life** [comment]
@hugovk Steps 1 and 2 done!

Screen Shot 2019-09-21 at 4 55 54 PM
Screen Shot 2019-09-21 at 4 55 47 PM

**Comment by hugovk** [comment]
And step 3 done! 

The action was skipped, I think it'll only trigger when a PR is opened, not updated (makes sense). 

https://github.com/python-pillow/Pillow/pull/4071/checks?check_run_id=231170480

Will close and reopen!

**Comment by hugovk** [comment]
Still skipped. Will close and create a fresh PR.

**Pull request closed without merging**
