### PR TITLE
Fast unpacking and partially packing

### PR DESCRIPTION
**Pull request by homm**
Benchmarks:

```
                     Master           This branch
Unpack from L       4697.80 Mpx/s    4745.82 Mpx/s  # No changes
Unpack from LA       615.37 Mpx/s     782.75 Mpx/s
Unpack from RGB      571.12 Mpx/s    1419.82 Mpx/s
Unpack from RGBA    1373.62 Mpx/s    1390.41 Mpx/s  # No changes
Pack to L           2406.48 Mpx/s    2494.54 Mpx/s  # No changes
Pack to LA           727.90 Mpx/s     730.90 Mpx/s  # No changes
Pack to RGB          524.85 Mpx/s     777.51 Mpx/s
Pack to RGBA         669.26 Mpx/s     660.43 Mpx/s  # No changes
```

### CODE REVIEW

**Comment by wiredfool** [comment]
FWIW, this does pass all the tests on PPC/big endian.

**Comment by homm** [comment]
Should be rebased after #2694 merge

**Comment by homm** [comment]
Merged tests from #2694 there.

**Comment by homm** [comment]
Coverage reduced because number of lines in `Unpack.c` is reduced.

**Pull request merged**
