### PR TITLE
Search pkgconf system libs/cflags

### PR DESCRIPTION
**Pull request by jameshilliard**
We need to search the system paths as well from pkg-config for some packages to be found properly.

### CODE REVIEW

**Comment by radarhere** [comment]
> some packages

Could you elaborate on this a bit? It's potentially helpful to have this information to refer back to.

**Comment by jameshilliard** [comment]
> Could you elaborate on this a bit?

Zlib and anything that has headers in the normal system libs/include folders seems to not get their headers picked up without this change.

I think this issue is mostly going to be something people hit when cross compiling since the prefix based system libs/include folder would probably work in most of the usual cases(searching in `sys.prefix` will not work when cross compiling since it points to the host toolchain prefix rather than the target toolchain sysroot prefix):
https://github.com/python-pillow/Pillow/blob/0cf072db39bf1868575c625fc4403f388e5d47d4/setup.py#L494-L495

When cross compiling we try and make sure pkg-config points to the correct target sysroot however.

**Comment by jameshilliard** [comment]
@radarhere FYI there's some additional background/discussion around this issue [here](https://lore.kernel.org/buildroot/CA+_SqVYy6DXFsQ26VmAwhsjGjo232fqAH=WQbnMk9cJQwg=JzQ@mail.gmail.com/).

**Comment by jameshilliard** [comment]
@radarhere Tests should be passing now, I've re-based on `main` with #6229.

**Comment by radarhere** [comment]
Yes, the tests will pass now, but the failure revealed a problem - on main, [libtiff is detected](https://github.com/python-pillow/Pillow/runs/6089745828#step:8:37). On this branch, [it is not.](https://github.com/python-pillow/Pillow/runs/6103156939#step:8:37)

**Comment by jameshilliard** [comment]
> On this branch, [it is not.](https://github.com/python-pillow/Pillow/runs/6103156939#step:8:37)

Weird, on ubuntu 20.04 with `libtiff-dev` installed it seems to get detected fine for me.

**Comment by jameshilliard** [comment]
FYI there's a repo setting you can change so that you don't have to manually approve most workflows in pull requests:
Screen Shot 2022-04-22 at 12 17 36 PM

**Comment by radarhere** [comment]
Ok, I [stopped `_pkg_config` from catching exceptions](https://github.com/radarhere/Pillow/commit/8b654dcef5559d09b235fc5d2c262b6704955103), and it turned out there was an error occurring - "[Unknown option --keep-system-libs](https://github.com/radarhere/Pillow/runs/6139685074?check_suite_focus=true#step:7:31)".

If I try on my macOS machine,
```
$ pkg-config --keep-system-libs
Unknown option --keep-system-libs
$ pkg-config --keep-system-cflags
Unknown option --keep-system-cflags
```

So I guess those options are only available in certain environments. What is surprising though is that you say the flag works for you on your copy of Ubuntu 20.04, but it doesn't in GitHub Actions. Any ideas why that might be?

Perhaps a solution would be to try `--keep-system-libs` first, and then to try again without it if it doesn't work? https://github.com/jameshilliard/Pillow/pull/1

**Comment by jameshilliard** [comment]
> What is surprising though is that you say the flag works for you on your copy of Ubuntu 20.04, but it doesn't in GitHub Actions. Any ideas why that might be?

Yeah, not sure why that is happening.

> Perhaps a solution would be to try `--keep-system-libs` first, and then to try again without it if it doesn't work?

That seems to work for me, merged to my branch here.

**Comment by radarhere** [comment]
The version number is was helpful, thanks - I think you are using pkgconf, not pkg-config.

https://pkgs.org/download/pkg-config
pkgconf

There is apparently a "[compatibility interface](https://fedoraproject.org/wiki/Changes/pkgconf_as_system_pkg-config_implementation#Detailed_Description)" that means you can run it as pkg-config, hence the confusion.

**Comment by jameshilliard** [comment]
Ah, yeah, guess that explains why the fallback is needed for some systems.

**Review by radarhere — APPROVED** [review]

**Comment by jameshilliard** [comment]
Rebased on [`python-pillow:main`](https://github.com/python-pillow/Pillow).

**Comment by jameshilliard** [comment]
@radarhere This good to merge or anything else I should do?

**Pull request merged**
