### PR TITLE
A dirty solution to #891

### PR DESCRIPTION
**Pull request by jackyyf**
Currently we have no good solution to handle embedded bitmap fonts (#891), so we should avoid using them, until a final patch is available.

### CODE REVIEW

**Comment by jackyyf** [comment]
When will my pull request merged? I have to use custom hacked version of Pillow here and there in my own project :|

**Comment by aclark4life** [comment]
@jackyyf You probably need @wiredfool or @hugovk to review

**Comment by hugovk** [comment]
@jackyyf I'd like @wiredfool to check this.

In the meantime, you can pip install from your own branch, something like this:

    pip install git+https://github.com/jackyyf/Pillow.git@bitmap-hack

**Comment by wiredfool** [comment]
Sorry, I missed that you had added the font and the testcases. I'll take a look.

**Comment by wiredfool** [comment]
Looking @ this on my Mavericks machine, the tests are failing due to different font metrics between the bitmap and truetype font. 

On master, the test fails with `AssertionError:  average pixel value difference 152.1070 > epsilon 0.0100
`, in this branch it fails with `AssertionError:  average pixel value difference 76.0391 > epsilon 0.0100
`. Looking at the images that come out, it's just off by a pixel or so, offsetting the outline draw by 1 pixel gets the epsilon down to 10. This offset is what your original test had.  

Looking on Ubuntu,  the metrics and renderings pass the test as committed. 

On linux, size_outline = size_bitmap = (212, 28), on the mac: size_outline = (212, 27) size_bitmap = (212, 28). So if we take that into account, and up the permissible error to something like 20, we should be able to easily distinguish between failures and successes. 

I've put that together on my wiredfool:pr960 branch. Once the tests pass, I'll merge that.

**Comment by hugovk** [comment]
#1072 merged.

Thanks!

**Comment by homm** [comment]
> Coverage increased (+11.3%) to 85.345% 

Whoa!

**Comment by hugovk** [comment]
A Coveralls glitch, unless Pillow has been replaced by two .js files without me noticing: https://coveralls.io/builds/6232236

**Pull request closed without merging**
