### PR TITLE
add functions to convert: Image <-> QImage; Image <-> QPixmap (see #897)

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by aclark4life** [comment]
#897

**Comment by aclark4life** [comment]
@rominf Still working on this?

**Comment by rominf** [comment]
Nope, I forgot about this (it became irrelevant for me). May be someone else can fix this?

**Comment by aclark4life** [comment]
Dunno. Unmerged PRs can be reopened later (I think) so I'll close this for now. Thanks

**Pull request closed without merging**
