### PR TITLE
PyPy3 on AppVeyor

### PR DESCRIPTION
**Pull request by nulano**
Adds PyPy3 to AppVeyor.

From https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507408755:
> Our tests didn't pick it up because we don't test PyPy3 on Windows; [...] We should improve these testing gaps.

Using a nightly build due to:

 * https://bitbucket.org/pypy/pypy/issues/3036/tkinter-unicodeencodeerror-mbcs-codec-cant
 * https://bitbucket.org/pypy/pypy/issues/3079/systemerror-in-timestrptime-with-non

PyPy3 is set to run last because this is not a stable release.

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for this!

I'm cautious about using a nightly build, in case pre-release PyPy bugs fail the build. It'd be annoying for that to happen after an hour!

If certain tests are failing on a given PyPy3 version, we can add a conditional `skipIf` on `is_pypy` and that particular version, and then update when the next PyPy release is out.

**Comment by radarhere** [comment]
Note that I've created PR #4083 as an alternative fix for https://bitbucket.org/pypy/pypy/issues/3079/systemerror-in-timestrptime-with-non

**Comment by nulano** [comment]
The first linked issue causes a crash in `selftest.py`: https://ci.appveyor.com/project/nulano/pillow/builds/27564402/job/j7ugyr3o4nxw0g77#L6455
I'm not sure if that can be skipped reasonably.

**Comment by nulano** [comment]
See https://bitbucket.org/pypy/pypy/issues/3037/pypy36-release-schedule-new-beta-quality

> We don’t have a release schedule. We try to release twice a year, so I guess the time is getting close. The nightly builds should be quite reliable, is there a reason you cannot use them?

> We don't have a release schedule. With that, we may be releasing a new version by the end of September

Perhaps this can wait for pypy-7.2.0?

**Comment by hugovk** [comment]
Yeah, the end of September would be good timing, we're removing PyPy2 after the 1st October release. And let's check #4083.

@radarhere Any thoughts on using the nightly until the next release, or waiting until it the next release is out?

**Comment by nulano** [comment]
> I'm cautious about using a nightly build, in case pre-release PyPy bugs fail the build. **It'd be annoying for that to happen after an hour!**

If you'd prefer, I can remove the last commit and put PyPy3 at the top, as I had it while working on this.

**Comment by hugovk** [comment]
Let's leave it where it is. If it was first, it's not obvious if a failure is from your changes or nightly.

When the next official release is out, we can reconsider the position.

Thank you!

**Pull request merged**
