### PR TITLE
Removed unittest mock

### PR DESCRIPTION
**Pull request by radarhere**
Helps #4193

Suggestion to replace unittest `mock` with custom code, including a context manager.

### CODE REVIEW

**Comment by coiax** [comment]
`unittest.mock` is an excellent toolkit for mocking and patching, and using it doesn't mean you have to use `unittest` style tests, surely?

**Comment by radarhere** [comment]
No, it doesn't. I created this PR separate to other unittest related changes because I felt it was more debatable. So if you think this shouldn't be included, that's valid, and we'll see what others think.

**Comment by nulano** [comment]
Why not use the [pytest alternative](https://docs.pytest.org/en/latest/monkeypatch.html)?

**Comment by radarhere** [comment]
@nulano because I didn't see it? Thanks. I've added it to PR #4486

**Comment by nulano** [comment]
@radarhere Apologies if I worded that poorly, it was merely a suggestion.

**Comment by radarhere** [comment]
@nulano not at all, good suggestion

**Pull request closed without merging**
