### PR TITLE
Only ask for YCbCr->RGB libtiff conversion for jpeg-compressed tiffs

### LINKED ISSUE #3413: Unknown pseudo-tag 65538
### What did you do?

Put program and file below in same directory. Ran program.

### What did you expect to happen?

Get two copies of the file, each a little bigger.

### What actually happened?

Well, it worked, but it produced the following error:
```
TIFFSetField: tempfile.tif: Unknown pseudo-tag 65538.
```

Since the original image is .png, it would seem that Pillow introduced the unknown pseudo-tag, and then complained about it.

The tag seems to be a deprecated tag for some form of JPEG compression inside TIFF, but I specified, explicitly, ZIP compression ('tiff-deflate'), so the unknown/deprecated tag is a surprise.

### What are your OS, Python and Pillow versions?

* OS: windows 10
* Python: 3.6
* Pillow: 5.3

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
from PIL import Image, ImageOps
def foo():

    im = Image.open('testovauto.png')
    im = ImageOps.expand( im, 44, 0xffffff )
    im.save('testout.tif', dpi=(300.0, 300.0), compression='tiff_deflate')
    print('hi there')
    im = Image.open('testout.tif')
    im = ImageOps.expand( im, 44, 0xffffff )
    im.save('testout2.tif', dpi=(300.0, 300.0), compression='tiff_deflate')
    print('hi there')
    im = Image.open('testout2.tif')
    im = ImageOps.expand( im, 44, 0xffffff )
    im.save('testout3.tif', dpi=(300.0, 300.0), compression='tiff_deflate')


foo()
```

testovauto.png: https://user-images.githubusercontent.com/3078240/47123380-e447b280-d22f-11e8-97a4-6c18ed22045d.png

### PR DESCRIPTION
**Pull request by kkopachev**
JPEG-related tiff pseudo-tags are registered only when tiff image has jpeg compression. Trying to set TIFFTAG_JPEGCOLORMODE on non jpeg-compressed file prints error "Unknown pseudo-tag 65538".

Fixes #3413 .

Changes proposed in this pull request:

 * Only set `TIFFTAG_JPEGCOLORMODE` pseudo-tag for jpeg-compressed TIFF images.

### CODE REVIEW

**Comment by kkopachev** [comment]
@hugovk Since the line where we set pseudo-tag only applies to jpeg-compressed tiffs, it's being covered already. I am not sure how to test for (not)presense of stderr output and this is only thing this patch addresses.

**Comment by kkopachev** [comment]
Added tabs->spaces conversion as separate commit https://github.com/python-pillow/Pillow/pull/3417/commits/28cdb993b9e35fc8ee23ce3166d768f11d0c4f06?w=1

**Comment by hugovk** [comment]
I've confirmed locally (macOS High Sierra/Python 3.7.0) that "Unknown pseudo-tag 65538" is no longer shown.

Thank you!

**Comment by GizmoTechy** [comment]
By chance, do we know when this build will be pushed to PyPi?

**Comment by hugovk** [comment]
Releases are quarterly, next one due on 2019-01-01.

**Comment by GizmoTechy** [comment]
> 
> 
> Releases are quarterly, next one due on 2019-01-01.

Thank you. I appreciate the quick reply.

**Pull request merged**
