### PR TITLE
Docs: Remove docutils pin

### PR DESCRIPTION
**Pull request by hugovk**
This reverts commit 9509a73ed9080640d8d6b95f514b77329d123fa1.

Changes proposed in this pull request:

 * Undo PR https://github.com/python-pillow/Pillow/pull/5704 now Sphinx 1.0.0 has been released
 * https://github.com/readthedocs/sphinx_rtd_theme/releases/tag/1.0.0
 * https://github.com/readthedocs/sphinx_rtd_theme/tags

### CODE REVIEW

**Comment by hugovk** [comment]
First build still missing bullet points:

image

https://pillow--5821.org.readthedocs.build/en/5821/releasenotes/8.3.2.html

Because it's still installing the old one:

```
Collecting sphinx-rtd-theme<0.5
  Downloading sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl (6.4 MB)
```

https://readthedocs.org/api/v2/build/15217187.txt

Need to update this.

**Comment by hugovk** [comment]
There we go!

image

**Comment by nulano** [comment]
And there is a fresh new look for functions!
image
(although the "Parameters:" title could use a bit of `padding-right`)

Old version for comparison:
image

**Comment by radarhere** [comment]
Thanks!

**Pull request merged**
