### PR TITLE
Updated TIFF tile descriptors to match current decoding functionality

### LINKED ISSUE #3756: AttributeError: module 'PIL._imaging' has no attribute 'group4_decoder'
### What did you do?

Executed this a script (code below) to get the dimensions of a tiff group4 image.

### What did you expect to happen?

I expected that the dimensions of the images would be printed

### What actually happened?

crash with the error

```
AttributeError: module 'PIL._imaging' has no attribute 'group4_decoder'
```

full output:

```
['DEFAULT_STRATEGY', 'FILTERED', 'FIXED', 'HAVE_LIBJPEGTURBO', 'HUFFMAN_ONLY', 'PILLOW_VERSION', 'RLE', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'alpha_composite', 'bcn_decoder', 'bit_decoder', 'blend', 'clear_cache', 'convert', 'draw', 'effect_mandelbrot', 'effect_noise', 'eps_encoder', 'fill', 'fli_decoder', 'font', 'get_alignment', 'get_block_size', 'get_blocks_max', 'get_stats', 'getcodecstatus', 'gif_decoder', 'gif_encoder', 'hex_decoder', 'hex_encoder', 'jp2klib_version', 'jpeg2k_decoder', 'jpeg2k_encoder', 'jpeg_decoder', 'jpeg_encoder', 'jpeglib_version', 'libtiff_decoder', 'libtiff_encoder', 'libtiff_version', 'linear_gradient', 'map_buffer', 'merge', 'new', 'outline', 'packbits_decoder', 'path', 'pcd_decoder', 'pcx_decoder', 'pcx_encoder', 'radial_gradient', 'raw_decoder', 'raw_encoder', 'reset_stats', 'set_alignment', 'set_block_size', 'set_blocks_max', 'sgi_rle_decoder', 'sun_rle_decoder', 'tga_rle_decoder', 'tga_rle_encoder', 'wedge', 'xbm_decoder', 'xbm_encoder', 'zip_decoder', 'zip_encoder', 'zlib_version']
5.4.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 455, in _getdecoder
    decoder = getattr(core, decoder_name + "_decoder")
AttributeError: module 'PIL._imaging' has no attribute 'group4_decoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 36, in <module>
    print(dimensionsFromBlobImage(blob))
  File "bug.py", line 24, in dimensionsFromBlobImage
    ImPar.feed(chunk)
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFile.py", line 416, in feed
    im.mode, d, a, im.decoderconfig
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 458, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
OSError: decoder group4 not available
```

### What are your OS, Python and Pillow versions?

* OS: Linux Debian (reproduced it on stable and sid)
* Python: 3.7.2+
* Pillow: 5.4.1

Note that I do have `libtiff5` and `libtiff5-dev` installed.

Here's the script:

```python
import PIL
from PIL import Image, TiffImagePlugin
from PIL import ImageFile

TiffImagePlugin.READ_LIBTIFF=True
print(dir(PIL._imaging))
print(PIL.PILLOW_VERSION)

def dimensionsFromBlobImage(blob):
    ImPar = ImageFile.Parser()
    chunk = blob.read(2048)
    while chunk != "":
        ImPar.feed(chunk)
        if ImPar.image:
            break
        chunk = blob.read(2048)
    return ImPar.image.size


with (open("I1GS1051890001.tif", mode='rb')) as blob:
    print(dimensionsFromBlobImage(blob))
```

and the image:

[I1GS1051890001.tif.zip](https://github.com/python-pillow/Pillow/files/3017275/I1GS1051890001.tif.zip)

Note that the script works fine when replacing the function with:

```python
def dimensionsFromBlobImage(blob):
    im = Image.open(blob)
    return im.size
```

### PR DESCRIPTION
**Pull request by dmnisson**
Fixes #3756.

### CODE REVIEW

**Comment by dmnisson** [comment]
seems to break other TIFF decoding, please don't merge yet

**Comment by dmnisson** [comment]
Some of the tests might still fail because they still expect the old tile descriptors.

**Comment by radarhere** [comment]
Your first commit includes unrelated raqm-cmake files. Would you be able to remove those?

**Comment by hugovk** [comment]
We should probably do a rebase or squash and merge to remove the addition and removal commits.

image

**Comment by radarhere** [comment]
I've rebased and moved the addition and removal of the extra files.

**Comment by hugovk** [comment]
Thanks.

**Pull request merged**
