### PR TITLE
use png when converting from a QImage to a Pillow Image

### PR DESCRIPTION
**Pull request by ericfrederich**
ppm doesn't have an alpha channel
png has alpha channel, should be able to convert back and forth now
without losing anything

### CODE REVIEW

**Comment by hugovk** [comment]
@ericfrederich The build fails: 
https://travis-ci.org/python-pillow/Pillow/jobs/80514177#L2224

The others pass, but the failing Python2.7_with_system_site_packages is the only one to test with Qt.

**Comment by ericfrederich** [comment]
@hugovk Please review again.  It no longer errors out.

My goal was to preserve alpha while round tripping.  This now works so I'd appreciate the merge.

I added tests for this an discovered a bug.
Essentially Qt's QImage wants data to be 32-bit aligned.
This happens by chance depending on the mode and dimensions.
In the cases where it doesn't happen by chance I commented out the failing combinations.

I will write the code to guarantee the alignment and then cleanup the test file.

**Comment by wiredfool** [comment]
Is this going to require zlib to work?

**Comment by ericfrederich** [comment]
@wiredfool why would it require zlib to work?

**Comment by wiredfool** [comment]
Because png has a dependency on zlib.

**Comment by ericfrederich** [comment]
@wiredfool this fix is about round-tripping between PIL and Qt.  I couldn't imagine a system which has Qt but no zlib.  How would you suggest to preserve alpha?

**Comment by ericfrederich** [comment]
I rebased this on top of #1430 since some tests depended on it which had to be commented out.
This ordering of the two is now cleaner.

**Comment by wiredfool** [comment]
Looks like zlib is required for qt, so as long as we have a functioning pillow install, this should work. However, since we don't actually compile against qt (its just a runtime thing), a badly installed pillow that doesn't have any of the optional C dependencies would break here. On the other hand, I'm really pushing for zlib as a required dependency.

**Pull request merged**
