### PR TITLE
Setting transparency value to 0 when the tRNS contains only null byte(s)

### PR DESCRIPTION
**Pull request by juztin**
Addresses Issue #1238.

Simple checking when the `tRNS` contains only `null` byte(s) then the transparency value gets set to `0`.

### CODE REVIEW

**Comment by hugovk** [comment]
Any chance to add tests?

**Comment by juztin** [comment]
Sure thing. I'll get something done this weekend.

**Comment by juztin** [comment]
Sorry for the delay on getting that test done, busy weekend =S

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
