### PR TITLE
yapf-formatting for setup.py

### PR DESCRIPTION
**Pull request by aclark4life**
I know folks don't universally agree on using yapf, but I've been using it a lot lately elsewhere & propose we start using it on a file-by-file basis here.

### CODE REVIEW

**Comment by aclark4life** [comment]
@python-pillow/pillow-team Thumbs up/down? Thanks

**Comment by radarhere** [comment]
I have a slight concern over the fact that formatting entire files like this could obscure the change history, but only slight. Otherwise no objections. Curious about the plans for file-by-file transition.

**Comment by aclark4life** [comment]
@radarhere Right. I though we gained some clarify by isolating "white space" cleanup in a separate commit, but maybe not. I suppose any diff between the "first commit" and this one (and after) would be confusing. So then the question becomes: does anyone care. I do, but I care *more* about cleanup. My motivation now is to look at ``setup.py`` without vomiting (and yapf-formatting helps me do that). As for other plans, there are none. There is a ticket somewhere where we debated yapf-formatting the entire repo, but I'm sure that will never happen. If anything, I may be interested in yapf-formatting more than just ``setup.py`` sometime in the future, but it's not a big concern.

**Comment by wiredfool** [comment]
Nice bikeshed color. 

In this case yapf is better than whatever other flake8 we were using. It's also closer to the native emacs version. It's still a pain to trace back code to where it was originally committed to find intention, but I'm not clear that it's going to get significantly harder. It's another step or two or three. 

OTOH, I'm like >< this close to doing clang-format on all of the C code to once and for all get rid of the mixed 8 tab/spaces -> all 4 spaces, get all the braces on a consistent style, enclose single lines in braces, and generally make it all consistent.

**Comment by aclark4life** [comment]
@wiredfool Do it! I used clang-format recently over here and loved the results: https://github.com/aclark4life/CS. OK I'm going to merge this since no one cares (enough) to veto.

**Pull request merged**
