### PR TITLE
How to report security vulnerabilites

### PR DESCRIPTION
**Pull request by hugovk**
See https://github.com/python-pillow/Pillow/issues/1658

Something like this?

### CODE REVIEW

**Comment by aclark4life** [comment]
Looks great, thanks. I would add we should probably start to think about getting a domain (e.g. `python-pillow.org` so we can setup appropriate email addresses (e.g. `security@python-pillow.org`)

**Comment by wiredfool** [comment]
Yeah, I was just thinking about a domain this morning.

**Comment by aclark4life** [comment]
Anyone got a preferred registrar? I will pursue registration of ``python-pillow.org`` (assuming no better suggestions.)

**Comment by wiredfool** [comment]
Somewhere you've already got domains.  Or I can toss it on one of my accounts @ dreamhost or amazon where it can be managed with the rest of them.

**Comment by aclark4life** [comment]
@wiredfool DirectNIC it is! Here we go…

**Comment by aclark4life** [comment]
Done… will open new ticket to discuss management of domain.

**Pull request merged**
