### PR TITLE
Only prevent repeated polygon pixels when drawing with transparency

### PR DESCRIPTION
**Pull request by radarhere**
#4333 prevented polygon pixels from being drawn more than once, so that the transparencies of pixels would not be combined to create an unintended result.

However, #5700 reported that this results in a speed decrease.

This PR switches back to the earlier, faster method of drawing pixels repeatedly - when drawing without transparency. This means that the slower method to avoid the transparency problem is not used when it does not need to be used.

### CODE REVIEW

**Comment by ntninja** [comment]
Thank you! I will test this shortly and report back!

**Comment by ntninja** [comment]
I can confirm this works in our setup, thank you!

**Comment by hugovk** [comment]
@ntninja Thank you for testing!

@radarhere Thank you for the PR! Can we add tests to cover the `(hasAlpha == 1)` branch?

**Comment by radarhere** [comment]
Ah, I had presumed that the test from #4333 would still cover this situation, but #4523 changed ellipses so that they are no longer polygons.

Ok, I've added a test.

**Comment by hugovk** [comment]
Thanks both!

**Pull request merged**
