### PR TITLE
Don't raise IndexError when GPS IFD tag is missing

### LINKED ISSUE #4215: "tuple index out of range" when using exif_transpose
I took a picture with my phone and am trying to call `exif_transpose()` on it, but I'm getting a "tuple index out of range" error.

Here's the traceback:

```python
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 108, in sentry_patched_wsgi_handler
    return SentryWsgiMiddleware(bound_old_app)(environ, start_response)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 120, in __call__
    reraise(*_capture_exception(hub))
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 116, in __call__
    _sentry_start_response, start_response, span
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 140, in sentry_patched_get_response
    return old_get_response(self, request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stavros/Code/Django/imgz/main/views.py", line 102, in image_upload
    image = Image.objects.create(data=data, user=user, name=name)
  File "/home/stavros/Code/Django/imgz/main/models.py", line 82, in create
    return super().create(*args, **kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/stavros/Code/Django/imgz/main/models.py", line 168, in save
    self.transpose_image()
  File "/home/stavros/Code/Django/imgz/main/models.py", line 160, in transpose_image
    transposed = ImageOps.exif_transpose(img)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/ImageOps.py", line 549, in exif_transpose
    transposed_image.info["exif"] = exif.tobytes()
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/Image.py", line 3212, in tobytes
    ifd[tag] = value
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 540, in __setitem__
    self._setitem(tag, value, self.legacy_api)
  File "/home/stavros/.virtualenvs/imgz/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 605, in _setitem
    dest[tag] = values[0]
IndexError: tuple index out of range
```

Here is the EXIF data. You can see that the cause is `(34853, {})`:

```
[(36864, b'0220'), (37121, b'\x01\x02\x03\x00'), (37377, (4321, 1000)), (36867, '2019:11:19 03:47:56'), (36868, '2019:11:19 03:47:56'), (37378, (161, 100)), (37379, (-383, 100)), (37380, (0, 6)), (37381, (161, 100)), (37383, 2), (37384, 21), (37385, 16), (37386, (4770, 1000)), (40961, 1), (40962, 4000), (41990, 0), (37520, '679949'), (37521, '679949'), (37522, '679949'), (40963, 3000), (257, 3000), (271, 'Xiaomi'), (272, 'Redmi K20'), (41495, 1), (531, 1), (33434, (1, 20)), (40965, 717), (282, (72, 1)), (33437, (175, 100)), (41729, b'\x01'), (283, (72, 1)), (34850, 2), (34853, {}), (34855, 983), (296, 2), (41986, 0), (40960, b'0100'), (256, 4000), (41987, 0), (306, '2019:11:19 03:47:56'), (41989, 26), (34665, 212)]
```

Is there any way I can work around this?

### PR DESCRIPTION
**Pull request by WhyNotHugo**
I've a bunch of images which seem to have this tag missing (apparently generated with some phones?), and running them through
`ImageOps.exif_transpose` raises `IndexError`.

Regrettably, I can't share any of the sample images since they belong to my client's client's.

Fixes #4215

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Actually, the image in [this comment](https://github.com/python-pillow/Pillow/issues/4215#issuecomment-665743276) fails before this patch and passes with it, so would be a perfect candidate to be included for a test.

Is it okay to add it into the repo? It's 1.4MB.

**Comment by nulano** [comment]
I've used ImageMagic to crop the image from that comment down to 2KB:

out

You can use this instead, assuming @dmig-alarstudios is ok with it being included in Pillow.

**Comment by WhyNotHugo** [comment]
Updated PR with a sample image and test.

**Comment by radarhere** [comment]
Hi. So, the fact that there isn't GPS data present is not actually the cause of the problem. Pillow isn't handling GPS correctly even when it is present, it's just that it only warns about it normally, rather than throwing an error. I've created #4862 to fix the situation.

**Comment by WhyNotHugo** [comment]
I'll admit I am a bit our of my area of expertise here.

All I can say is that I see large volumes of photos missing that tag, and an `IndexError` is raised. I've shifted that to a warning, mostly to follow the Robustness Principle:

> Be conservative in what you send, be liberal in what you accept

If #4851 allows parsing these images (keeping the rotation data intact, since I need to rotate them), I'm fine with closing this PR in favour of that. Would you mind using the test image from here in a unit test, just to confirm that?

**Comment by radarhere** [comment]
Thanks for your willingness to jump in and try to solve the issue by the way.

I've checked the test image from the issue on my machine. Regarding adding it to the PR, @dmig-alarstudios hasn't actually granted us permission to use the image yet, so I'm going to hold off for now at least.

**Comment by dmig-alarstudios** [comment]
> I've checked the test image from the issue on my machine. Regarding adding it to the PR, @dmig-alarstudios hasn't actually granted us permission to use the image yet, so I'm going to hold off for now at least.

What??? Since it's posted here -- it's granted to use by anyone.

**Comment by radarhere** [comment]
Just posting an image here doesn't mean that anyone can do anything with it. We're asking if we are allowed to include the image, or a variation of it, as part of our test suite and distribute it with Pillow under the [Pillow license](https://github.com/python-pillow/Pillow/blob/master/LICENSE).

**Comment by dmig-alarstudios** [comment]
Use it as much as you need. Wherever required.

**Comment by radarhere** [comment]
I've added the [smaller test image](https://github.com/python-pillow/Pillow/pull/4851#issuecomment-673164846) to PR #4862.

So, closing in favour of that.

**Comment by WhyNotHugo** [comment]
@radarhere Thanks for addressing this! :)

**Pull request closed without merging**
