### PR TITLE
gif doc improved

### PR DESCRIPTION
**Pull request by d-schmidt**
- missing closing brackt
- EOFError mentioned

### CODE REVIEW

**Comment by aclark4life** [comment]
screenshot 2015-06-30 07 57 48

**Comment by hugovk** [comment]
That pypy3 failure was:
```
cc -shared -coverage build/temp.linux-x86_64-3.2/_imagingtk.o build/temp.linux-x86_64-3.2/Tk/tkImaging.o -L/lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -ltcl8.5 -ltk8.5 -o /home/travis/build/python-pillow/Pillow/PIL/_imagingtk.pypy3-24.so
Exception AssertionError: AssertionError('can only test a child process',) in weakref callback of <weakref at 0x00000000059067e0; dead> ignored
Exception AssertionError: AssertionError('can only test a child process',) in weakref callback of <weakref at 0x000000000529a3e0; dead> ignored
Exception AssertionError: AssertionError('can only test a child process',) in weakref callback of <weakref at 0x000000000529b1a0; dead> ignored
Exception AssertionError: AssertionError('can only test a child process',) in weakref callback of <weakref at 0x000000000529bfe0; dead> ignored
building 'PIL._imagingmath' extension
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
Most likely https://github.com/python-pillow/Pillow/issues/1176. I've restarted the build job.

**Comment by hugovk** [comment]
Both CIs now pass. 

I wouldn't worry about the Coveralls "failure", it's only recorded the coverage from the restarted job and not the other, older ones.

Anyway, this is just a comment change :)

**Comment by aclark4life** [comment]
Bah! Even comments must pass! :smile: Thanks

**Pull request merged**
