### PR TITLE
Modified ImageSequence Iterator class to be an iterator

### LINKED ISSUE #1648: ImageSequence.Iterator name is misleading
Hi Pillow developers,

I found this error message to be rather hilarious:
```
TypeError: 'Iterator' object is not an iterator
```
which was produced by this code:
```python
from PIL import Image, ImageSequence

with Image.open('multipage.tiff', mode='r') as tif:
    i = ImageSequence.Iterator(tif)
    next(i)
```

It seems that `ImageSequence.Iterator` does not define an `__iter__()` method, which means that it is a sequence type but not an iterator type. In my opinion, this is misleading and I suggest that a proper `__iter__()` method should be added to the class definition.

Thanks.

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #1648

### CODE REVIEW

**Comment by u55** [comment]
Hmm.  I'm not sure that you should remove the `__getitem__()` method, since this could break a lot of user's code if they were depending on being able to index the `ImageSequence.Iterator` object, as was recommended in the docstring:
```python
"""
    You can use the ``[]`` operator to access elements by index. This operator
    will raise an :py:exc:`IndexError` if you try to access a nonexistent
    frame.
"""
```

However, it probably is not common for a python type to be both indexable and iterable. It is not exactly clear how it should behave in this circumstance, to maintain backwards compatibility.  What should happen after indexing, should the current position be updated or not?  In other words, if you leave in the `__getitem__()` method, should the following commented line be included?:

```python
...
    def __getitem__(self, ix):
        try:
            if ix:
                self.im.seek(ix)
                self.position = ix + 1  # Should the current position be updated here?
            return self.im
        except EOFError:
            raise IndexError
```

**Comment by u55** [comment]
Or, if the `__getitem__()` method is to be removed, maybe it should be deprecated for a release cycle first?

**Comment by radarhere** [comment]
Thanks for finding that. It wasn't my intention to remove any existing behaviour. I've now restored the method, and added tests to prevent this from occurring again.

I don't think that the `position` variable does need to be updated at that point - seeking to a different position within an object while iterating over it sounds like a recipe for confusion. If anything, I would suggest throwing an error in that scenario.

**Comment by u55** [comment]
Yeah, I agree. If indexing the object had the side effect of updating the current position of the iterator, then it could "restart" an iteration that had already ended, which is considered to be unpythonic.  I found this from the python docs [https://docs.python.org/3.5/library/stdtypes.html#typeiter]:
```
Once an iterator’s __next__() method raises StopIteration,
it must continue to do so on subsequent calls. 
Implementations that do not obey this property are deemed broken.
```

**Pull request merged**
