### PR TITLE
Correct convert matrix docs

### PR DESCRIPTION
**Pull request by wiredfool**
* Fixes documentation complaint in http://engineering.khanacademy.org/posts/making-thumbnails-fast.htm from @wchargin that has made it from PIL through all of the releases of Pillow. 

* Fixes formatting of convert_matrix in _imaging.c so that the indentation actually matches the code flow.

### CODE REVIEW

**Comment by WChargin** [comment]
haha, thanks a bunch! :)

**Comment by wiredfool** [comment]
Glad to help. 

I'm thinking that some of the code from transforms.py (https://gist.github.com/WChargin/d8eb0cbafc4d4479d004) might be useful as an example elsewhere in the docs to better explain the matrix option.  Do you have any objections?

**Comment by WChargin** [comment]
None at all—go for it!

**Comment by WChargin** [comment]
On reflection, I definitely should have pinged you or just fixed this myself before publishing that post. Sorry for blindsiding you. I just didn't think of it.

Thank you for being so responsive!

**Comment by wiredfool** [comment]
No worries. It's easy enough to fix once you know where to look. I wasn't even clear if app-engine uses pillow or PIL, but it kind of looks like it's still PIL.

**Pull request merged**
