### PR TITLE
Restored 32-bit support

### PR DESCRIPTION
**Pull request by radarhere**
This reverts the parts of #7228 that are not related to the CI jobs.

I've updated the release notes to remove the notice that 32-bit architecture is no longer supported.

To test, I've restored 32-bit Debian 12.

### CODE REVIEW

**Comment by nulano** [comment]
I would also revert the AppVeyor CI for a representative Windows job: https://github.com/python-pillow/Pillow/pull/7228/files#diff-e1ab4c3cec24f841948eb867754d4ad0b9b6d11eaa6b5bfbe0357aceb0a49eff

**Comment by hugovk** [comment]
Thank you!

**Comment by mara004** [comment]
Thanks! I think it's good to maintain as much compatibility as possible.

**Comment by Dragonius** [comment]
Thank you.

**Pull request merged**
