### PR TITLE
Add support for ATI1/2(BC4/BC5) DDS files

### PR DESCRIPTION
**Pull request by REDxEYE**
This commit adds support for loading DDS with ATI1 and ATI2 fourcc pixel format

Changes proposed in this pull request:

 * Add support for ATI1 dds files
 * Add support for ATI2 dds files

### CODE REVIEW

**Comment by REDxEYE** [comment]
I haven't found the ATI1 texture yet, I will add a test for ATI1 when I find texture

Test texture is taken from Zombie Army 4

**Comment by REDxEYE** [comment]
Quick question, how should I go about DDS cube maps? Does pillow support layers or something like it?
If not, should I flatten multi-side/layer textures into one line?

**Comment by radarhere** [comment]
> Quick question, how should I go about DDS cube maps? Does pillow support layers or something like it? If not, should I flatten multi-side/layer textures into one line?

Pillow has a concept of 'frames'. While used for the different images for in an animated GIF, they are also used for the different layers in a PSD. You might want to look at https://github.com/python-pillow/Pillow/blob/main/src/PIL/PsdImagePlugin.py

**Comment by radarhere** [comment]
> Test texture is taken from Zombie Army 4

Is that something that can be distributed under Pillow's license as part of our test suite?

**Comment by REDxEYE** [comment]
> > Test texture is taken from Zombie Army 4
> 
> Is that something that can be distributed under Pillow's license as part of our test suite?

I'll replace them with selfmade textures in next commit

**Comment by REDxEYE** [comment]
@radarhere Do you have any estimations of when this PR will be merged? I have other PR in progress that needs changes from this one

**Review by radarhere — APPROVED** [review]

**Comment by radarhere** [comment]
All looks good. My only suggestion is to rearrange the order of the formats - https://github.com/REDxEYE/Pillow/pull/1/files

I think this can be merged after that.

**Comment by REDxEYE** [comment]
> All looks good. My only suggestion is to rearrange the order of the formats - https://github.com/REDxEYE/Pillow/pull/1/files
> 
> I think this can be merged after that.

Good idea, I forgot to sort them. I'm also working on a full rewrite of DDS plugin, using proper enums and flags with support for more pixel formats, but i'm stuck at floating point formats, is there any plans on adding RGBAF32 format or something?

**Comment by radarhere** [comment]
Sounds like you're talking about #1888

**Comment by hugovk** [comment]
Let's also add this to the release notes. Thanks!

https://pillow.readthedocs.io/en/latest/releasenotes/9.3.0.html

**Comment by radarhere** [comment]
Ok, I've created #6465 to add to the release notes.

**Pull request merged**
