### PR TITLE
Update tiff and tk tcl 8.5 versions

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by radarhere** [comment]
Note that this conflicts with #1298

**Comment by hugovk** [comment]
Thanks, I've updated that PR.

**Comment by wiredfool** [comment]
This didn't actually work, as none of the tcl/tks were recognized in the pillow build https://ci.appveyor.com/project/Pythonpillow/pillow/build/2.9.pre.43/job/rhtd5q2i5gr7hq96#L849

vs:

https://ci.appveyor.com/project/Pythonpillow/pillow/build/2.9.pre.42/job/hbpd30gef96gqy22#L917

**Comment by wiredfool** [comment]
https://github.com/python-pillow/Pillow/blob/master/winbuild/build_dep.py#L97  

hardwired versioning...

**Comment by radarhere** [comment]
They're from the master downloads - http://www.tcl.tk/software/tcltk/download.html

**Comment by radarhere** [comment]
Ah, apologies for missing the skipped portion of the ci build. Thanks for fixing up the hardwired versions.

**Pull request merged**
