### PR TITLE
Add Mergify config

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/python-pillow/Pillow/issues/4900.

Changes proposed in this pull request:

 * Approval, label and Travis CI rules like in Like https://github.com/python-pillow/docker-images/pull/84 and https://github.com/python-pillow/pillow-wheels/pull/161
 * AppVeyor rule is similar
 * GHA: https://doc.mergify.io/conditions.html#github-actions

> GitHub Actions works slightly differently. To match a status check when using GitHub Action, only the job name is used.
> 
> image
>
> In the example above, it would be `A job to say hello`:
>
```yml
conditions:
  - status-success=A job to say hello
```

So it's a bit more maintenance for GHA. We could rename the jobs so they don't include Python versions etc., but it's useful to see which one fails at a glance. Let's see how it goes and iterate if necessary.

### CODE REVIEW

**Comment by nulano** [comment]
It might be possible to use [dependant jobs in GHA](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#creating-dependent-jobs) to simplify this config a bit. Each workflow set (`test.yml`, `test-docker.yml`, `test-windows.yml`) can have another dummy job added that depends on the success of the rest of the set named something like `Test Windows / All Successful` which could allow this config to be just three GHA lines.

I'm not sure whether there is anything else that could be shown in these dummy jobs such as perhaps a warnings summary, but it might be worth adding just to simplify this config. OTOH the set of jobs doesn't change often, so this might be fine as is.

**Comment by hugovk** [comment]
Interesting idea! 

Would they still need enumerating, something like this?

```yml
jobs:
  build:
    ...
  success:
    needs: [
      MSYS2 MinGW 32-bit,
      MSYS2 MinGW 64-bit,
      Python 3.6 x64,
      Python 3.6 x86,
      Python 3.7 x64,
      Python 3.7 x86,
      Python 3.8 x64,
      Python 3.8 x86,
      Python 3.9-dev x64,
      Python 3.9-dev x86,
      Python pypy3 x86,
    ]

```

Or would it be possible to use a matrix?

**Comment by nulano** [comment]
It only needs to list `build`:
```yml
jobs:
  build:
    ...
  success:
    needs: build
    ...
```
Take a look at an example I made: [test.yml](https://github.com/nulano/Pillow/actions/runs/268268455/workflow#L112), [test-windows.yml](https://github.com/nulano/Pillow/actions/runs/268268456/workflow#L272)

**Comment by hugovk** [comment]
That looks good. Please could you make a test PR against my fork? I've put this config there:

https://github.com/hugovk/Pillow/commit/5b6c6fc6337a34f985711573719fa3f41a486c49

**Comment by hugovk** [comment]
The tests worked (https://github.com/hugovk/Pillow/pull/60, https://github.com/hugovk/Pillow/pull/61), updated!

**Pull request merged**
