### PR TITLE
Run Tidelift Align on Pipfile changes

### PR DESCRIPTION
**Pull request by radarhere**
Updated Pipfile to Python 3.10

### CODE REVIEW

**Comment by hugovk** [comment]
Does the lockfile need updating?

**Comment by hugovk** [comment]
And because these files are only used by https://github.com/python-pillow/Pillow/blob/main/.github/workflows/tidelift.yml should we edit that to also run when these files change?

**Comment by radarhere** [comment]
Good call, done.

**Comment by aclark4life** [comment]
```
Error: No API key found. Please authenticate with the Tidelift API as described at https://ptm.tl/docs-apikeys.
```
Hmmm

**Comment by radarhere** [comment]
I'm going to abandon my original idea of updating, and instead just keep @hugovk's idea of running Tidelift Align for Pipfile changes.

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/6233 is the same as this but from a branch in this repo, instead of from a personal fork.

This one failed because it can't find the API key, likely a GitHub security precaution to prevents forks accessing secrets.

**Pull request closed without merging**
