### PR TITLE
Wiredfool setup cleanup

### PR DESCRIPTION
**Pull request by aclark4life**
OK what did I do here; you sent a PR from your fork and somehow I created a new branch …

### CODE REVIEW

**Comment by wiredfool** [comment]
I'm not really sure. You've also created 5 pending checks, which is 2 more than I'm used to.

**Comment by radarhere** [comment]
I've seen the five pending checks on a few other issues lately - not all, but a few. Just noting that it's not unique to this issue.

**Comment by wiredfool** [comment]
Cherry picked, closing

**Comment by hugovk** [comment]
> You've also created 5 pending checks, which is 2 more than I'm used to.

I reckon because it's the branch is from the Pillow repo, so it does a build for both the push and the PR (for Travis and AppVeyor). 

If the branch is from a personal repo, you still get the push builds, but only the PR builds show up here.

**Pull request closed without merging**
