### PR TITLE
Add pillow logo

### PR DESCRIPTION
**Pull request by seriousadi**
old pillow logo was not working so i added pillow logo from official pillow site

Fixes #
The pillow logo wasn't working in readme.md 

Changes proposed in this pull request:
- replaced the broken link to new working one from python-pillow.org

### CODE REVIEW

**Comment by radarhere** [comment]
You say that it wasn't working, and that it was a broken link.

However, https://raw.githubusercontent.com/python-pillow/pillow-logo/main/pillow-logo-248x250.png works for me if I navigate to it directly.

pillow-logo-248x250

If I look at the README, I see
readme

Are you seeing something different? Or were you thinking that the word 'Pillow' should be part of the logo, as you'd made it in this PR?

**Comment by seriousadi** [comment]
It wasn't working on my laptop i even tried to go i that link but it wasn't working i tried it in my other devices too but it wasn't working then i thought i should add if the existing one isn't working so i added it from your pillow site but now it is working fine as if nothing happened anyways adding pillow to side actually  looks better but not with that pick it looks a bit squished.

**Comment by hugovk** [comment]
Here's how it currently looks fore on mobile:

Screenshot_20230319_135644_Chrome

And with this PR:

Screenshot_20230319_135701_Chrome

**Comment by seriousadi** [comment]
So if i edit that photo to look good on computers and mobile too will it work, is that ok

**Comment by hugovk** [comment]
Please can you share a screenshot or explain how the existing one "wasn't working"?

**Comment by hugovk** [comment]
It sounds like a temporary network issue causing it to fail to load the image. Thanks for the PR, but I don't think we need to replace the image for this.

**Comment by seriousadi** [comment]
thanks no problem its ok

**Pull request closed without merging**
