### PR TITLE
Show warning when trying to save RGBA image as JPEG

### PR DESCRIPTION
**Pull request by homm**
Fixes https://github.com/python-pillow/Pillow/issues/2005

### CODE REVIEW

**Comment by wiredfool** [comment]
The problem here is that it's liable to break thumbnailing scripts that read PNGs, and this behavior dates from the PIL fork. (so it's well established).  We'd be replacing something that does questionable things to the alpha channel with an exception.

**Comment by homm** [comment]
PNG have [16 base color formats](http://www.schaik.com/pngsuite/pngsuite_bas_png.html). 6 of them fails PNG → JPEG conversation on master:

```python
from PIL import Image
for fn in glob('../i/basn*.png'):
    try:
        Image.open(fn).save(fn + '.jpg')
    except IOError:
        print '>>>', fn
```

They are:
```
>>> ../i/basn0g16.png
>>> ../i/basn3p01.png
>>> ../i/basn3p02.png
>>> ../i/basn3p04.png
>>> ../i/basn3p08.png
>>> ../i/basn4a08.png
```

We can leave the alpha channel discarding for now, but I afraid this means that we leave it forever.

**Comment by wiredfool** [comment]
We can make it a specific deprecation warning, and anyone who wants to can register that as an exception. Then we can switch it over in 2-4 releases. (probably after stretch freezes, or April '17)

**Comment by homm** [comment]
Ok, I'll add warning then.

Sorry, what is stretch freezes?

**Comment by wiredfool** [comment]
Debian Stretch, the next stable release. I'm leaning to include a deprecation warning in one iteration of Debian stable before making a hard error.

**Comment by homm** [comment]
Ok, caught your point.

**Comment by homm** [comment]
Turned the error to the warning.

**Comment by wiredfool** [comment]
This should probably get a release note as a future deprecation warning.

**Pull request merged**
