### PR TITLE
Tiff: allow writing floating point tag values

### PR DESCRIPTION
**Pull request by bpedersen2**
Use the inverse logic used for loading floating point tag
values to also write them out again.

### CODE REVIEW

**Comment by hugovk** [comment]
@bpedersen2 Please can you add tests so this new code is covered?

https://coveralls.io/builds/1976951/source?filename=PIL%2FTiffImagePlugin.py#L520

**Comment by wiredfool** [comment]
Noting that this likely interacts with #1059.

**Comment by aclark4life** [comment]
@bpedersen2 Any progress on this?

**Comment by karimbahgat** [comment]
This is great! I was just about to add a new issue on exactly the same. I had inserted my own custom code in TiffImagePlugin.py similar to @bpedersen2 but I like his code better. 

Especially since it looks like the Travis CI tests passed I really hope there is nothing left in the way for this pull request to be merged. As evidenced by #660 and [this post](http://gis.stackexchange.com/questions/16839/why-does-a-tif-file-lose-projection-information-when-a-pixel-value-is-changed) I think there is considerable interest from GIS developers in using Pillow to save GeoTIFFs (or at least there could and should be). This issue of float/double tags is really the last remaining obstacle to having fully blown support for working with GeoTIFF images in Pillow, since virtually all of the important GIS-specific tags (coordinate transform and projection definitions) in the [GeoTIFF specification](http://www.remotesensing.org/geotiff/spec/geotiff2.6.html#2.6) require decimal numbers of type double. 

I have a [GIS developers book](https://www.packtpub.com/application-development/python-geospatial-development-essentials) coming out soon where I patch Pillow to support Python floats and then use it to save GeoTIFFs, so it would be especially great if this feature was already in the main branch so I can drop the part about patching. This could be a great encouragement to GIS developers and users to know that Pillow has at least basic out-of-the-box support for GeoTIFF. 

If there is anything I could do to speed the process I would gladly do so.

**Comment by hugovk** [comment]
Looks good to me, merging.

@karimbahgat Do you think it'd be useful to add any more tests for GIS-specific tags?

**Comment by karimbahgat** [comment]
That was fast, thanks! 

Regarding the GIS tag tests, I don't think there would be a point. The GIS specific tags are just like any other tag, and since @bpedersen2 added successfull tests of saving floats and doubles to some generic tags, those tests apply equally much to any GIS-specific tags or any other specialized-tag for that matter. Or maybe I misunderstood?

I can testify that I was able to successfully save and reload a GeoTIFF of the world with the new Pillow code after your merge. The commonly used GIS-specific "nodata" tag was also successfully saved and reloaded as ascii type. I think all of the GIS-tags only use short, double, or ascii types so they should all be supported. There is however one tag that contains a nodata image mask of sorts but I haven't looked into which data type it uses. For another time I think :P

**Comment by hugovk** [comment]
You understood :)

**Pull request merged**
