### PR TITLE
Explicitly type Image __init__ attributes

### PR DESCRIPTION
**Pull request by Yay295**

### CODE REVIEW

**Comment by Yay295** [comment]
Unfortunately, trying to type `im` and `palette` leads to a lot of false errors because mypy can't always determine that those values aren't `None`.

Related:
https://github.com/python/mypy/issues/10151
https://github.com/python/mypy/issues/11969

**Comment by radarhere** [comment]
I've created #8279 as an alternative to this, addressing `im` and `palette` as well.

**Comment by Yay295** [comment]
Other than thee `im` and `palette` changes, the only differences I see are a slightly different handling of `PngImagePlugin`, and a very different handling of `EpsImagePlugin`.

**Comment by radarhere** [comment]
I think my versions of the EPS and PNG changes are simpler. I've also restricted the hinting of `self.info` keys more than this PR.

**Comment by Yay295** [comment]
I'm not sure how you think your PNG change are simpler when you introduce a new local variable and I don't.

**Comment by radarhere** [comment]
My opinion is that it's simpler because my version declares what the type is once, whereas this does it three times.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/pull/8279 has been merged instead.

**Pull request closed without merging**
