### PR TITLE
Added copy method font_variant() and accessible properties to truetype()

### PR DESCRIPTION
**Pull request by radarhere**
This is from the suggestion in issue #589

The original poster seemed to think it would be a complex change. I can't see why, so let me know if I have missed something.

### CODE REVIEW

**Comment by wiredfool** [comment]
+1, I'm ok with this once there's documentation for the new method.

**Comment by radarhere** [comment]
Is this what you were after? As far as I can see, there isn't documentation for FreeTypeFont methods in docs/reference/ImageFont.rst

**Comment by hugovk** [comment]
Thanks.

**Comment by hugovk** [comment]
Strange, the CI failed after merging with:

`TabError: inconsistent use of tabs and spaces in indentation`
https://travis-ci.org/python-pillow/Pillow/builds/55271699

The PR didn't pick it up because of the [CI skip], and I wouldn't have expected it to fail either. In general, I suppose if source code is edited at all, it's better to avoid CI skip! :)

Fixup PR: #1143.

**Comment by jvanasco** [comment]
Wow. Thanks!   I was just unfamiliar with the Pillow/PIL codebase and didn't know what was going on.

**Pull request merged**
