### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### python-pillow/Pillow now has a Chat Room on Gitter

@aclark4life has just created a chat room. You can visit it here: [https://gitter.im/python-pillow/Pillow](https://gitter.im/python-pillow/Pillow?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/python-pillow/Pillow?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by aclark4life** [comment]
Thanks @gitter-badger for saving me the trouble of creating an issue to announce the creation of this room:

- https://gitter.im/python-pillow/Pillow?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link

Pillow IRC never took off, but maybe this will.

**Comment by hugovk** [comment]
Let's stick it somewhere in the badge table.

**Comment by wiredfool** [comment]
Is anyone actually using glitter?

**Comment by aclark4life** [comment]
@wiredfool How would they know to use it if you didn't hang the sign up? (No idea, haven't logged in since I created it…)

**Comment by aclark4life** [comment]
@wiredfool I mean, I would add it just to add it. Leave it up for a while, then if it's truly useless, remove it in a year or so. (I.e. rather than questioning it's potential for usefulness before trying it.)

I should also mention that overall, I'm looking for more ways to engage folks in "real time" discussion, and I just happened to come across Gitter.

**Comment by hugovk** [comment]
Let's add it (but move it to the badge table). 

I've used Gitter on other projects. It will send emails to summarise activity if you've not been there for a while (and you can unsubscribe).

**Pull request closed without merging**
