### PR TITLE
prevent div by zero for exif rationals with zero denominator

### PR DESCRIPTION
**Pull request by kraiz**
Found this ZeroDivisionError with one of the photos from my old mobile. It's happening when reading the EXIF tags. Seems like a value of DigitalZoomRatio is (0,0) which then will result in 0 / 0.

I'm not quiet sure if my patch is valid. It should just emulate an div by almost zero when the denominator (b) is exactly zero (evaluates to False and therefore fallback to the system's minimum float value).

I scaled down the image keeping the exif tags intact and put it into a testcase.

### CODE REVIEW

**Comment by hugovk** [comment]
I've not checked but I think this a/b might be a new thing that used to be (a, b). 

Even if not, and this might be an API change, it may be more sensible to return (a, b) then a/b for this ratio.

Especially as these docs say the numerator has a special meaning when zero, so we shouldn't really be obfuscating it by combining it:

> Indicates the digital zoom ratio when the image
was shot. 

> If the numerator of the recorded value is 0, this
indicates that digital zoom was not used.

http://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/digitalzoomratio.html

**Comment by kraiz** [comment]
The result type in the current implementation depends on the ``legacy_api`` flag. If it's ``True``, then the result is tuple (``(a,b)``) else (assuming kind of newstyle/current api) the ratio is calculated and the result type is float (``a/b``). So old-style/legacy api returns numerator and denominator. New-style/current api get me combined value as float. My patch does not change this .

Did i get you right to return different types dependiing on the value? I would find this rather irritating, to get a (0,x) tuple in case of disabled/not used digital zoom when otherwise getting floats. Maybe ``None`` would be a good value?

**Comment by wiredfool** [comment]
Changing the return type depending on the value is a bad solution, unless it's an exception or NaN type.

**Comment by hugovk** [comment]
I'm suggesting always returning `(a, b)` and never returning `a/b`, regardless of the value. 

Then the end user can divide them if they want, they can check if the numerator is zero and whether digital zoom was not used.

---

When I open the test image in Irfanview, it gives two values:

`DigitalZoomRatio - 0.00/0.00 x`

Exiftool gives:

`Digital Zoom Ratio              : undef`

Photoshop gives:

`exif:DigitalZoomRatio: 0/0`

**Comment by wiredfool** [comment]
I wonder if we could return a FunkyObject(tm) that's a chimera between a fractions.Fraction and something that will return Nan or undefined or None if it's a 0/0. 

Returning a tuple should be the last resort, but if we do make that change, we'll need to do that for 3.0.1.

**Comment by hugovk** [comment]
I checked a couple of photos from different cameras. In Irfanview the values are:

DigitalZoomRatio - 0.00 x
DigitalZoomRatio - 1.00 x

**Comment by hugovk** [comment]
I checked a couple of photos from different cameras. In Irfanview the values are:
`DigitalZoomRatio - 0.00 x`
`DigitalZoomRatio - 1.00 x`

In Photoshop:
`exif:DigitalZoomRatio: 0/100`
`exif:DigitalZoomRatio: 100/100`

Exiftool:
`Digital Zoom Ratio              : 0`
`Digital Zoom Ratio              : 1`

That first one has numerator 0, so that should also not be lost.

**Comment by wiredfool** [comment]
Yeah, so what we have is clearly a field that has a numeric value as well as a different meaning when the value doesn't make strict numeric sense. 

Could we subclass fraction.Fraction or number.Rational and do something smart in the 0 case?

**Comment by hobarrera** [comment]
I'm getting this issue on Debian 8.2, but not on ArchLinux, with the exact same virtualenv on both, and the same image file.

Is it possible that some OS-level dependency is making a difference?

**Comment by wiredfool** [comment]
@hobarrera That would be pretty odd. There shouldn't be any dependency on libraries in this code path. It's pretty clearly a bug in the expectations of the TiffImageDirectory as it relates to data correctness.

**Comment by hobarrera** [comment]
My bad, sorry, looks like my Arch machine had v2.9.0 for some reason. Sorry about the noise.

**Comment by thanhson1085** [comment]
+1

**Comment by ymyzk** [comment]
:+1:

**Comment by JanMalte** [comment]
What is the state of this PR? What is needed to get this merged and releases into a bugfix release?

**Comment by wiredfool** [comment]
@JanMalte I've got an alternate implementation that retains more of the semantics of what 0/0 does, but I don't see the link here or in the other thread. 

I've just added a PR for it, see #1531. Please try it and report back as to if it works for you.

**Comment by radarhere** [comment]
If #1531 has been merged, then this can be closed, yes?

**Comment by wiredfool** [comment]
For everyone who's interested in the exif handling in Pillow, Please test the new 3.1.0-rc1 release soon and give feedback.

**Comment by kraiz** [comment]
Passes my initial testcase. Thanks!

**Comment by okrutny** [comment]
Version 3.1.0 works like a charm and fixes mariocesar/sorl-thumbnail#429

**Pull request closed without merging**
