### PR TITLE
fix bug in TiffImagePlugin. Save and restore pointer to super.load in…

### PR DESCRIPTION
**Pull request by Geka000**
There is a bug in TiffImagePlugin.py. If tiff file has two frames, first with tiff_ccitt compression, and second in packbits compression. _setup method replace self.load with self._load_libtiff if frame has tiff_ccitt, and when you try to load frame with other compression self.load still points to self._load_libtiff, but it need to point to super.load

### CODE REVIEW

**Comment by radarhere** [comment]
Hi. Thanks for creating this PR, and joining the community effort to support Pillow. In order to try and avoid regressions in the code at a later point in time, tests are encouraged. Would you be able to add a test to check that this behaves correctly?

**Comment by Geka000** [comment]
Hello. I have added a test. it's failes on master branch, and it's works on my PR

**Comment by wiredfool** [comment]
This is a valid problem, but I think the approach should be different. Rather than patching over a questionable design decision, we should fix the underlying issue.

**Comment by radarhere** [comment]
I've created PR #1782 as an alternative fix, cherry-picking the test-related commit from this.

**Comment by wiredfool** [comment]
Merged #1782

**Pull request closed without merging**
