### PR TITLE
Update licence to MIT-CMU

### PR DESCRIPTION
**Pull request by hugovk**
Closes https://github.com/python-pillow/Pillow/issues/7942.

Pending https://github.com/pypa/trove-classifiers/pull/189.

### CODE REVIEW

**Comment by hugovk** [comment]
> Pending [pypa/trove-classifiers#189](https://github.com/pypa/trove-classifiers/pull/189).

Merged and released in https://github.com/pypa/trove-classifiers/releases/tag/2024.10.11 🚀

**Review by radarhere — APPROVED** [review]

**Comment by hugovk** [comment]
> Moving to draft pending a rename in [pypa/trove-classifiers#190](https://github.com/pypa/trove-classifiers/pull/190).

Merged and released in https://github.com/pypa/trove-classifiers/releases/tag/2024.10.12 🚀🚀

**Comment by sunpoet** [comment]
Is it planned to update LICENSE file to reflect this change?

**Comment by hugovk** [comment]
Yes, it was already done in https://github.com/python-pillow/Pillow/pull/8490, but only after the 11.0 release.

**Comment by sunpoet** [comment]
Thanks. I only checked the release tarball but not the repository.

**Pull request merged**
