### PR TITLE
Add complex text support

### LINKED ISSUE #1089: Bug in rendering Indic fonts
ImageFont, ImageDraw do not render complex scripts with ligatures correctly. (On Ubuntu 14.04, Python 3.4.0)

This is how it looks in editor gedit:
gedit
This is how Pillow does it.
pillow

```python
#!/usr/bin/env python3
#-*- coding:utf8 -*-

from PIL import Image, ImageFont, ImageDraw

im = Image.new("RGB",(160, 160))
draw = ImageDraw.Draw(im)

font_telugu = ImageFont.truetype("/usr/share/fonts/truetype/ttf-indic-fonts-core/Pothana2000.ttf",50)
text_telugu = "నిత్య"

font_hindi = ImageFont.truetype("/usr/share/fonts/truetype/ttf-indic-fonts-core/gargi.ttf",50)
text_hindi = "नित्य"

draw.text((10, 10), text_telugu, font=font_telugu)
draw.text((10, 90), text_hindi, font=font_hindi)

im.show()
```

### PR DESCRIPTION
**Pull request by ShamsaHamed**
This pull request adds support for languages that require complex text layout.

We are using the Raqm library, that wraps FriBidi (for bidirectional
text support) and HarfBuzz (for text shaping), and does proper BiDi and script
itemization:
https://github.com/HOST-Oman/libraqm

This should fix #1089.

### CODE REVIEW

**Comment by wiredfool** [comment]
Thanks for the contribution.  This is something that have been requested several times. 

From a quick look at this I've got several concerns:
* This changes the test platform from precise to trusty. While that may be a reasonable change, it's something that should be considered separately.
* This ties **all** of the font rendering to three new dependencies, at least one of which is listed as an early prototype and is not available as a binary on any of our supported platforms other than through a PPA. Specifically, that means that this is going to break font rendering (and testing) on windows and older linuxes unless there is a build process for them. 
* We've got to have automated tests for this that are well specified. I don't believe that any of the core developers could look at the output from this and tell if it's correct or incorrect. So the level of testing needs to be somewhat more complete and fool proof than our usual tests. 
* Documentation on the changes to the api needs to be added.

**Comment by wiredfool** [comment]
Also, please don't rebase PRs when we're reviewing them.

**Comment by khaledhosny** [comment]
Raqm depends on HarfBuzz, which is not packaged for Precise. For the other point, would providing fallback code for when Raqm is missing (that does essentially what the old code is doing) an acceptable compromise?

**Comment by wiredfool** [comment]
I think I'd want fallback code to be comfortable merging this. I'd also want to update the scripts in the `depends` directory for those platforms where there aren't packages, and the  `winbuild` directory for testing on windows. I couldn't tell if libraqm builds on windows or not, but it does appear that at least harfbuzz is available.

**Comment by ShamsaHamed** [comment]
I am working on fallback code in case that Raqm is missing, so it will use the old code.
I will also work on the tests and documentation fixing.

**Comment by ShamsaHamed** [comment]
This provide the documentation, testing and fallback code.

**Comment by hugovk** [comment]
Travis CI didn't build. I checked [.travis.yml](https://github.com/ShamsaHamed/Pillow/blob/CTL/.travis.yml) on https://lint.travis-ci.org/ and it said:

> your repository must be feature flagged for the **dist** setting to be used

**Comment by ShamsaHamed** [comment]
The failure is due to merge conflict, so I will rebase this after you finish reviewing the code.

**Comment by wiredfool** [comment]
Go ahead and fix the merge conflicts so we can get good test runs on this.

**Comment by ShamsaHamed** [comment]
I have a problem in testing file I have added. I run it locally and it is ok, but I can't find why it fails during travis-ci buliding. Even I can't reproduce the issue locally.
So anyone can debug the code and see if the issue is reproduced?
I have python 2.7 and 3.4.

**Comment by andreymal** [comment]
Any progress with this?

@ShamsaHamed can you upgrade this to Pillow 3.4.2? Then I will try to find and fix problems with the tests, if possible (this feature is needed for me :)

**Comment by wiredfool** [comment]
Closed, merged with #2576

Thanks to everyone who worked on this, I think it's a valuable addition to the library.

**Comment by ShamsaHamed** [comment]
Thanks to you for your efforts and sorry for my absence to complete the work. I have a problem with my device.

**Pull request closed without merging**
