### PR TITLE
Raise an EOFError when seeking too far in PNG

### LINKED ISSUE #4518: AttributeError: 'NoneType' object has no attribute 'read'
### What did you do?

Following on from #4509 after the 7.1.0 release, we have a new issue that cropped up opening a png from scikit-image.

### What did you expect to happen?

Not error.

### What actually happened?

It errored.

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.8.2
* Pillow: 7.1.0

The code should just be loading a scikit-image PNG data:

```python
from skimage import data
original = data.camera().astype('float')
```
The error message is:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/data/__init__.py", line 109, in camera
    return _load("camera.png")
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/data/__init__.py", line 96, in _load
    return imread(_os.path.join(data_dir, f), plugin='pil', as_gray=as_gray)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/io/_plugins/pil_plugin.py", line 36, in imread
    return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/skimage/io/_plugins/pil_plugin.py", line 66, in pil_to_ndarray
    image.seek(i)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 748, in seek
    self._seek(f)
  File "/opt/miniconda/envs/sunpy/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 791, in _seek
    cid, pos, length = self.png.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

Since this is scikit image loading one of their PNGs, I wonder if it's actually a bug there.

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #4518

Looking at PngImagePlugin, there's no need for `n_frames` or `is_animated` to use property decorators - they can just be regular properties.

You might think this is just a simplification of the code, and that it would have no effect on behaviour. This is not the case - the common [`_seek_check` method](https://github.com/python-pillow/Pillow/blob/8c9100e267f40a63081b344220abaa57325a3d6d/src/PIL/ImageFile.py#L294-L306) changes behaviour. If `_n_frames` is present, and `None`, then it doesn't check the upper limit on the frame number, because that would potentially require seeking all the way to the end of the file. Now that there is no `_n_frames`, it checks the upper limit, and throws an `EOFError`.

I've added a test to ensure that an EOFError is thrown moving forward.

Testing, I find that this resolves the issue. This is also noted in https://github.com/python-pillow/Pillow/issues/4518#issuecomment-608360106.

### CODE REVIEW

**Comment by hugovk** [comment]
@pmrowla Please could you have a look at this PR? Thank you!

**Comment by pmrowla** [comment]
This has the same effect as what I suggested in #4519, and it's simpler. Testing w/scikit-image also shows the the original downstream issue would be resolved.

**Comment by hugovk** [comment]
@radarhere Thoughts about the doccheck failure? I checked the branch out locally and cannot reproduce.

I'd restart it, but the restart button is now missing for me on this repo on Travis CI.

**Comment by radarhere** [comment]
It's not just this branch. It's appeared in others.

**Why now?**

The last master run - https://travis-ci.org/github/python-pillow/Pillow/jobs/671262347#L4634 - used Sphinx v2.4.4.

The issue would be that then, Sphinx v3 was released - https://github.com/sphinx-doc/sphinx/releases/tag/v3.0.0

And so then this PR uses Sphinx v3.0.0 - https://travis-ci.org/github/python-pillow/Pillow/jobs/671293213#L4559

**What is the error?**

https://travis-ci.org/github/python-pillow/Pillow/jobs/671293213#L4567-L4573

A series of warnings like

> WARNING: duplicate object description of PIL.PngImagePlugin.PngImageFile, other instance in reference/plugins, use :noindex: for one of them

Sphinx has realised that we are documenting PngImageFile twice. You can see this at https://pillow.readthedocs.io/en/latest/reference/plugins.html#module-PIL.PngImagePlugin - once at the start of the module, and once if you scroll down under ChunkStream.

I've pushed a commit removing the first one. See https://pillow-radarhere.readthedocs.io/en/png_seek/reference/plugins.html#module-PIL.PngImagePlugin for what this now looks like.

**Comment by hugovk** [comment]
And I had 2.4.1 locally. Thanks!

**Comment by hmaarrfk** [comment]
Kinda nudge toward a release since this issue seems to affecting one passionate user for a release

https://github.com/conda-forge/scikit-image-feedstock/pull/56

**Comment by hugovk** [comment]
Thanks for the nudge! We'll do a release this weekend, keep an eye on https://github.com/python-pillow/Pillow/issues/4354#issuecomment-618970390.

**Comment by radarhere** [comment]
Pillow 7.1.2 has now been released with this fix.

**Comment by hmaarrfk** [comment]
Thanks!

**Pull request merged**
