### PR TITLE
Don't use int for handle type

### PR DESCRIPTION
**Pull request by nu774**
Couldn't accept handle values greater than 0x7FFFFFFF, which wasn't enough even on 32bit system, and completely wrong for 64bit.

### CODE REVIEW

**Comment by radarhere** [comment]
Thanks for this! Would you be able to write a test for it at all?

**Comment by wiredfool** [comment]
We should do a review of anywhere we're passing pointers through the python layer for this sort of error.  It should be greppable from the tuple parsing arguments.

**Comment by wiredfool** [comment]
A couple of comments -- with the caveat that I can't actually build this on windows today. 

* There's a format character, `n`, which gives you a `Py_ssize_t`, which is the same size as a `Py_intptr`. We use it elsewhere (in the `_getattr_unsafe_ptrs` method of _imaging.c.)  It should ensure that it's the same size as a pointer on both 32 and 64 bit architectures. 
* Other places in the file use the HWND  and HDC pointer types from Windows.h. I'm not clear why these were ints, or they weren't converted earlier. I think that these pointer types are a better idea than the `PY_LONG_LONG`. They _should_ be the same size as a `Py_ssize_t`, so casts to and from should be safe.

**Comment by nu774** [comment]
Well, in pure C level, intptr_t is actually ideal and enough. However, using "n" format character is a no-no.
In Windows, both of ctypes.wintypes.HDC and ctypes.wintypes.HWND are synonym for ctypes.c_void_p, which holds **UNSIGNED** value.
```
>>> ctypes.wintypes.HDC(-1)
c_void_p(4294967295)
```
See ? 
However, format n is same as format i in that it only accepts value in **SIGNED** integer type range. Therefore, on 32bit system, format n can accept only upto 2147483647, which is not enough.

For this reason, only available option for us is to use format K, therefore we have to always use 64bit integer type to store it.

**Comment by nu774** [comment]
It turned out that some more fixes are required for 64bit, so updated the pull req.
I don't have a script for automated testing, but basically the following simple script should be enough to see if it's working:
``` python
import sys
from PIL import Image, ImageWin

def main(path):
    im = Image.open(path)
    ImageWin.ImageWindow(im).mainloop()

if __name__ == '__main__':
    main(sys.argv[1])
```

**Comment by radarhere** [comment]
Just a note to say that the only reason the tests are failing is #1436 and #1437. Rebasing this branch on master will resolve that issue.

**Comment by wiredfool** [comment]
Travis doesn't even test this, since it's windows only. And I'm not convinced we have any covering tests on windows, partly because they're passing on master without this, and partly because Appveyor doesn't tend to test anything that relies on a display.

**Comment by wiredfool** [comment]
@cgohlke Do you have any comments on this?

**Comment by wiredfool** [comment]
The test above isn't failing on my Windows machine on master. It's possible that I'm getting low pointers that would work anyway, but I'm not sure how to force the issue.

**Comment by cgohlke** [comment]
Here's how CPython's multiprocessing module passes pointers and handles (<https://github.com/python/cpython/blob/master/Modules/_multiprocessing/multiprocessing.h#L60>):
```C
#if SIZEOF_VOID_P == SIZEOF_LONG
#  define F_POINTER "k"
#  define T_POINTER T_ULONG
#elif defined(HAVE_LONG_LONG) && (SIZEOF_VOID_P == SIZEOF_LONG_LONG)
#  define F_POINTER "K"
#  define T_POINTER T_ULONGLONG
#else
#  error "can't find format code for unsigned integer of same size as void*"
#endif

#ifdef MS_WINDOWS
#  define F_HANDLE F_POINTER
#  define T_HANDLE T_POINTER
#  define F_SEM_HANDLE F_HANDLE
#  define T_SEM_HANDLE T_HANDLE
#  define F_DWORD "k"
#  define T_DWORD T_ULONG
#else
#  define F_HANDLE "i"
#  define T_HANDLE T_INT
#  define F_SEM_HANDLE F_POINTER
#  define T_SEM_HANDLE T_POINTER
#endif
```
On 32 bit they use `k` and `T_ULONG`, on 64 bit `K`  and `T_ULONGLONG`.

**Comment by nu774** [comment]
Update patch to use either "k" (for 32bit) or "K" (for 64bit).
Also, here is a non-gui script for test.
It seems like HDC takes quite often high pointer value.

``` python
import sys
import ctypes
import ctypes.wintypes
from PIL import Image, ImageWin
from io import BytesIO

class BITMAPFILEHEADER(ctypes.Structure):
    _pack_ = 2
    _fields_ = [
        ('bfType',          ctypes.wintypes.WORD),
        ('bfSize',          ctypes.wintypes.DWORD),
        ('bfReserved1',     ctypes.wintypes.WORD),
        ('bfReserved2',     ctypes.wintypes.WORD),
        ('bfOffBits',       ctypes.wintypes.DWORD),
    ]

class BITMAPINFOHEADER(ctypes.Structure):
    _pack_ = 2
    _fields_ = [
        ('biSize',          ctypes.wintypes.DWORD),
        ('biWidth',         ctypes.wintypes.LONG),
        ('biHeight',        ctypes.wintypes.LONG),
        ('biPlanes',        ctypes.wintypes.WORD),
        ('biBitCount',      ctypes.wintypes.WORD),
        ('biCompression',   ctypes.wintypes.DWORD),
        ('biSizeImage',     ctypes.wintypes.DWORD),
        ('biXPelsPerMeter', ctypes.wintypes.LONG),
        ('biYPelsPerMeter', ctypes.wintypes.LONG),
        ('biClrUsed',       ctypes.wintypes.DWORD),
        ('biClrImportant',  ctypes.wintypes.DWORD),
    ]

BI_RGB = 0
DIB_RGB_COLORS = 0

memcpy = ctypes.cdll.msvcrt.memcpy
memcpy.argtypes = [ ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t ]

CreateCompatibleDC = ctypes.windll.gdi32.CreateCompatibleDC
CreateCompatibleDC.argtypes = [ ctypes.wintypes.HDC ]
CreateCompatibleDC.restype = ctypes.wintypes.HDC

DeleteDC = ctypes.windll.gdi32.DeleteDC
DeleteDC.argtypes = [ ctypes.wintypes.HDC ]

SelectObject = ctypes.windll.gdi32.SelectObject
SelectObject.argtypes = [ ctypes.wintypes.HDC, ctypes.wintypes.HGDIOBJ ]
SelectObject.restype = ctypes.wintypes.HGDIOBJ

DeleteObject = ctypes.windll.gdi32.DeleteObject
DeleteObject.argtypes = [ ctypes.wintypes.HGDIOBJ ]

CreateDIBSection = ctypes.windll.gdi32.CreateDIBSection
CreateDIBSection.argtypes = [ ctypes.wintypes.HDC, ctypes.c_void_p, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p), ctypes.wintypes.HANDLE, ctypes.wintypes.DWORD ]
CreateDIBSection.restype = ctypes.wintypes.HBITMAP


def serialize_dib(bi, pixels):
    bf = BITMAPFILEHEADER()
    bf.bfType    = 0x4d42
    bf.bfOffBits = ctypes.sizeof(bf) + bi.biSize
    bf.bfSize    = bf.bfOffBits + bi.biSizeImage
    bf.bfReserved1 = bf.bfReserved2 = 0

    buf = (ctypes.c_byte * bf.bfSize)()
    bp = ctypes.addressof(buf)
    memcpy(bp, ctypes.byref(bf), ctypes.sizeof(bf))
    memcpy(bp + ctypes.sizeof(bf), ctypes.byref(bi), bi.biSize)
    memcpy(bp + bf.bfOffBits, pixels, bi.biSizeImage)
    return bytes(buf)

def test(ipath, opath):
    im = Image.open(ipath)
    imdib = ImageWin.Dib(im)

    hdr = BITMAPINFOHEADER()
    hdr.biSize = ctypes.sizeof(hdr)
    hdr.biWidth         = im.width
    hdr.biHeight        = im.height
    hdr.biPlanes        = 1
    hdr.biBitCount      = 32
    hdr.biCompression   = BI_RGB
    hdr.biSizeImage     = im.width * im.height * 4
    hdr.biClrUsed       = 0
    hdr.biClrImportant  = 0

    hdc = CreateCompatibleDC(None)
    print('hdc:',hex(hdc))
    pixels = ctypes.c_void_p()
    dib = CreateDIBSection(hdc, ctypes.byref(hdr), DIB_RGB_COLORS, ctypes.byref(pixels), None, 0)
    SelectObject(hdc, dib)

    imdib.expose(hdc)
    bitmap = serialize_dib(hdr, pixels)
    DeleteObject(dib)
    DeleteDC(hdc)

    Image.open(BytesIO(bitmap)).save(opath)

if __name__ == '__main__':
    test(sys.argv[1], sys.argv[2])
```

**Comment by wiredfool** [comment]
I've adapted the latest test script for our automated testing in my pr1431 branch: https://github.com/wiredfool/Pillow/tree/pr1431

It's passing tests OMM on python 3.4, both 32 and 64bit, but it's failing at the last line on the 2.7 series, where the bmp that's coming back is not recognized. I'm not sure if it's a bug in the test or in the patch.  @nu774 Ideas?

**Comment by nu774** [comment]
Please change the last line of <tt>serialize_dib()</tt> from <tt>return bytes(buf)</tt> to <tt>return bytearray(buf)</tt>.
On Python2.7. <tt>bytes</tt> is just a synonym for <tt>str</tt>, and it doesn't work as intended.

**Comment by wiredfool** [comment]
Ok, that looks like it did it. Thanks for your help.

**Pull request closed without merging**
