### PR TITLE
Release Python GIL when converting images using matrix operations

### LINKED ISSUE #6520: Releasing the GIL during matrix image conversion
I'm wondering how you would prefer to deal with small PRs that release the GIL.

I understand that those can cause a lot of churn due to unintended consequences when considering resource utilization.

### What did you do?

I opened a PR without raising a dedicated issue first.
https://github.com/python-pillow/Pillow/pull/6418

### What did you expect to happen?

Given I had done some research on the history of releasing the GIL during computation, I figured that it was OK to open the pull request first.
I was hoping for some comments or feedback, but I understand that different projects have different expectations on the order that things should happen.

### What are your OS, Python and Pillow versions?

* OS:  Linux / Windows / OSX (All really!)
* Python:  3.9
* Pillow: 9.2.0

Code like this, will not be able to run in parallel on different threads.

```python
import numpy as np
import PIL

image = np.zeros((1024, 1024, 3), dtype='uint8')
img = PIL.Image.fromarray(image)
matrix = (1, 2, 3, 4, 5, 6, 7, 8, 9)
final_image = np.asarray(
    img.convert(mode='RGB', matrix=matrix)
)
```

### PR DESCRIPTION
**Pull request by hmaarrfk**
Resolves #6520

Related to 
* https://github.com/python-pillow/Pillow/issues/2635
* https://github.com/python-pillow/Pillow/issues/2664#issuecomment-328666279

Changes proposed in this pull request:

 * Release python GIL when converting images using matrix operations

Thank you for reviewing!

### CODE REVIEW

**Comment by hmaarrfk** [comment]
kind bumb

**Comment by hmaarrfk** [comment]
Gentle bump in case anybody wanted to review this. It would be greatly appreciated.

**Review by hugovk — APPROVED** [review]
Thank you!

**Comment by hmaarrfk** [comment]
Thank you for including tests for error cases. This made finding bugs in my original implementation easy!

**Comment by hmaarrfk** [comment]
Thanks!

**Pull request merged**
