### PR TITLE
Just for fun, yapf-formatting of PIL/*.py

### PR DESCRIPTION
**Pull request by aclark4life**
And amazingly all tests pass! https://github.com/google/yapf

### CODE REVIEW

**Comment by aclark4life** [comment]
For discussion only right now: some of this a like, some I don't like. In general with a large body of work like PIL, it may be nice to perform a one-time format of all code with yapf to create a "clean slate" effect, then fix annoyances created by the formatted code.

**Comment by hugovk** [comment]
> The idea is also similar to the 'gofmt' tool for the Go programming language: end all holy wars about formatting - if the whole code base of a project is simply piped through YAPF whenever modifications are made, the style remains consistent throughout the project and there's no point arguing about style in every code review.

If yapf can be [configured](https://github.com/google/yapf#formatting-style) to our liking, we can do this.

**Comment by wiredfool** [comment]
* Meh, some of the changes are decent, some are horrible. Oddly enough, some classes of transforms manage to hit both of those in various places in the code. (e.g. deep data structures and exception strings) 
 * Don't do anything to OleFileIO, unless it goes upstream first
 * Gofmt is from a different culture and is part of genesis of the language. Python is from a different culture. Guido has said a few times that things like pep8 are more guidelines than rules.

**Comment by aclark4life** [comment]
@wiredfool I'll configure to taste at some point, using their configuration options. Can we talk you into it if we allow post-formatting fixes to any annoyances that remain?

**Comment by radarhere** [comment]
If this was going to be done at any point, I would suggest 3.0 as the time to do it.

**Comment by radarhere** [comment]
In light of the discussion in #1770, can this be closed?

**Comment by aclark4life** [comment]
Sure we can re-open as needed

**Pull request closed without merging**
