### PR TITLE
Upgrade OleFileIO to 0.43

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by hugovk** [comment]
Last non-CI skip build is failing: https://travis-ci.org/python-pillow/Pillow/builds/95549590

**Comment by radarhere** [comment]
Yep, I've just pushed a fix, thanks.

**Comment by decalage2** [comment]
Hi, olefile v0.43 is the current development version, I have not released it yet. But if this one works as-is, I will propose a new version later.

**Comment by radarhere** [comment]
Ah, my apologies, and thanks for pointing that out. I'll close this.

**Pull request closed without merging**
