### PR TITLE
Add a basic DDS image plugin with more tests

### PR DESCRIPTION
**Pull request by wiredfool**
With tests comparing the read files to png versions. See #1650

### CODE REVIEW

**Comment by wiredfool** [comment]
Currently failing:
Pillow, DXT1
dxt1
DXT5
dxt5
Original DXT1
![dxt1-rgb-4bbp-noalpha_mipmaps-1]
(https://cloud.githubusercontent.com/assets/19792/12202348/49e88110-b621-11e5-9aab-bb9034ba9a51.png)
Original DXT5
dxt5-argb-8bbp-interpolatedalpha_mipmaps-1

**Comment by jleclanche** [comment]
The test images display fine for me.

**Comment by wiredfool** [comment]
Still a couple more bits -- sanity checks on lengths and io errors on failed unpacks.

**Comment by wiredfool** [comment]
Ok,  I think I'm good here. This includes #1650, so  I'm closing it now.

**Pull request merged**
