### PR TITLE
Remove duplicate parameter EXIF from JPEG

### PR DESCRIPTION
**Pull request by melonmouse**
Small improvement of the docs. Have a nice day :)

### CODE REVIEW

**Comment by radarhere** [comment]
The first mention of EXIF is listed under `The open() method may set the following info properties if available:`
The second is listed under `The save() method supports the following options:`

This is not a duplication. It is mentioned twice because it can be used in two different ways.

**Comment by melonmouse** [comment]
Ah thanks for the clarification! I guess I read over those because "The save/load method supports the following options:" looks to me to be a part of the header above/below it - rather than being their semantic header. Would it make sense to elevate those to headers with a fontsize in between the parameter names and the image format header?

**Comment by radarhere** [comment]
```
The :py:meth:`~PIL.Image.Image.save` method supports the following options:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
renders as a `<h4>`.

Screen Shot 2022-09-16 at 7 53 17 pm


I personally feel like that's a bit much?

This also turns it into a `<section>` and adds an anchor tag.

**Comment by melonmouse** [comment]
How about the following? I think the thing you propose is already a big win for readability of the docs, but maybe this is a bit neater.

```
The :py:meth:`~PIL.Image.Image.save` method
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The :py:meth:`~PIL.Image.Image.save` method supports the following options:
```

**Comment by radarhere** [comment]
What do you think of PR #6632 / https://pillow--6632.org.readthedocs.build/en/6632/handbook/image-file-formats.html#jpeg?

**Comment by radarhere** [comment]
#6632 has now been merged.

**Pull request closed without merging**
