### PR TITLE
WIP: Enable ImageGrab grab for Linux

### PR DESCRIPTION
**Pull request by vkresch**
Changes proposed in this pull request:

 *  Enable to use ImageGrab.py not only on mac and windows but on linux too
 *  Depends on ImageMagick `sudo apt-get install imagemagick`

Please point me to the parts which also needs to be change like the installation script.

### CODE REVIEW

**Comment by nulano** [comment]
Note that I have a WIP patch using the XCB library, which I believe is more common, but I doubt I will be able to work on it until mid-December. As the next release is on 1 January, I'd suggest waiting until later before merging this.

**Comment by radarhere** [comment]
Just to link, see #2028 for a discussion of this.

**Comment by radarhere** [comment]
Just to note - this doesn't add support for all of ImageGrab on Linux, only the ``grab`` method - if this were to progress, you might want to throw an error on ``grabclipboard``.

**Comment by radarhere** [comment]
@vkresch #4260 has been merged. Do you feel there is value in including your functionality as well, or are you happy for this to be closed?

**Comment by vkresch** [comment]
@radarhere thanks it can be closed.

**Pull request closed without merging**
