### PR TITLE
Windows: Try to build all enabled optional dependencies

### PR DESCRIPTION
**Pull request by gaborkertesz-linaro**
This patch enabled win-arm64 as a new platform for Windows.
Platform query and documentation is updated accordingly.

### CODE REVIEW

**Comment by gaborkertesz-linaro** [comment]
Tested on x64 and win-arm64.

build_dep_all.cmd before this change:
[build_all_orig.cmd.txt](https://github.com/python-pillow/Pillow/files/7474313/build_all_orig.cmd.txt)

build_dep_all.cmd with this change:
[build_all_mod.cmd.txt](https://github.com/python-pillow/Pillow/files/7474314/build_all_mod.cmd.txt)

I'm open for any recommendation if this solution won't fit to your CI/CD system and I would accept rejection, but this patch helps my current task, so I thought it can be useful for others later on.

**Comment by gaborkertesz-linaro** [comment]
Steps are done as tests:

python \winbuild\build_prepare.py
winbuild\build\build_dep_all.cmd

Output
`Pillow dependencies build result:
  libjpeg: successful
  zlib: successful
  libtiff: successful
  libwebp: successful
  libpng: successful
  freetype: failed
  lcms2: failed
  openjpeg: successful
  libimagequant: failed
  harfbuzz: failed
  fribidi: successful`

winbuild\build\build_pillow.cmd install

python selftest.py
pytest Tests

**Comment by nulano** [comment]
The expectation is that all dependencies should build correctly or be explicitly disabled. As is, this patch would break that assumption. While `build_dep_all.cmd` is not used on GitHub Actions, it is used on AppVeyor, where a silent failure would be even worse as it could go undetected for a long time (as happened before this script was in use).

There are also internal dependencies between the dependencies themselves, for example it makes no sense to build HarfBuzz and FriBiDi if FreeType failed, and FreeType is configured to require libpng.

If you only require some of the dependencies, you are welcome to run the required cmd files yourself with `cmd /c build_dep_xyz.cmd` as I often do when updating the build of some dependency, and as mentioned in the documentation:

> To build all dependencies, run ``winbuild\build\build_dep_all.cmd``, or run the individual scripts to build each dependency separately.

**Comment by gaborkertesz-linaro** [comment]
Ok, understood thanks for the quick feedback!

**Pull request closed without merging**
