### PR TITLE
Fix setting of TIFF ExtraSamples tag.

### PR DESCRIPTION
**Pull request by anntzer**
- force cast ExtraSamples to a list.
- fix calls to ImagingLibTiffSetField to include array length.
(cf. #1039, #1045)

### CODE REVIEW

**Comment by anntzer** [comment]
I just noticed your comment on #520 about incompatibilities.  Do you have any specific suggestions?  It is not clear to me how to keep full backwards compatibility there...

**Comment by wiredfool** [comment]
I don't have specific suggestions yet -- I haven't gotten in the headspace to go through and see what all is failing from the tests (since right now, they're fail fast, there could be many hiding behind the one failure), and even if the tests are actually covering what needs to be covered. 

Breaking user's code is something that I don't want to do, at least without some deprecation warnings and a phase in over some time. (From a quick look, the two things that concern me are changing some of the test items -- but I need to look closer to see if that's changing internal implementation details, or changing the only way people had to get that information, and the changes in the way that the TiffTags are done, especially removing a huge chunk of tags that we did have in there. )

I think what I'd probably look at doing is building up the IFD info in whatever api and structure works for it, including supporting EXIF (since it's the same thing), then blessing the new api as the way to do it. I'd then go back and make the old api work in a best-effort / best-guess approach, building on the new, working core.

**Comment by anntzer** [comment]
The removal of a huge chunk of tags is simply due to the fact that I was too lazy to figure out the type of each of the tags, as this is now needed.  This can easily be added back once we have decided on the actual API, which I agree is the main issue.
I had not noticed that some tests were failing, because in fact, trying to run all the tests at once fails locally, but I can run single test files so I'm just catching whatever Travis is complaining about, one file at a time.  So now MPO should be fixed (basically, now, values for unknown tags are returned as tuples, so I needed to enter the MPO tags in the TiffTags database.  (The other test was due to the use of dict comprehensions, not supported by Python 2.6).
Now I'm stuck with a failing test on 2.6 only, which doesn't seem obvious (and that I can't easily test locally)...

**Comment by hugovk** [comment]
@anntzer Some tips.

Make full use of Travis CI to run the full test suite on all Python versions. I recommend enabling Travis (and Coveralls, seeing as you're making a big change) for your own account, so you can have your own branches fully tested. They're free for open source.

See https://github.com/python-pillow/Pillow/blob/master/CONTRIBUTING.md for guidelines.

If you want to temporarily disable fail-first and see all test failures, remove the `x` option in this line of .travis.yml:

`coverage run --append --include=PIL/* -m nose -vx Tests/test_*.py`

It'll need to be re-enabled when everything is all done and the PR is ready for merging. 

Ideally all changed code should be covered by tests, and especially for big changes, it's wise to make sure there are specific tests for the functionality being changed.

**Comment by anntzer** [comment]
I don't really want to shoehorn the old API on top of the new one, so what about the following: have a global tag (e.g., `TIFF_API = "2.7"` or `"2.8"`, the default value being obviously a policy issue rather than a code issue) that'll switch between either API?  The tag would live in the `PIL` namespace, so that it can be checked for when `TiffImagePlugin` is imported for the first time.

**Comment by aclark4life** [comment]
@anntzer Any progress on this?

**Comment by anntzer** [comment]
Did you see the Feb 25th commits?  I was waiting for your opinion on the approach (providing a `legacy_api` attribute on IFD objects, defaulting to False).

**Comment by aclark4life** [comment]
Ah, thanks. We probably need @wiredfool or @hugovk to review.

**Comment by radarhere** [comment]
Hi. I think that in #1227, it turns out I was raising this exact problem. However, if I checkout this branch and try out my [test image](http://s000.tinyupload.com/download.php?file_id=08240275698144503996&t=0824027569814450399610301), it returns

    IOError: cannot identify image file
Any thoughts?

**Comment by anntzer** [comment]
Should be covered now, although the image is technically non-conformant imho.

I would really like to see this merged... what's next?

**Comment by aclark4life** [comment]
Looks like it needs a manual merge unless you want to close this and submit a new "clean" PR featuring lessons learned. I'm sure we can get it in to 2.9.0.
screenshot 2015-06-16 17 57 18

Additionally, I have no idea what "AppVeyor" is :smile:

**Comment by anntzer** [comment]
Apparently it's the new testing framework that also works on Windows.  I still have the tests on Travis (https://travis-ci.org/anntzer/Pillow/builds/67102118), which also fail.  I can't reproduce the tests failures locally (the failing tests pass (i.e. the resolutions are roundtripped correctly) with both Py3.4 and 2.7).  Do you want to have a look?

I'd rather rebase the whole thing on the current master and keep this PR.  Sounds good?

**Comment by wiredfool** [comment]
And why appveyor is trying to build this instead of the PR where we're trying to enable it... I can't even...

Appveyor is Windows CI. Interface like Travis. Not quite as well baked, but certainly easier than putting together a jenkins server ourselves.

**Comment by wiredfool** [comment]
I'll take a look at the rebuilt API soonish.

**Comment by anntzer** [comment]
Rebased on the current master.

Note that there are some tests that fail, namely the "support for corrupted EXIF data".  I left the API to throw `struct.error` (we may decide to throw another exception class here, that's fine with me too) rather than print a warning and ignore the error in that case.  Given that `_getexif` is private anyways, I think changing it to throw an exception makes sense (even the changelog entry (for v. 1.1.4!) says that the interface is most likely to change in future versions...).

**Comment by aclark4life** [comment]
Currently seeing failures here
screen shot 2015-06-29 at 4 56 01 pm

**Comment by anntzer** [comment]
Sorry, I rebased mostly just to get a new appveyor build (I guess something went wrong during the transition).
I knew that there would be some failures, as mentioned in my previous message.  I would like to revert the behavior recently introduced in ed2cca1 which leads to loading corrupted exif data with just a warning rather than with an exception.  IMHO, there is no reason to guess what the exif data should be when it is corrupted.
On the other hand I wouldn't mind raising an exception other than `struct.error` (which can legitimately considered to be an implementation detail).

**Comment by anntzer** [comment]
Can someone reproduce Travis's failures locally?  Despite my best attempts I cannot reproduce them (on Linux 64bit).

**Comment by radarhere** [comment]
I am unable to reproduce on OS X.

**Comment by wiredfool** [comment]
I can reproduce on Ubuntu 12.04/x64. Changing the assert to 

```
      self.assertEqual(val, value, msg="%s didn't roundtrip. %s, %s" % (tag, val, value))
```

yields:
```
Traceback (most recent call last):
  File "/home/erics/Pillow/Tests/test_file_libtiff.py", line 144, in test_write_metadata
    self.assertEqual(val, value, msg="%s didn't roundtrip. %s, %s" % (tag, val, value))
AssertionError: YResolution didn't roundtrip. ((4294967295, 113653537),), ((634011008, 16777216),)
```

They are roughly equivalent, but different representations.

**Comment by anntzer** [comment]
Sorry, I won't have the time to work on this in the next few days.  We could switch back to assertAlmostEqual (which as I mentioned earlier was already used by the earlier tests) for now...

**Comment by anntzer** [comment]
The problem is that I have no idea of where (634011008, 16777216) comes from.  It is not that hard to see that the value actually stored in the file is (4294967295, 113653537) (hex dump `ffff ffff 2137 c606` towards the end of the file) and this is also the value I see if I print the values in the test.
Likewise these are the values that appear when running master (before any TIFF patching).  Can you run the tests with the current master, and print the values at lines 142 and 153 of `test_file_libtiff.py`?

**Comment by anntzer** [comment]
Half-fudging it, but not really: libtiff's precision for "rationals" is limited to C floats, not C doubles, so it should be enough to require roundtripping up to that precision.

**Comment by anntzer** [comment]
Sad.

**Comment by wiredfool** [comment]
See #1419

**Comment by wiredfool** [comment]
Closing, merged #1419 which contains this branch.

**Pull request closed without merging**
