### PR TITLE
Trim trailing whitespace from all source files throughout project

### PR DESCRIPTION
**Pull request by jdufresne**
Many editors trim whitespace by default. When newcomers are submitting patches, it is often undesirable to see inadvertent whitespace changes in the diff as it is distracting and unrelated. To make contributing easier, clean up all whitespace in one go across the project. Will allow for cleaner diffs in the future. Contributors will not need to worry about automatic yet inadvertent whitespace changes.

### CODE REVIEW

**Comment by radarhere** [comment]
I will note that this PR wouldn't solve the problem you're describing once-and-for-all - I mean, it would go a long way towards it, but trailing whitespace is not just legacy code. Trailing whitespaces are commonly added in with new commits.

**Comment by wiredfool** [comment]
So, while this may be useful to reduce noise in commits, I'm not going to merge it due to rebasing issues. 

I'm trying to clear out the old backlog of PRs that are stacked up due to missing tests or needing one last tweak. If I merge this, it's likely to trigger rebase issues on those PRs, and that adds one more hurdle to getting those PRs in.

**Comment by jdufresne** [comment]
If you finish the backlog and would like me to rebase or redo this work. Please let me know. I'm happy to. The change is done automatically by a simple command.

**Comment by jdufresne** [comment]
>  I'm not going to merge it due to rebasing issues.

Given the recent code reorganziation, should this be reconsidered? I expect the code reorganization will already require a large amount of rebasing.

**Comment by wiredfool** [comment]
Sure, I'll push this in

**Pull request closed without merging**
