### PR TITLE
Raise NotImplementedError for verify()

### PR DESCRIPTION
**Pull request by ashleyblackmore**
Let people know that the verify() method does not provide verification.

### CODE REVIEW

**Comment by wiredfool** [comment]
Could you explain a bit why we should make this change, as it has the potential to break existing deployed code.

**Comment by ashleyblackmore** [comment]
Yes, it would break code, but I think there is a security issue here - the "verification" is not in fact verification (since the method is just a stub and does nothing). The comment is misleading, at the very least:

    def verify(self):
        """
        Verifies the contents of a file. For data read from a file, this
        method attempts to determine if the file is broken, without
        actually decoding the image data.  If this method finds any
        problems, it raises suitable exceptions.  If you need to load
        the image after using this method, you must reopen the image
        file.
        """
        pass

If you would prefer some kind of actual verification method instead of this raise, then perhaps I could come up with something for that.

**Comment by wiredfool** [comment]
That is a reasonable course to follow if we were implementing a new api. However, we've got a 20 yr old api with significant external usage.  Specifically, this change would break Django, here: https://github.com/django/django/blob/master/django/forms/fields.py#L682 . It would prevent any image other than a PNG from ever passing through that code.  

Format specific validation would be a reasonable addition, following the lead of what the PngImagePlugin uses.

**Comment by ashleyblackmore** [comment]
I see, thanks for the info.

**Pull request closed without merging**
