### PR TITLE
Give much more details about ICC profiles.

### PR DESCRIPTION
**Pull request by lambdafu**
Hi! We developed smc.freeimage as a fast image library when PIL was not competitive.  Now PIL has caught up a lot, but there are some features missing, and I am sending you a patch to fix one of them: A  lot of details about ICC profiles are currently inaccessible.  This patch exposes the information.  What do you think?

### CODE REVIEW

**Comment by lambdafu** [comment]
I guess I have to check py3 support, sorry.

**Comment by lambdafu** [comment]
Mh, Python 3 under Linux works for me.

**Comment by wiredfool** [comment]
Thanks for the contribution. 

Those do look like real errors under python 2.x and 3.2. From https://travis-ci.org/python-pillow/Pillow/jobs/113266766#L2478 which is python 2.7:

```
======================================================================
FAIL: TestImageCms.test_extended_information
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/python-pillow/Pillow/Tests/test_imagecms.py", line 270, in test_extended_information
    self.assertEqual(p.blue_primary, ((0.14306641366715667, 0.06060790921083026, 0.7140960805782015), (0.15588475410450106, 0.06603820408959558, 0.06060790921083026)))
AssertionError: Tuples differ: ((0.11546244121575455, 0.05207... != ((0.14306641366715667, 0.06060...
First differing element 0:
(0.11546244121575455, 0.05207207318221663, 0.5364367765241695)
(0.14306641366715667, 0.06060790921083026, 0.7140960805782015)
- ((0.11546244121575455, 0.05207207318221663, 0.5364367765241695),
-  (0.16401583801025305, 0.07396902949551647, 0.05207207318221663))
+ ((0.14306641366715667, 0.06060790921083026, 0.7140960805782015),
+  (0.15588475410450106, 0.06603820408959558, 0.06060790921083026))
```

**Comment by lambdafu** [comment]
That's a difference in lcms versions.  lcms had a big overhaul of the absolute colorimetric intent in https://github.com/mm2/Little-CMS/commit/1e4fab616c4eef7e3ea131386e92fcf34c54f96e
The relative colorimetric intent gives the same result (as it only skews the whitepoint), and did not change since 2.2, so this should work better (the relative intent is also used in the blog post by the littlecms developer that I linked from the source, which explains how to get the primaries in lcms2).  I also sorted the tests alphabetically.

Python 3.2 does not have u'' syntax.  I am not sure how to work around that, any advice?

Python 2.6 has different float representation in strings, but they should compare equally. Travis will tell us :)

**Comment by lambdafu** [comment]
Ok, the Python builds look much better now (only missing 3.2 fix for u''), but I have no idea what to do about the appveyor problem: The log does not contain any information as far as I can see.

As with regards to documentation, I suppose that would go into the ImageCmsProfile class in PIL/ImageCms.py?

**Comment by lambdafu** [comment]
Finally figured out the build problems under Windows and fixed a couple of bugs.  The code is now ready to be merged, I think.  For documentation I'd be happy to provide some but am unsure where to place it given that CmsProfile is a class defined in C.

**Comment by wiredfool** [comment]
Look at docs/reference/ImageCms.rst. There's not much there (yet? ever?) but that's where it would go.

**Comment by lambdafu** [comment]
@wiredfool Ok, I added documentation for CmsProfile, which also exposed an implementation mistake in one of the chromaticity functions that I fixed.  Coverage is not perfect, but I guess getting the code out there and used would help a lot finding interesting icc profiles to test :)

**Pull request merged**
