### PR TITLE
Read value when checking for JPEG progressive key

### LINKED ISSUE #2064: unintuitive save properties
> **progressive**
> If present, indicates that this image should be stored as a progressive JPEG file.

It is not completely obvious that ```progressive = False``` evaluates to it being set. I guess it's difficult to change this whilst keeping backwards compatibility. (I doubt someone passes ```progressive = False``` with the intention to enable it.)

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #2064

### CODE REVIEW

**Comment by wiredfool** [comment]
Maybe add a test to test_file_jpeg.py:test_progressive_compat ?

**Comment by radarhere** [comment]
Fair call, thanks. I've added tests.

**Comment by wiredfool** [comment]
OK, LGTM.  However, it looks like optimize has the same issue. Could probably use something in the docs as well, but I'm going to merge this and we can deal with the rest of it in the next pr.

**Comment by pdknsk** [comment]
I've [commented](https://github.com/python-pillow/Pillow/issues/2064#issuecomment-249258740) on the issue, but it appears there are no subscribers, so I'm mentioning it here.

**Pull request merged**
