### PR TITLE
Added support for GIF comment extension

### LINKED ISSUE #1895: Maybe not an issue but a need for support
Hello, gif similarly to png with itxt or ztxt can contains arbitrary plain text metadata *(comment extension)*.

However, looking at the source code and the documentation of Pillow, I wasn’t able to find any relevant function for reading or writing them.

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #1895

### CODE REVIEW

**Comment by ytrezq** [comment]
A last thing : how would I be able to use this code to write comments ?

**Comment by radarhere** [comment]
im = Image.open('test.gif')
    im.info['comment'] = b"Comment text"
    im.save('test.gif')

**Comment by ytrezq** [comment]
I know this isn’t related to pillow but what is theoretical maximum comment size ?

**Comment by ytrezq** [comment]
I know this isn’t related to pillow but does ɢɪꜰ extensions support compression ?

**Comment by radarhere** [comment]
I highly suspect that there is no maximum size of a GIF file. Here is a link to the GIF89a specification - https://www.w3.org/Graphics/GIF/spec-gif89a.txt - a brief search doesn't show anything, and if it's not in the specification, then I wouldn't think that there is any kind of universal limit.

**Pull request merged**
