### PR TITLE
Load broken images

### PR DESCRIPTION
**Pull request by homm**
This PR revert change from #38. There was a couple of quick fixes and this change. As I know there was no discussion about this decision.

Later @cezarsa try to create the option for loading broken images in #311. He said:

> Because I'm not sure about what use cases @d-schmidt had in mind when the size check was added, I've introduced a new flag called IGNORE_DECODING_ERRORS that if True will never raise IOError. 

The problem with not opened images was not confirmed and this changes was reverted.

#### My point

1. I don't see a big difference between "truncated image" and "image with broken data stream", at least for my tasks. I think what you may want to read original not corrupted image from a file (LOAD_TRUNCATED_IMAGES = False), or you may want to load as many data from an image as you can (LOAD_TRUNCATED_IMAGES = True). How exactly an image is corrupted (is it truncated or has broken datastream) does not matter for almost all tasks.

2. As I understand Pillow currently loads broken images (not only truncated) if at least first chunk of the image was loaded correctly (n != 0).

3. Corrupted first chunk does not mean what nothing was loaded. It can be corrupted in the middle or close to the end. I've attached the test image with corrupted first chunk but which reads for more than the half. Unfortunately, I don't know anything about its licence (and I just realized what we probably need to remove some of my previous added test images due to legal purposes :-).

4. This can be confusing, but I also don't see a big problem even if nothing was loaded at all. This is just a special case of "something was loaded" in opposite to "everything was loaded correctly". I bet most of image viewers will show a black or transparent rectangle instead of some sort of error in this case.

### CODE REVIEW

**Comment by homm** [comment]
Any thoughts?

For being a part of 3.0.0, this should be in master for some time so everyone can confirm what this works for she. There only 12 days left until the release.

**Comment by wiredfool** [comment]
I don't have a good handle on the implications of this, and I haven't had a chance to dig through in more depth.

**Comment by homm** [comment]
@wiredfool but you can agree or disagree with my arguments :)

**Comment by radarhere** [comment]
Side question - which test images need to be replaced? All of the ones that you've added previously, or just a few?

**Comment by homm** [comment]
I've replaced broken image with broken `hopper.png` copy.

I'll replace other not CC images later in another PR.

**Comment by wiredfool** [comment]
So, the net difference here is that some images will return something where they didn't previously.  It's limited to when LOAD_TRUNCATED_IMAGES is on, and there's an error in the first block. 

The only possible way this could be a regression is if the image had literally nothing returned from the decoder. Previously, we'd toss an error, now they'll get a black image. 

I think it's safe.

**Comment by homm** [comment]
:+1:

**Pull request merged**
