### PR TITLE
Skip extra 0xff00 in jpeg

### PR DESCRIPTION
**Pull request by kkopachev**
Some jpeg images might contain 0xFF00 bytes. Currently code just raises an error in this case. Example image is attached to PR and used in test.
imagemagick are able to read and show this file just right, with warning:

> identify Tests/images/jpeg_ff00_header.jpg 
Tests/images/jpeg_ff00_header.jpg JPEG 300x225 300x225+0+0 8-bit sRGB 86.5KB 0.000u 0:00.009
identify: Corrupt JPEG data: 4 extraneous bytes before marker 0xdb `Tests/images/jpeg_ff00_header.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.

I looked up some other decoders and they just skip 0xff00:
https://golang.org/src/image/jpeg/reader.go L562
http://geezer.osdevbrasil.net/software/dumpjpeg.c (search for 0xFF00)
https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js#L604

Related issue: https://github.com/python-pillow/Pillow/issues/630

I can not share original image with which this issue occurred, so I modified flower2.jpg from Pillow's test suite.

### CODE REVIEW

**Comment by cerber717** [comment]
👍

**Comment by kkopachev** [comment]
Test failures seems to be not related to the changes.

**Comment by willtheorangeguy** [comment]
Sounds good. I have been having a problem too.

**Comment by kkopachev** [comment]
Would be great if this could be included in next release

**Comment by homm** [comment]
What is the license of the test image?

**Comment by kkopachev** [comment]
I took [image from existing tests ](https://github.com/python-pillow/Pillow/blob/master/Tests/images/flower2.jpg) and added 4 bytes. Not sure of a license of original. I assume new image will have same license.

**Pull request merged**
