### PR TITLE
Clean up reqs

### PR DESCRIPTION
**Pull request by aclark4life**
- pip freeze
- Combine docs/requirements.txt with requirements.txt (No need for separate reqs if top-level calls sub-level.)

### CODE REVIEW

**Comment by aclark4life** [comment]
@python-pillow/pillow-team Can this go in to 3.2.0? I was going to finish something… but now can't remember what it was.

**Comment by wiredfool** [comment]
OK with me. I'm not a fan of the install-venv, but I don't have to use it. 

What does the `make co` do?

**Comment by aclark4life** [comment]
@wiredfool I'm not necessarily a fan either, was just experimenting. And if I recall correctly, it didn't quite work out. ``make co`` checks out all the branches.

**Comment by wiredfool** [comment]
I'm not clear why you'd want to check out all the branches, as checkout just matches your source tree with a branch. As soon as you check out another one, you've wiped out what you just did. 

I find something like `git fetch --all` and then a checkout on an individual branch is useful.  ( especially after adding the pull requests to the the fetch refs in .git/config)

**Comment by aclark4life** [comment]
@wiredfool Just a habit I got into: https://github.com/aclark4life/python-project. ``get fetch --all`` looks interesting …

**Comment by wiredfool** [comment]
Yep. My .git/config looks like this:

```
[remote "upstream"]
   	url = git@github.com:python-pillow/Pillow.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
	fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
```

Then when I do `git fetch --all`, I refs to all the branches and prs.. Then I can just checkout a pr and test or hack on it, and it I really want to work on it, I can just create a named branch.

**Comment by wiredfool** [comment]
Getting an error on RTD from this: https://readthedocs.org/projects/pillow/builds/3868673/

**Comment by aclark4life** [comment]
OK fixed I think (changed path to requirements.txt in RTD admin)

**Comment by wiredfool** [comment]
Looks like it's building properly now.

**Comment by aclark4life** [comment]
@wiredfool Actually I rescind my thumbs up to your ``.git/config`` since I don't understand why you don't make branches in the Pillow repo :smile:. (Fetching the upstream is only attractive to me when I don't have write permission to the upstream.)

**Comment by wiredfool** [comment]
So don't call it upstream. You can still fetch PRs. :>  That's only part of it, as it also has mine and a private one. 

So, a couple of reasons I don't party on in the main pillow repo:
* Most of the time, I don't have upstream connected over ssh, it's over https. I switch that when I know I'm going to work directly on that repo, as it's the repo of record. But most of what I do to it is either through the github interface or it's around a release time.
* I've messed up master on my repo before. It's not a general problem when it's my problem. 
* I don't necessarily need to send notifications to all the watchers when I push a commit. I also rewrite history in my repo often enough to be annoying if I pushed it to everyone by default. 
* Have you seen my repo?
```
(vpy27)erics@builder-1204-x64:~/Pillow$ git branch -l | wc -l
231
```
(and that's only one of the machines where I work)

**Pull request merged**
