### PR TITLE
Close files after loading

### PR DESCRIPTION
**Pull request by homm**
Draft for #2019

This PR closes files at least for files which we are opening from filename at least for not sequence formats. This breaks consistency across different codecs, though.

Is there any reliable place where we can close files for sequence formats?

### CODE REVIEW

**Comment by wiredfool** [comment]
Will have more to say later, but mostly afk for a week.  

As far as I know, the only place to deal with closing the file for sequences is in the explicit close o r the destructor.

This may interact with handles_eof flag.

**Comment by wiredfool** [comment]
I've dumped my thoughts on open file handling into a design doc: https://github.com/wiredfool/Pillow/blob/open-files/docs/reference/open_files.rst

It looks like _exclusive_fd is actually a flag that indicates that we might have a multiple frame image. 

It doesn't appear that there's a good test for if there's > 1 image in a file in general, other than checking n_frames, which at least in the case of the GIF image plugin, has the effect of loading all of the frames in the image (which incidentally changes the image bytes). I haven't checked the others.

**Comment by condemil** [comment]
Fixes #2032

**Comment by condemil** [comment]
Fixes #2361

**Pull request closed without merging**
