### PR TITLE
Improve iPython interoperability

### LINKED ISSUE #7259: Addition of _repr_jpeg_ causes both JPEG and PNG format images to be attached to Jupyter cells
I've had a go at improving the interaction between Jupyter and `Image`s.  As I commented on in #7135, that change causes the image to be saved in JPEG and PNG format and both files attached to the invoking cell.

This behavior seems redundant, and given that no resizing is done can result in very large `.ipynb` files if the user isn't careful when working with high resolution images.  I've had a look at how to avoid this, and the nicest way I could see to do this was by adding a `Image._repr_mimebundle_` method that would do the "right thing" in more circumstances.

Specifically, it would know whether the user has called `display_jpeg` or `display_png` and could return the appropriate encoding.  If neither format is specifically requested it could return something appropriate for the data.

I've had a go at implementing this and it currently looks like:
```python
THRESHOLD_SIZE = 1200

MODE_MAP = {
    'La': 'LA',
    'LAB': 'RGB',
    'HSV': 'RGB',
    'RGBX': 'RGB',
    'RGBa': 'RGBA',
}

VALID_JPEG_MODES = {'L', 'RGB', 'YCbCr', 'CMYK'}
VALID_PNG_MODES = {'1', 'P', 'L', 'RGB', 'RGBA', 'LA', 'PA'}

def _repr_mimebundle_(self, include=None, exclude=None, **kwargs):
    # let IPython interpret its ambiguous include/exclude flags
    if include is not None or exclude is not None or kwargs:
        return None

    # massage the image into something that has a reasonable
    # chance of being viewed by the user

    # handle the special snowflake modes
    if self.mode in {'I', 'F'}:
        # linearly transform extrema to fit in [0, 255]
        # this should have a similar result as Image.histogram
        lo, hi = self.getextrema()
        scale = 256 / (hi - lo) if lo != hi else 1
        image = self.point(lambda e: (e - lo) * scale).convert('L')
    elif self.mode == 'I;16':
        # linearly transform max down to 255
        image = self.point(lambda e: e / 256).convert('L')
    else:
        image = self

    # shrink large images so they don't take too long to transfer/render
    factor = max(image.size) // THRESHOLD_SIZE
    if factor > 1:
        image = image.reduce(factor)

    # process remaining modes into things supported by writers
    if image.mode in MODE_MAP:
        image = image.convert(MODE_MAP[image.mode])

    jpeg = image._repr_jpeg_() if image.mode in VALID_JPEG_MODES else None
    png = image._repr_png_() if image.mode in VALID_PNG_MODES else None

    # prefer lossless format if it's not significantly larger
    if jpeg and png:
        # 1.125 and 2**18 used as they have nice binary representations
        if len(png) < len(jpeg) * 1.125 + 2**18:
            jpeg = None
        else:
            png = None

    return {
        'image/jpeg': jpeg,
        'image/png': png,
    }
```
This can be tested with something like:
```python
size = 100, 100
arr = np.linspace(0, 10, np.prod(size), endpoint=False, dtype=np.int32)
image = Image.fromarray(arr.reshape(size))
display.display(_repr_mimebundle_(image), raw=True)
```
Could turn this into a pull-request if this seems like the right way to go.

Note the `if include is not None or exclude is not None` code at the top would mean that explicit calls like:
```python
display.display_jpeg(image)
```
would cause Jupyter to end up calling `Image._repr_jpeg_` directly, bypassing this code.  If called with a large image, this would cause a full-res JPEG to be returned.  Not sure if this is the right thing, or even what the "correct" way of handling these arguments should be. 

I've only seen `exclude=None` in my testing, so am going on description in [`IPython/core/formatters.py`](https://github.com/ipython/ipython/blob/c3d7f161b19ddb3c16120487b0797539568c2c0f/IPython/core/formatters.py#L90) and what [`graphviz` does](https://github.com/xflr6/graphviz/blob/master/graphviz/jupyter_integration.py).

### PR DESCRIPTION
**Pull request by smason**
Fixes #7259

Changes proposed in this pull request:

 * support `_repr_mimebundle_`  by returning either PNG or JPEG
 * convert images to a supported `mode` where possible
 * shrink large images by an integer factor
 * output warning messages when changes were made for display purposes
 * refactor `_repr_png|jpeg_` to do the same pre-processing
 * because large are resized it made sense to remove the previously requested `compression_level=1`

I've been finding the current behavior to be unusable in a Jupyter notebook.  The number of dumped backtraces are very painful to work with, so I've tidied up my method in #7259 and incorporated it into the codebase.  Until I get a response to my question from the IPython project I think this code does reasonable things.

### CODE REVIEW

**Comment by radarhere** [comment]
This conversation should be re-evaluated if/when someone from the IPython team responds, but for the moment, I'm not really in favour of the various automatic changes you're making here.

In particular, you've added scaling for I;16 images, which is a change regarding #3159 that would occur here, but nowhere else.

For an analogous situation, in #7241, you were concerned about the speed of saving images for IPython. I was in favour of #7242 as a solution because it mirrored the behaviour of ImageShow. I think any arguments you make here for IPython would similarly apply to ImageShow.

Different users might have different preferences for how much they want images to be scaled down by. I know you've added a constant to try and make this configurable - my feeling is just that it is better to let the user specify what they would like, rather than guessing. If I found images displaying at a small size, I would first believe that the image itself was small, rather than expecting a library to be transforming it automatically.

Those are just my thoughts though. You're welcome to leave this open, and if someone else approves of this plan, I raise no objections.

**Comment by smason** [comment]
Mostly did this so I could have a current version that installed locally that behaved better with Jupyter.  Happy to leave it open until some decision can be reached.

Re, the `I;16` handling, I hadn't tested with loading a 16bit PNG.  I've used JPEG2000 more when dealing with higher bit-depth images, and assumed other formats were treated similarly.  For example:
```python
Image.fromarray(np.random.randint(65536, size=(100, 100), dtype='uint16')).save('out.jp2')
print(im.open('out.jp2').mode)
```
gives me `I;16` which seems useful.  This is similar when using TIFF files.

I've made it print warnings so user has some indication of when it's making non-trivial changes.  But I agree that I've baked lot of my preferences into policy rather than providing the mechanisms and letting the user define their preferred policy.

I've been reading more of their API, and have seen that you can use `BaseFormatter.for_type` to register custom code.  Which might be a better way of handling things, something like:
```python
from IPython.display import display
def show_image(obj, *args, **kwargs):
    display({
        'text/plain': f"custom={str(obj)}",
        # 'image/png': b'...',
        # 'image/jpeg': b'...',
    }, raw=True)

get_ipython().display_formatter.ipython_display_formatter.for_type(Image.Image, show_image)

Image.new('L', (10, 10))
```
and have some method available that has some common policy, but could be swapped out with another formatter as required.  The issue is that this seems to be even more entangled in the guts of IPython.

**Comment by aclark4life** [comment]
@n3011 Any opinion here?

**Comment by smason** [comment]
Following all the activity on other related issues, I've had a go at reworking this change.  By default it will now only return either a PNG or JPEG image, as determined by whichever encodes to less bytes.  It won't do any other conversion.

I've added a `Image.use_display_hook_features` method that can be called to optionally enable various transforms to make the image more compatible with IPython/Jupyter.  For example:

```python
Image.use_display_hook_features(F_mode='unit', mode_map='auto')
```
would allow the following images to be displayed automatically:
```python
Image.new('HSV', (400, 400))
Image.fromarray(np.random.random((400, 400)))
```
Or you can mostly "full auto" mode with:
```python
Image.use_display_hook_features('auto', F_mode='unit')
```
which also resizes large images and other things.

Interested to hear opinions!

**Comment by homm** [comment]
It's a quite big change and complicated API, especially when I still don't see any explanation why `_repr_jpeg_` is useful for someone.

**Comment by radarhere** [comment]
A comment from the author of this PR - https://github.com/python-pillow/Pillow/issues/7259#issuecomment-1695434827
> I'm not sure if there's enough interest to maintain the relevant state in Pillow directly.
>
> Specifically, I'm dealing with raw camera data (i.e. lots of pixels at 12 or 14bpc) and Pillow doesn't seem to track the numeric range from the source data in a way that would help me. I'm also interested in just previewing images while I'm exploring the data in Jupyter (hence my code downsampling images) and returning both PNG and JPEG versions of the image seems wasteful.
>
> When I've got a workflow/code that's mostly correct I'll turn it into a proper Python module that's tested to process things correctly, but, e.g., while working out whether I'm correctly debayering an image correctly I just want a quick preview that things are on track. In my experience this is a good way to use Jupyter notebooks; exploratory work goes into notebooks where it's very quick to iterate on changes (no need to rerun Python and/or reload large datasets), then the code is tidied up for production into a module (or a package for large chunks of code).
>
> You can close as Wont Fix if you think that's relevant, I'm not sure how many other people use Pillow in the way I am.

As I've indicated earlier, I think this is somewhat too... automatic. This PR is trying to solve #3159, #2663, and also scaling images automatically, but only for IPython, while against an IPython decision. It's trying to more IPython use easier, but the boundaries for this change are irregularly defined enough that I think this should be code on the user's end, rather than something built into Pillow.

**Pull request closed without merging**
