### PR TITLE
Image add support fromarray LA mode

### PR DESCRIPTION
**Pull request by pierriko**
when using grayscale image with alpha channel, at the moment I have to save them as:
```python
def save(path, data, quality=90):
    if len(data.shape) == 3 and data.shape[2] == 2:
        # Pillow "Cannot handle this data type" mode=LA
        img = Image.fromarray(data[:,:,0])
        alp = Image.fromarray(data[:,:,1])
        img.putalpha(alp)
    else:
        img = Image.fromarray(data)
    # in case of JPEG or WebP, set quality to 90%, else this option is ignored
    img.save(path, quality=quality)
```
(see: https://github.com/pierriko/atlaas/blob/master/python/atlaas/helpers/image.py )

This patch add support for mode LA in `Image.fromarray` and fix:
```
>>> img = np.zeros((40,40,2), 'uint8')
>>> Image.fromarray(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1929, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

### CODE REVIEW

**Comment by radarhere** [comment]
Hi. Thanks for this. If you're able to add a test as well, that would be appreciated.

**Comment by pierriko** [comment]
Hi !

Let me know if the test is ok with you.

Cheers,
Pierrick

**Comment by radarhere** [comment]
I was imagining something that fits in with the existing tests for this - https://github.com/python-pillow/Pillow/blob/master/Tests/test_image_array.py.

Also, just to set expectations - I'm here to offer helpful hints. Someone else will ultimately review this PR for inclusion.

**Comment by wiredfool** [comment]
see #1871

**Pull request closed without merging**
