### PR TITLE
Remove `image.copy()` op from `exif_transpose()`

### PR DESCRIPTION
**Pull request by glenn-jocher**
This version of the function avoids image copy and a dictionary build for the majority use case of missing exif tags / no action needed on call.

As implemented in YOLOv5 in https://github.com/ultralytics/yolov5/pull/3852

### CODE REVIEW

**Comment by radarhere** [comment]
I count 3 changes here

1. Moving `method` inside a new `if` block.

It seems to me like the extra code complexity isn't worth the very minor speed increase.

2. You reverted #5547, deleting the orientation tag from the original image.

As #5546 explains in full, this means that while original image hasn't been transposed, its orientation tag is gone now.

```python
from PIL import Image
im = Image.open("hopper.jpg")
exif = im.getexif()
orientation_before = exif.get(0x0112)
im.exif_transpose()
orientation_after = exif.get(0x0112)
```

The `orientation_after` will be empty, but the image data in `im` is still the same. I don't think this is desired.

3. Removing the `copy()` operation if a transpose is not performed.

Because `transpose` returns a copy of the image, this keeps the output consistent. Without it,
```python
from PIL import Image
im = Image.open("hopper.jpg")
im2 = im.exif_transpose()
```
sometimes, `im` will be the same object as `im2`, and sometimes it won't. That's a source of confusion for the user.

For example, afterwards, if I rotate `im2`,
```python
im2.rotate(90)
```
I don't know whether or not `im` has been rotated, because it might the same image instance, or it might not.

**Comment by glenn-jocher** [comment]
CI is failing. I think this appears to be due to the CI itself expecting copies of images returned from the function rather than a problem in the function.

**Comment by radarhere** [comment]
The specific failure seen in AppVeyor at the moment isn't because this isn't `copy()`ing the image. It's a test from #5547. So it's because this is deleting the orientation tag from the original image's EXIF data - what I'm calling point 2 in these changes.

**Comment by glenn-jocher** [comment]
@radarhere thanks for the detailed analysis. I understand the need for continuity of behavior within the PIL package, so in this case it seems we want slightly different behaviors, as in our case we want to prioritize speed, so to use the official function we'd probably want to have an if-statement outside the function to determine if it required transposing first, which would duplicate the code inside the function.

I think probably we'll implement our updated version in YOLOv5 with a comment referencing the source, and then I'll close this PR.

**Comment by glenn-jocher** [comment]
@radarhere PR is closed. Thank you for your feedback!

**Pull request closed without merging**
