### PR TITLE
API Additions

### PR DESCRIPTION
**Pull request by Kipkurui-mutai**
Fixes # Displaying images in Google Colab.

Changes proposed in this pull request:

 * According to issue  #5289

### CODE REVIEW

**Comment by radarhere** [comment]
`ipython_display` is just an alias. The method is actually `display`.

Also, this works for IPython in general as well, not just Google Colab.

**Review by Kipkurui-mutai — COMMENTED** [review]
API Additions

**Review by Kipkurui-mutai — COMMENTED** [review]
Update 8.2.0.rst

**Comment by radarhere** [comment]
The ImageShow documentation has already been added to #5289 by https://github.com/radarhere/Pillow/pull/12

I've added https://github.com/python-pillow/Pillow/pull/5289/commits/76a373fbdfb49f13bd7e957fabe4ca2a6f48d57b for the release notes.

**Pull request closed without merging**
