### PR TITLE
Added Gitter references

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by wiredfool** [comment]
Is anyone paying attention to gitter?

**Comment by radarhere** [comment]
There was the initial conversation on November 10.
Then a question was asked on Jan 18, which wasn't answered.
Then a question was asked on Mar 3, which was answered.

**Comment by aclark4life** [comment]
@wiredfool Not me … you can kill it if you want I guess

**Comment by hugovk** [comment]
Merging, as people have been using it lately.

**Pull request merged**
