### PR TITLE
Remove indirect dependencies from requirements.txt

### PR DESCRIPTION
**Pull request by hugovk**
This is mostly just to create a new PR to see if the Codecov checks are now working, and we don't explicitly use `six` anyway.

### CODE REVIEW

**Comment by radarhere** [comment]
From what i can see, we also don't use alabaster, Babel, docopt, docutils, Jinja2, MarkupSafe, Pygments, pytz or snowballstemmer - looks like these were all added during the [requirements version freeze](https://github.com/python-pillow/Pillow/commit/1dfbe273f0deb7642ba2f7427d3), and were left there when the versions were unfrozen. Shall we remove those as well?

cov-core could also be part of that list, I'm just less certain that it's not used directly.

**Comment by wiredfool** [comment]
Check out pipdeptree: https://github.com/naiquevin/pipdeptree

I'd be in favor of just requiring the top level items by version, and let the rest sort themselves out.

**Comment by wiredfool** [comment]
While you're cleaning -- the `-e .` line is dangerous, and leads to inconsistent behavior. I think that the `olefile` dependency is actually an optional dependency, and not actually a dev dependency.

**Comment by radarhere** [comment]
Output from pipdeptree

```
black==19.3b0
  - appdirs [required: Any, installed: 1.4.3]
  - attrs [required: >=18.1.0, installed: 19.1.0]
  - click [required: >=6.5, installed: 7.0]
  - toml [required: >=0.9.4, installed: 0.10.0]
check-manifest==0.39
  - toml [required: Any, installed: 0.10.0]
cov-core==1.15.0
  - coverage [required: >=3.6, installed: 4.5.3]
coveralls==1.8.1
  - coverage [required: >=3.6,<5.0, installed: 4.5.3]
  - docopt [required: >=0.6.1, installed: 0.6.2]
  - requests [required: >=1.0.0, installed: 2.22.0]
    - certifi [required: >=2017.4.17, installed: 2019.6.16]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.3]
jarn.viewdoc==2.3
  - docutils [required: >=0.14, installed: 0.14]
  - pygments [required: >=2.3.1, installed: 2.4.2]
  - setuptools [required: Any, installed: 41.0.1]
olefile==0.46
pycodestyle==2.5.0
pyflakes==2.1.1
pyroma==2.5
  - docutils [required: Any, installed: 0.14]
  - setuptools [required: Any, installed: 41.0.1]
pytest-cov==2.7.1
  - coverage [required: >=4.4, installed: 4.5.3]
  - pytest [required: >=3.6, installed: 5.0.1]
    - atomicwrites [required: >=1.0, installed: 1.3.0]
    - attrs [required: >=17.4.0, installed: 19.1.0]
    - importlib-metadata [required: >=0.12, installed: 0.18]
      - zipp [required: >=0.5, installed: 0.5.2]
    - more-itertools [required: >=4.0.0, installed: 7.2.0]
    - packaging [required: Any, installed: 19.0]
      - pyparsing [required: >=2.0.2, installed: 2.4.1.1]
      - six [required: Any, installed: 1.12.0]
    - pluggy [required: >=0.12,<1.0, installed: 0.12.0]
      - importlib-metadata [required: >=0.12, installed: 0.18]
        - zipp [required: >=0.5, installed: 0.5.2]
    - py [required: >=1.5.0, installed: 1.8.0]
    - wcwidth [required: Any, installed: 0.1.7]
sphinx-rtd-theme==0.4.3
  - sphinx [required: Any, installed: 2.1.2]
    - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
    - babel [required: >=1.3,!=2.0, installed: 2.7.0]
      - pytz [required: >=2015.7, installed: 2019.1]
    - docutils [required: >=0.12, installed: 0.14]
    - imagesize [required: Any, installed: 1.1.0]
    - Jinja2 [required: >=2.3, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - packaging [required: Any, installed: 19.0]
      - pyparsing [required: >=2.0.2, installed: 2.4.1.1]
      - six [required: Any, installed: 1.12.0]
    - Pygments [required: >=2.0, installed: 2.4.2]
    - requests [required: >=2.5.0, installed: 2.22.0]
      - certifi [required: >=2017.4.17, installed: 2019.6.16]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.3]
    - setuptools [required: Any, installed: 41.0.1]
    - snowballstemmer [required: >=1.1, installed: 1.9.0]
    - sphinxcontrib-applehelp [required: Any, installed: 1.0.1]
    - sphinxcontrib-devhelp [required: Any, installed: 1.0.1]
    - sphinxcontrib-htmlhelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
    - sphinxcontrib-qthelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-serializinghtml [required: Any, installed: 1.1.3]
```

**Comment by hugovk** [comment]
Updated.

**Pull request merged**
