### PR TITLE
Disable-platform-guessing in setup.py

### PR DESCRIPTION
**Pull request by wiredfool**
Includes a bit of a refactor of #1861 + docs.

### CODE REVIEW

**Comment by wiredfool** [comment]
@angeloc Could you check that this still works for you.

**Comment by angeloc** [comment]
@wiredfool : Tested on Buildroot, it works like a charm!

Please merge!

**Comment by angeloc** [comment]
@wiredfool: I would really have python-pillow included in buildroot, is there any possibility that a minor release will be released with this fix included?
Thanks!

**Comment by wiredfool** [comment]
Unlikely before the scheduled release at the beginning of July, unless we have another issue that it can piggyback on. We generally only do point releases for security bugs or regressions, and this doesn't hit that criteria.

**Pull request merged**
