### PR TITLE
GitHub Action to add issue or PR to project

### PR DESCRIPTION
**Pull request by hugovk**
Continuation of https://github.com/python-pillow/Pillow/pull/4078.

The Action has been updated and v0.1.0 released:

* https://github.com/alex-page/github-project-automation-plus/issues/10#issuecomment-534347768

### CODE REVIEW

**Comment by hugovk** [comment]
```
Run alex-page/github-project-automation-plus@v0.1.0
   with:
    project: Pillow
    column: New Issues
##[error]HttpError: Bad credentials
##[error]Bad credentials
##[error]Node run failed with exit code 1
```

**Comment by hugovk** [comment]
Unfortunately this is not possible at the moment, as forks cannot read the token needed to run the action. Hopefully in the future!

Thanks for the help in investigating!

**Comment by nulano** [comment]
> Unfortunately this is not possible at the moment, as forks cannot read the token needed to run the action. Hopefully in the future!

Does this include issues? Perhaps this could still be used for those.

**Comment by hugovk** [comment]
Yes, I think for everything.

**Pull request closed without merging**
