### PR TITLE
Pruning manifest to those items we need

### PR DESCRIPTION
**Pull request by wiredfool**
Pruning manifest to those items we need and in larger chunks to reduce thrashing.

 * This doesn't have nearly the detailed coverage, it's including whole directories at a shot. This makes it far less likely that you'll miss something when adding a test. 
 * It removes everything that shouldn't be in an sdist, like appveyor, editorconfig, travis, anything git related, coveragerc, and such. 
 * This saves about a second of a ~3 second python only build on an ssd vm OMM. 
 * Removes warnings from the build about pattern excluded but no pattern matched. 

However. Check-manifest barfs mightily, and complains that there are a hell of a long list of things that aren't included. If you check in the actual generated manifest, `SOURCES.txt`, they are actually there, or intentionally ignored (like the source control cruft). Adding the intentional ignores back in causes warnings from the manifest generation. I'd prefer to fix or ignore check-manifest, because it's clearly wrong.

### CODE REVIEW

**Comment by wiredfool** [comment]
@hugovk I've looked at the output file manifest from this change, and I think it's actually correct. Check-manifest is freaking out, but I don't think it's actually calculating the files correctly. 

Can you take a look at this?

**Comment by hugovk** [comment]
I also see a discrepancy between what `check-manifest --ignore "depends/*"` complains is missing, and what `python setup.py sdist --dry-run --verbose` actually includes. 

For example, the former complains Tests/*.py are missing, but the latter includes them.

Python 2.7.10
check-manifest==0.30

---

With this branch, MANIFEST.in contains:
```
include *.c
include *.h
include *.in
include *.md
include *.py
include *.rst
include *.sh
include *.txt
include LICENSE
include Makefile
graft Tests/fonts
graft Tests/images
graft Tests/icc
graft Tk
graft libImaging
graft depends
graft winbuild
graft docs
prune docs/_static

# build/src control detritus
exclude build_children.sh
global-exclude .git*

```

I get this output locally:
```
$ check-manifest --ignore "depends/*"
lists of files in version control and sdist do not match!
missing from sdist:
  .coveragerc
  .editorconfig
  .landscape.yaml
  PIL/OleFileIO-README.md
  Scripts/README.rst
  Scripts/diffcover-install.sh
  Scripts/diffcover-run.sh
  Tests/32bit_segfault_check.py
  Tests/README.rst
  Tests/bench_cffi_access.py
  Tests/bench_get.py
  Tests/check_icns_dos.py
  Tests/check_imaging_leaks.py
  Tests/check_j2k_dos.py
  Tests/check_j2k_leaks.py
  Tests/check_jpeg_leaks.py
  Tests/check_png_dos.py
  Tests/check_webp_leaks.py
  Tests/helper.py
  Tests/import_all.py
  Tests/large_memory_numpy_test.py
  Tests/large_memory_test.py
  Tests/make_hash.py
  Tests/show_icc.py
  Tests/show_mcidas.py
  Tests/test_000_sanity.py
  Tests/test_binary.py
  Tests/test_bmp_reference.py
  Tests/test_box_blur.py
  Tests/test_cffi.py
  Tests/test_decompression_bomb.py
  Tests/test_features.py
  Tests/test_file_bmp.py
  Tests/test_file_bufrstub.py
  Tests/test_file_cur.py
  Tests/test_file_dcx.py
  Tests/test_file_eps.py
  Tests/test_file_fitsstub.py
  Tests/test_file_fli.py
  Tests/test_file_fpx.py
  Tests/test_file_gbr.py
  Tests/test_file_gif.py
  Tests/test_file_gimpgradient.py
  Tests/test_file_gimppalette.py
  Tests/test_file_gribstub.py
  Tests/test_file_hdf5stub.py
  Tests/test_file_icns.py
  Tests/test_file_ico.py
  Tests/test_file_im.py
  Tests/test_file_iptc.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_libtiff_small.py
  Tests/test_file_mcidas.py
  Tests/test_file_mic.py
  Tests/test_file_mpo.py
  Tests/test_file_msp.py
  Tests/test_file_palm.py
  Tests/test_file_pcx.py
  Tests/test_file_pdf.py
  Tests/test_file_png.py
  Tests/test_file_ppm.py
  Tests/test_file_psd.py
  Tests/test_file_sgi.py
  Tests/test_file_spider.py
  Tests/test_file_sun.py
  Tests/test_file_tar.py
  Tests/test_file_tga.py
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  Tests/test_file_webp.py
  Tests/test_file_webp_alpha.py
  Tests/test_file_webp_lossless.py
  Tests/test_file_webp_metadata.py
  Tests/test_file_xbm.py
  Tests/test_file_xpm.py
  Tests/test_font_bdf.py
  Tests/test_font_pcf.py
  Tests/test_format_hsv.py
  Tests/test_format_lab.py
  Tests/test_image.py
  Tests/test_image_array.py
  Tests/test_image_convert.py
  Tests/test_image_copy.py
  Tests/test_image_crop.py
  Tests/test_image_draft.py
  Tests/test_image_filter.py
  Tests/test_image_frombytes.py
  Tests/test_image_fromqimage.py
  Tests/test_image_fromqpixmap.py
  Tests/test_image_getbands.py
  Tests/test_image_getbbox.py
  Tests/test_image_getcolors.py
  Tests/test_image_getdata.py
  Tests/test_image_getextrema.py
  Tests/test_image_getim.py
  Tests/test_image_getpalette.py
  Tests/test_image_getpixel.py
  Tests/test_image_getprojection.py
  Tests/test_image_histogram.py
  Tests/test_image_load.py
  Tests/test_image_mode.py
  Tests/test_image_point.py
  Tests/test_image_putalpha.py
  Tests/test_image_putdata.py
  Tests/test_image_putpalette.py
  Tests/test_image_putpixel.py
  Tests/test_image_quantize.py
  Tests/test_image_resize.py
  Tests/test_image_rotate.py
  Tests/test_image_split.py
  Tests/test_image_thumbnail.py
  Tests/test_image_tobitmap.py
  Tests/test_image_tobytes.py
  Tests/test_image_toqimage.py
  Tests/test_image_toqpixmap.py
  Tests/test_image_transform.py
  Tests/test_image_transpose.py
  Tests/test_imagechops.py
  Tests/test_imagecms.py
  Tests/test_imagecolor.py
  Tests/test_imagedraw.py
  Tests/test_imageenhance.py
  Tests/test_imagefile.py
  Tests/test_imagefont.py
  Tests/test_imagefont_bitmap.py
  Tests/test_imagegrab.py
  Tests/test_imagemath.py
  Tests/test_imagemorph.py
  Tests/test_imageops.py
  Tests/test_imageops_usm.py
  Tests/test_imagepalette.py
  Tests/test_imagepath.py
  Tests/test_imageqt.py
  Tests/test_imagesequence.py
  Tests/test_imageshow.py
  Tests/test_imagestat.py
  Tests/test_imagetk.py
  Tests/test_imagewin.py
  Tests/test_imagewin_pointers.py
  Tests/test_lib_image.py
  Tests/test_lib_pack.py
  Tests/test_locale.py
  Tests/test_mode_i16.py
  Tests/test_numpy.py
  Tests/test_olefileio.py
  Tests/test_pickle.py
  Tests/test_psdraw.py
  Tests/test_pyroma.py
  Tests/test_scipy.py
  Tests/test_shell_injection.py
  Tests/test_tiff_ifdrational.py
  Tests/test_util.py
  Tests/threaded_save.py
  Tests/versions.py
  appveyor.yml
  tox.ini
suggested MANIFEST.in rules:
  include *.yaml
  include *.yml
  include .coveragerc
  include tox.ini
  recursive-include PIL *.md
  recursive-include Scripts *.rst
  recursive-include Scripts *.sh
  recursive-include Tests *.py
  recursive-include Tests *.rst
```

Running `python setup.py sdist --dry-run --verbose`:
```
...
reading manifest file 'Pillow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Pillow.egg-info/SOURCES.txt'
...
```

and Pillow.egg-info/SOURCES.txt contains:
```
.coveragerc
.landscape.yaml
.travis.yml
CHANGES.rst
CONTRIBUTING.md
LICENSE
MANIFEST.in
Makefile
README.rst
RELEASING.md
_imaging.c
_imagingcms.c
_imagingft.c
_imagingmath.c
_imagingmorph.c
_imagingtk.c
_webp.c
appveyor.yml
decode.c
display.c
encode.c
map.c
mp_compile.py
outline.c
path.c
profile-installed.py
py3.h
requirements.txt
selftest.py
setup.py
test-installed.py
tox.ini
PIL/BdfFontFile.py
PIL/BmpImagePlugin.py
PIL/BufrStubImagePlugin.py
PIL/ContainerIO.py
PIL/CurImagePlugin.py
PIL/DcxImagePlugin.py
PIL/EpsImagePlugin.py
PIL/ExifTags.py
PIL/FitsStubImagePlugin.py
PIL/FliImagePlugin.py
PIL/FontFile.py
PIL/FpxImagePlugin.py
PIL/GbrImagePlugin.py
PIL/GdImageFile.py
PIL/GifImagePlugin.py
PIL/GimpGradientFile.py
PIL/GimpPaletteFile.py
PIL/GribStubImagePlugin.py
PIL/Hdf5StubImagePlugin.py
PIL/IcnsImagePlugin.py
PIL/IcoImagePlugin.py
PIL/ImImagePlugin.py
PIL/Image.py
PIL/ImageChops.py
PIL/ImageCms.py
PIL/ImageColor.py
PIL/ImageDraw.py
PIL/ImageDraw2.py
PIL/ImageEnhance.py
PIL/ImageFile.py
PIL/ImageFilter.py
PIL/ImageFont.py
PIL/ImageGrab.py
PIL/ImageMath.py
PIL/ImageMode.py
PIL/ImageMorph.py
PIL/ImageOps.py
PIL/ImagePalette.py
PIL/ImagePath.py
PIL/ImageQt.py
PIL/ImageSequence.py
PIL/ImageShow.py
PIL/ImageStat.py
PIL/ImageTk.py
PIL/ImageTransform.py
PIL/ImageWin.py
PIL/ImtImagePlugin.py
PIL/IptcImagePlugin.py
PIL/Jpeg2KImagePlugin.py
PIL/JpegImagePlugin.py
PIL/JpegPresets.py
PIL/McIdasImagePlugin.py
PIL/MicImagePlugin.py
PIL/MpegImagePlugin.py
PIL/MpoImagePlugin.py
PIL/MspImagePlugin.py
PIL/OleFileIO-README.md
PIL/OleFileIO.py
PIL/PSDraw.py
PIL/PaletteFile.py
PIL/PalmImagePlugin.py
PIL/PcdImagePlugin.py
PIL/PcfFontFile.py
PIL/PcxImagePlugin.py
PIL/PdfImagePlugin.py
PIL/PixarImagePlugin.py
PIL/PngImagePlugin.py
PIL/PpmImagePlugin.py
PIL/PsdImagePlugin.py
PIL/PyAccess.py
PIL/SgiImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/SunImagePlugin.py
PIL/TarIO.py
PIL/TgaImagePlugin.py
PIL/TiffImagePlugin.py
PIL/TiffTags.py
PIL/WalImageFile.py
PIL/WebPImagePlugin.py
PIL/WmfImagePlugin.py
PIL/XVThumbImagePlugin.py
PIL/XbmImagePlugin.py
PIL/XpmImagePlugin.py
PIL/__init__.py
PIL/_binary.py
PIL/_util.py
PIL/features.py
Pillow.egg-info/PKG-INFO
Pillow.egg-info/SOURCES.txt
Pillow.egg-info/dependency_links.txt
Pillow.egg-info/pbr.json
Pillow.egg-info/top_level.txt
Pillow.egg-info/zip-safe
Scripts/README.rst
Scripts/createfontdatachunk.py
Scripts/diffcover-install.sh
Scripts/diffcover-run.sh
Scripts/enhancer.py
Scripts/explode.py
Scripts/gifmaker.py
Scripts/painter.py
Scripts/pilconvert.py
Scripts/pildriver.py
Scripts/pilfile.py
Scripts/pilfont.py
Scripts/pilprint.py
Scripts/player.py
Scripts/thresholder.py
Scripts/viewer.py
Tests/32bit_segfault_check.py
Tests/README.rst
Tests/bench_cffi_access.py
Tests/bench_get.py
Tests/check_icns_dos.py
Tests/check_imaging_leaks.py
Tests/check_j2k_dos.py
Tests/check_j2k_leaks.py
Tests/check_jpeg_leaks.py
Tests/check_png_dos.py
Tests/check_webp_leaks.py
Tests/helper.py
Tests/import_all.py
Tests/large_memory_numpy_test.py
Tests/large_memory_test.py
Tests/make_hash.py
Tests/show_icc.py
Tests/show_mcidas.py
Tests/test_000_sanity.py
Tests/test_binary.py
Tests/test_bmp_reference.py
Tests/test_box_blur.py
Tests/test_cffi.py
Tests/test_decompression_bomb.py
Tests/test_features.py
Tests/test_file_bmp.py
Tests/test_file_bufrstub.py
Tests/test_file_cur.py
Tests/test_file_dcx.py
Tests/test_file_eps.py
Tests/test_file_fitsstub.py
Tests/test_file_fli.py
Tests/test_file_fpx.py
Tests/test_file_gbr.py
Tests/test_file_gif.py
Tests/test_file_gimpgradient.py
Tests/test_file_gimppalette.py
Tests/test_file_gribstub.py
Tests/test_file_hdf5stub.py
Tests/test_file_icns.py
Tests/test_file_ico.py
Tests/test_file_im.py
Tests/test_file_iptc.py
Tests/test_file_jpeg.py
Tests/test_file_jpeg2k.py
Tests/test_file_libtiff.py
Tests/test_file_libtiff_small.py
Tests/test_file_mcidas.py
Tests/test_file_mic.py
Tests/test_file_mpo.py
Tests/test_file_msp.py
Tests/test_file_palm.py
Tests/test_file_pcx.py
Tests/test_file_pdf.py
Tests/test_file_png.py
Tests/test_file_ppm.py
Tests/test_file_psd.py
Tests/test_file_sgi.py
Tests/test_file_spider.py
Tests/test_file_sun.py
Tests/test_file_tar.py
Tests/test_file_tga.py
Tests/test_file_tiff.py
Tests/test_file_tiff_metadata.py
Tests/test_file_webp.py
Tests/test_file_webp_alpha.py
Tests/test_file_webp_lossless.py
Tests/test_file_webp_metadata.py
Tests/test_file_xbm.py
Tests/test_file_xpm.py
Tests/test_font_bdf.py
Tests/test_font_pcf.py
Tests/test_format_hsv.py
Tests/test_format_lab.py
Tests/test_image.py
Tests/test_image_array.py
Tests/test_image_convert.py
Tests/test_image_copy.py
Tests/test_image_crop.py
Tests/test_image_draft.py
Tests/test_image_filter.py
Tests/test_image_frombytes.py
Tests/test_image_fromqimage.py
Tests/test_image_fromqpixmap.py
Tests/test_image_getbands.py
Tests/test_image_getbbox.py
Tests/test_image_getcolors.py
Tests/test_image_getdata.py
Tests/test_image_getextrema.py
Tests/test_image_getim.py
Tests/test_image_getpalette.py
Tests/test_image_getpixel.py
Tests/test_image_getprojection.py
Tests/test_image_histogram.py
Tests/test_image_load.py
Tests/test_image_mode.py
Tests/test_image_point.py
Tests/test_image_putalpha.py
Tests/test_image_putdata.py
Tests/test_image_putpalette.py
Tests/test_image_putpixel.py
Tests/test_image_quantize.py
Tests/test_image_resize.py
Tests/test_image_rotate.py
Tests/test_image_split.py
Tests/test_image_thumbnail.py
Tests/test_image_tobitmap.py
Tests/test_image_tobytes.py
Tests/test_image_toqimage.py
Tests/test_image_toqpixmap.py
Tests/test_image_transform.py
Tests/test_image_transpose.py
Tests/test_imagechops.py
Tests/test_imagecms.py
Tests/test_imagecolor.py
Tests/test_imagedraw.py
Tests/test_imageenhance.py
Tests/test_imagefile.py
Tests/test_imagefont.py
Tests/test_imagefont_bitmap.py
Tests/test_imagegrab.py
Tests/test_imagemath.py
Tests/test_imagemorph.py
Tests/test_imageops.py
Tests/test_imageops_usm.py
Tests/test_imagepalette.py
Tests/test_imagepath.py
Tests/test_imageqt.py
Tests/test_imagesequence.py
Tests/test_imageshow.py
Tests/test_imagestat.py
Tests/test_imagetk.py
Tests/test_imagewin.py
Tests/test_imagewin_pointers.py
Tests/test_lib_image.py
Tests/test_lib_pack.py
Tests/test_locale.py
Tests/test_mode_i16.py
Tests/test_numpy.py
Tests/test_olefileio.py
Tests/test_pickle.py
Tests/test_psdraw.py
Tests/test_pyroma.py
Tests/test_scipy.py
Tests/test_shell_injection.py
Tests/test_tiff_ifdrational.py
Tests/test_util.py
Tests/threaded_save.py
Tests/versions.py
Tests/fonts/DejaVuSans-bitmap.ttf
Tests/fonts/DejaVuSans.ttf
Tests/fonts/FreeMono.ttf
Tests/fonts/helvO18.pcf
Tests/icc/LICENSE.txt
Tests/icc/sRGB_IEC61966-2-1_black_scaled.icc
Tests/icc/sRGB_v4_ICC_preference.icc
Tests/images/10ct_32bit_128.tiff
Tests/images/12bit.cropped.tif
Tests/images/12in16bit.tif
Tests/images/16_bit_binary.pgm
Tests/images/16_bit_binary_pgm.png
Tests/images/16bit.MM.cropped.tif
Tests/images/16bit.MM.deflate.tif
Tests/images/16bit.cropped.j2k
Tests/images/16bit.cropped.jp2
Tests/images/16bit.cropped.tif
Tests/images/16bit.deflate.tif
Tests/images/7x13.png
Tests/images/bad_palette_entry.gpl
Tests/images/bad_palette_file.gpl
Tests/images/binary_preview_map.eps
Tests/images/broken.png
Tests/images/broken_data_stream.png
Tests/images/caption_6_33_22.png
Tests/images/color_snakes.png
Tests/images/copyleft.tiff
Tests/images/corner.lut
Tests/images/courB08.bdf
Tests/images/courB08.pbm
Tests/images/courB08.pil
Tests/images/create_eps.gnuplot
Tests/images/custom_gimp_palette.gpl
Tests/images/deerstalker.cur
Tests/images/default_font.png
Tests/images/dilation4.lut
Tests/images/dilation8.lut
Tests/images/dispose_bgnd.gif
Tests/images/dispose_none.gif
Tests/images/dispose_prev.gif
Tests/images/edge.lut
Tests/images/effect_mandelbrot.png
Tests/images/effect_spread.png
Tests/images/erosion4.lut
Tests/images/erosion8.lut
Tests/images/exif_gps.jpg
Tests/images/exif_gps_typeerror.jpg
Tests/images/exif_typeerror.jpg
Tests/images/flower.jpg
Tests/images/flower.webp
Tests/images/flower2.jpg
Tests/images/flower2.webp
Tests/images/frozenpond.mpo
Tests/images/g4-fillorder-test.png
Tests/images/g4-fillorder-test.tif
Tests/images/gimp_gradient.ggr
Tests/images/gimp_gradient_with_name.ggr
Tests/images/high_ascii_chars.png
Tests/images/hopper.Lab.tif
Tests/images/hopper.bmp
Tests/images/hopper.bw
Tests/images/hopper.dcx
Tests/images/hopper.fli
Tests/images/hopper.gif
Tests/images/hopper.iccprofile.tif
Tests/images/hopper.iccprofile_binary.tif
Tests/images/hopper.ico
Tests/images/hopper.im
Tests/images/hopper.jpg
Tests/images/hopper.msp
Tests/images/hopper.png
Tests/images/hopper.ppm
Tests/images/hopper.psd
Tests/images/hopper.ras
Tests/images/hopper.rgb
Tests/images/hopper.spider
Tests/images/hopper.tar
Tests/images/hopper.tif
Tests/images/hopper.webp
Tests/images/hopper.xbm
Tests/images/hopper.xpm
Tests/images/hopper_bad_exif.jpg
Tests/images/hopper_bw_500.png
Tests/images/hopper_g4.tif
Tests/images/hopper_g4_500.tif
Tests/images/hopper_gray.jpg
Tests/images/hopper_gray_4bpp.tif
Tests/images/hopper_merged.psd
Tests/images/hopper_underscore.xbm
Tests/images/hopper_webp_bits.ppm
Tests/images/hopper_webp_write.ppm
Tests/images/icc_profile_none.png
Tests/images/illu10_no_preview.eps
Tests/images/illu10_preview.eps
Tests/images/illuCS6_no_preview.eps
Tests/images/illuCS6_preview.eps
Tests/images/imagedraw_arc.png
Tests/images/imagedraw_bitmap.png
Tests/images/imagedraw_chord.png
Tests/images/imagedraw_ellipse.png
Tests/images/imagedraw_ellipse_edge.png
Tests/images/imagedraw_floodfill.png
Tests/images/imagedraw_floodfill2.png
Tests/images/imagedraw_line.png
Tests/images/imagedraw_pieslice.png
Tests/images/imagedraw_point.png
Tests/images/imagedraw_polygon.png
Tests/images/imagedraw_rectangle.png
Tests/images/invalid.spider
Tests/images/iptc.jpg
Tests/images/iss634.gif
Tests/images/junk_jpeg_header.jpg
Tests/images/l_trns.png
Tests/images/lab-green.tif
Tests/images/lab-red.tif
Tests/images/lab.tif
Tests/images/morph_a.png
Tests/images/multiline_text.png
Tests/images/multiline_text_center.png
Tests/images/multiline_text_right.png
Tests/images/multiline_text_spacing.png
Tests/images/multipage-lastframe.tif
Tests/images/multipage.tiff
Tests/images/no_cursors.cur
Tests/images/non_zero_bb.eps
Tests/images/non_zero_bb.png
Tests/images/non_zero_bb_scale2.png
Tests/images/p_trns_single.png
Tests/images/pil123p.png
Tests/images/pil123rgba.png
Tests/images/pil136.tiff
Tests/images/pil168.tif
Tests/images/pil184.pcx
Tests/images/pil_sample_cmyk.jpg
Tests/images/pil_sample_rgb.jpg
Tests/images/pillow.icns
Tests/images/pillow.ico
Tests/images/pillow2.icns
Tests/images/pillow3.icns
Tests/images/png_decompression_dos.png
Tests/images/pngtest_bad.png.bin
Tests/images/pport_g4.tif
Tests/images/python.ico
Tests/images/rdf.tif
Tests/images/rectangle_surrounding_text.png
Tests/images/rgb.jpg
Tests/images/rgb_trns.png
Tests/images/rgb_trns_ycbc.j2k
Tests/images/rgb_trns_ycbc.jp2
Tests/images/sugarshack.mpo
Tests/images/sugarshack_bad_mpo_header.jpg
Tests/images/tRNS_null_1x1.png
Tests/images/test-card-lossless.jp2
Tests/images/test-card-lossy-tiled.jp2
Tests/images/test-card.png
Tests/images/test-ole-file.doc
Tests/images/test.colors.gif
Tests/images/test.gpl
Tests/images/tga_id_field.tga
Tests/images/tiff_adobe_deflate.tif
Tests/images/total-pages-zero.tif
Tests/images/transparent.png
Tests/images/transparent.sgi
Tests/images/transparent.webp
Tests/images/truncated_image.png
Tests/images/zero_bb.eps
Tests/images/zero_bb.png
Tests/images/zero_bb_scale2.png
Tests/images/bmp/README.txt
Tests/images/bmp/b/badbitcount.bmp
Tests/images/bmp/b/badbitssize.bmp
Tests/images/bmp/b/baddens1.bmp
Tests/images/bmp/b/baddens2.bmp
Tests/images/bmp/b/badfilesize.bmp
Tests/images/bmp/b/badheadersize.bmp
Tests/images/bmp/b/badpalettesize.bmp
Tests/images/bmp/b/badplanes.bmp
Tests/images/bmp/b/badrle.bmp
Tests/images/bmp/b/badwidth.bmp
Tests/images/bmp/b/pal8badindex.bmp
Tests/images/bmp/b/reallybig.bmp
Tests/images/bmp/b/rletopdown.bmp
Tests/images/bmp/b/shortfile.bmp
Tests/images/bmp/g/pal1.bmp
Tests/images/bmp/g/pal1bg.bmp
Tests/images/bmp/g/pal1wb.bmp
Tests/images/bmp/g/pal4.bmp
Tests/images/bmp/g/pal4rle.bmp
Tests/images/bmp/g/pal8-0.bmp
Tests/images/bmp/g/pal8.bmp
Tests/images/bmp/g/pal8nonsquare.bmp
Tests/images/bmp/g/pal8os2.bmp
Tests/images/bmp/g/pal8rle.bmp
Tests/images/bmp/g/pal8topdown.bmp
Tests/images/bmp/g/pal8v4.bmp
Tests/images/bmp/g/pal8v5.bmp
Tests/images/bmp/g/pal8w124.bmp
Tests/images/bmp/g/pal8w125.bmp
Tests/images/bmp/g/pal8w126.bmp
Tests/images/bmp/g/rgb16-565.bmp
Tests/images/bmp/g/rgb16-565pal.bmp
Tests/images/bmp/g/rgb16.bmp
Tests/images/bmp/g/rgb24.bmp
Tests/images/bmp/g/rgb24pal.bmp
Tests/images/bmp/g/rgb32.bmp
Tests/images/bmp/g/rgb32bf.bmp
Tests/images/bmp/html/bkgd.png
Tests/images/bmp/html/bmpsuite.html
Tests/images/bmp/html/fakealpha.png
Tests/images/bmp/html/pal1.png
Tests/images/bmp/html/pal1bg.png
Tests/images/bmp/html/pal1p1.png
Tests/images/bmp/html/pal2.png
Tests/images/bmp/html/pal4.png
Tests/images/bmp/html/pal4rletrns-0.png
Tests/images/bmp/html/pal4rletrns-b.png
Tests/images/bmp/html/pal4rletrns.png
Tests/images/bmp/html/pal8.png
Tests/images/bmp/html/pal8nonsquare-e.png
Tests/images/bmp/html/pal8nonsquare-v.png
Tests/images/bmp/html/pal8rletrns-0.png
Tests/images/bmp/html/pal8rletrns-b.png
Tests/images/bmp/html/pal8rletrns.png
Tests/images/bmp/html/pal8w124.png
Tests/images/bmp/html/pal8w125.png
Tests/images/bmp/html/pal8w126.png
Tests/images/bmp/html/rgb16-231.png
Tests/images/bmp/html/rgb16-565.png
Tests/images/bmp/html/rgb16.png
Tests/images/bmp/html/rgb24.jpg
Tests/images/bmp/html/rgb24.png
Tests/images/bmp/html/rgba16-4444.png
Tests/images/bmp/html/rgba32.png
Tests/images/bmp/q/pal1p1.bmp
Tests/images/bmp/q/pal2.bmp
Tests/images/bmp/q/pal4rletrns.bmp
Tests/images/bmp/q/pal8offs.bmp
Tests/images/bmp/q/pal8os2sp.bmp
Tests/images/bmp/q/pal8os2v2-16.bmp
Tests/images/bmp/q/pal8os2v2.bmp
Tests/images/bmp/q/pal8oversizepal.bmp
Tests/images/bmp/q/pal8rletrns.bmp
Tests/images/bmp/q/rgb16-231.bmp
Tests/images/bmp/q/rgb24jpeg.bmp
Tests/images/bmp/q/rgb24largepal.bmp
Tests/images/bmp/q/rgb24lprof.bmp
Tests/images/bmp/q/rgb24png.bmp
Tests/images/bmp/q/rgb24prof.bmp
Tests/images/bmp/q/rgb32-111110.bmp
Tests/images/bmp/q/rgb32fakealpha.bmp
Tests/images/bmp/q/rgba16-4444.bmp
Tests/images/bmp/q/rgba32.bmp
Tests/images/bmp/q/rgba32abf.bmp
Tests/images/imagedraw/line_horizontal_slope1px_w2px.png
Tests/images/imagedraw/line_horizontal_w101px.png
Tests/images/imagedraw/line_horizontal_w2px_inverted.png
Tests/images/imagedraw/line_horizontal_w2px_normal.png
Tests/images/imagedraw/line_horizontal_w3px.png
Tests/images/imagedraw/line_oblique_45_w3px_a.png
Tests/images/imagedraw/line_oblique_45_w3px_b.png
Tests/images/imagedraw/line_vertical_slope1px_w2px.png
Tests/images/imagedraw/line_vertical_w101px.png
Tests/images/imagedraw/line_vertical_w2px_inverted.png
Tests/images/imagedraw/line_vertical_w2px_normal.png
Tests/images/imagedraw/line_vertical_w3px.png
Tests/images/imagedraw/square.png
Tests/images/imagedraw/triangle_right.png
Tk/README.rst
Tk/tkImaging.c
depends/README.rst
depends/debian_8.2.sh
depends/install_openjpeg.sh
depends/install_webp.sh
depends/ubuntu_14.04.sh
docs/BUILDME
docs/COPYING
docs/Guardfile
docs/Makefile
docs/PIL.rst
docs/about.rst
docs/build.rst
docs/conf.py
docs/index.rst
docs/installation.rst
docs/make.bat
docs/porting.rst
docs/requirements.txt
docs/_templates/sidebarhelp.html
docs/handbook/appendices.rst
docs/handbook/concepts.rst
docs/handbook/image-file-formats.rst
docs/handbook/index.rst
docs/handbook/overview.rst
docs/handbook/tutorial.rst
docs/handbook/writing-your-own-file-decoder.rst
docs/reference/ExifTags.rst
docs/reference/Image.rst
docs/reference/ImageChops.rst
docs/reference/ImageCms.rst
docs/reference/ImageColor.rst
docs/reference/ImageDraw.rst
docs/reference/ImageEnhance.rst
docs/reference/ImageFile.rst
docs/reference/ImageFilter.rst
docs/reference/ImageFont.rst
docs/reference/ImageGrab.rst
docs/reference/ImageMath.rst
docs/reference/ImageMorph.rst
docs/reference/ImageOps.rst
docs/reference/ImagePalette.rst
docs/reference/ImagePath.rst
docs/reference/ImageQt.rst
docs/reference/ImageSequence.rst
docs/reference/ImageStat.rst
docs/reference/ImageTk.rst
docs/reference/ImageWin.rst
docs/reference/OleFileIO.rst
docs/reference/PSDraw.rst
docs/reference/PixelAccess.rst
docs/reference/PyAccess.rst
docs/reference/index.rst
docs/reference/plugins.rst
docs/releasenotes/2.7.0.rst
docs/releasenotes/2.8.0.rst
docs/releasenotes/3.0.0.rst
docs/releasenotes/3.1.0.rst
docs/releasenotes/index.rst
libImaging/Access.c
libImaging/AlphaComposite.c
libImaging/Bands.c
libImaging/Bit.h
libImaging/BitDecode.c
libImaging/Blend.c
libImaging/BoxBlur.c
libImaging/Chops.c
libImaging/Convert.c
libImaging/ConvertYCbCr.c
libImaging/Copy.c
libImaging/Crc32.c
libImaging/Crop.c
libImaging/Dib.c
libImaging/Draw.c
libImaging/Effects.c
libImaging/EpsEncode.c
libImaging/Except.c
libImaging/File.c
libImaging/Fill.c
libImaging/Filter.c
libImaging/FliDecode.c
libImaging/Geometry.c
libImaging/GetBBox.c
libImaging/Gif.h
libImaging/GifDecode.c
libImaging/GifEncode.c
libImaging/HexDecode.c
libImaging/Histo.c
libImaging/ImDib.h
libImaging/ImPlatform.h
libImaging/Imaging.h
libImaging/Incremental.c
libImaging/Jpeg.h
libImaging/Jpeg2K.h
libImaging/Jpeg2KDecode.c
libImaging/Jpeg2KEncode.c
libImaging/JpegDecode.c
libImaging/JpegEncode.c
libImaging/Lzw.h
libImaging/LzwDecode.c
libImaging/Matrix.c
libImaging/ModeFilter.c
libImaging/MspDecode.c
libImaging/Negative.c
libImaging/Offset.c
libImaging/Pack.c
libImaging/PackDecode.c
libImaging/Palette.c
libImaging/Paste.c
libImaging/PcdDecode.c
libImaging/PcxDecode.c
libImaging/PcxEncode.c
libImaging/Point.c
libImaging/Quant.c
libImaging/QuantHash.c
libImaging/QuantHash.h
libImaging/QuantHeap.c
libImaging/QuantHeap.h
libImaging/QuantOctree.c
libImaging/QuantOctree.h
libImaging/QuantTypes.h
libImaging/RankFilter.c
libImaging/Raw.h
libImaging/RawDecode.c
libImaging/RawEncode.c
libImaging/Resample.c
libImaging/Storage.c
libImaging/SunRleDecode.c
libImaging/TgaRleDecode.c
libImaging/TiffDecode.c
libImaging/TiffDecode.h
libImaging/Unpack.c
libImaging/UnpackYCC.c
libImaging/UnsharpMask.c
libImaging/XbmDecode.c
libImaging/XbmEncode.c
libImaging/Zip.h
libImaging/ZipDecode.c
libImaging/ZipEncode.c
winbuild/README.md
winbuild/build.py
winbuild/build_dep.py
winbuild/config.py
winbuild/fetch.py
winbuild/fixproj.py
winbuild/get_pythons.py
winbuild/nmake.opt
winbuild/test.py
winbuild/untar.py
winbuild/unzip.py
```

**Comment by hugovk** [comment]
Reported: https://github.com/mgedmin/check-manifest/issues/65

**Comment by wiredfool** [comment]
I could have sworn that the tests were actually included, but looking at Pillow.egg-info/SOURCES.txt, they weren't there. I've pushed an update for that, and am going to rebase to catch the recently added added lines.

**Comment by wiredfool** [comment]
I've force pushed the rebase, so now anything that the original issue w/ check-manifest is going to be off in the ether.

**Comment by wiredfool** [comment]
Right, and now rebased to fix merge errors from the changes I just merged to master.

**Pull request merged**
