### PR TITLE
Added FPX fill decoder

### PR DESCRIPTION
**Pull request by radarhere**
Helps #3900

The FPX image in the issue uses ["fill" compression](https://github.com/python-pillow/Pillow/blob/b3bc4a7bb4e7ab007af7d19b5091b6d4ee3c13a4/src/PIL/FpxImagePlugin.py#L172-L174), or as it is known in the [specification](https://graphcomp.com/info/specs/livepicture/fpx.pdf), "single color compression".

The specification lays out that "single color compression" is an apt name.
> If the compression type is set to single color compression (0x1), the compression subtype identifies the actual color value of all pixels in the tile.

This PR adds a PyDecoder to fill the tile with the color.

### CODE REVIEW

**Comment by faheemziker** [comment]
i have already fixed this issue ill create a pr in which we can see expected output

**Comment by radarhere** [comment]
@faheemziker thanks, that would be good. If you have an image that could be added to our test suite and distributed under the Pillow license, that would also be useful

**Comment by radarhere** [comment]
@faheemziker any update on that PR?

**Comment by radarhere** [comment]
Closing, as apparently this does not produce the correct output.

**Pull request closed without merging**
