### PR TITLE
chore: enabled syntax highlighting

### PR DESCRIPTION
**Pull request by 0xflotus**
I enabled the syntax highlighting feature in the `image-file-formats.rst`

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR, however the default for literal blocks (`::`) is already Python and we've not changed it using `highlight_language`.

* https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

So this PR doesn't change anything other than making it more explicit, which I don't think we need in this particular case.

**Comment by 0xflotus** [comment]
Ok, but there is already a use of it in the lines 1402 and 1413:

https://github.com/python-pillow/Pillow/blob/73038257e3b6f48d8909175b24f1c4e77b977b4b/docs/handbook/image-file-formats.rst#L1402-L1417

So I thaught it would be consistent.

**Comment by radarhere** [comment]
I've created PR #6958 as a possible alternative to this.

**Comment by radarhere** [comment]
#6958 has been merged instead.

**Pull request closed without merging**
