### PR TITLE
Removed history

### PR DESCRIPTION
**Pull request by radarhere**
#1520 contains the suggestion of removing history from Pillow files, so it is as a PR for consideration.

### CODE REVIEW

**Comment by hugovk** [comment]
I find these things quite interesting, and it doesn't really affect the code much. We also don't have commit history before the PIL->Pillow fork (although it's probably in some BitBucket repo somewhere). It's nice to see reminders this code is 20 years old!

**Comment by radarhere** [comment]
So we have @hugovk against, @wiredfool for in #1520 -

    I'd actually prefer to kill the changelog banner on all the files, since it's so out of
    date on anything that we're actually working on. The only thing it's actually useful
    for is determining which prehistoric layer of PIL the file is actually from.

    Probably only retain a license and any copyright info, but I'd have to spot check
    more to see if there's any other useful info there.

I'm fairly neutral on the issue, so if anyone feels strongly enough to close, feel free. Anyone else have any thoughts?

**Comment by homm** [comment]
I'm for deleting the history. I'm for deleting any stuff not related to the code from the code: history, licences, end of files. I'd like to see only useful comments explaining how this code works. For other things, there are LICENCE, CHANGES.rst and documentation.

> It's nice to see reminders this code is 20 years old!

We can't just turn codebase to the museum. What if we need to remove some file entirely (the question only for C files. We can't just delete python module for compatibility reasons)? Should we keep it just for the banner? I think it is better to collect all of them in some place outside of the code.

**Comment by wiredfool** [comment]
We need to be _way_ more careful with anything associated with licences and copyright notices than anything else that we're dealing with here. 

As for removal, I've dropped Incremental.c completely. (granted that's more recent than PIL 1.1.7)

**Comment by aclark4life** [comment]
I definitely don't want to remove history without some extremely compelling argument … which I don't see here yet.

**Comment by aclark4life** [comment]
Marking ready for merge + wontfix, please reopen if you think it's a serious problem to leave it in. Thanks

**Pull request closed without merging**
