### PR TITLE
Added ability to pass `memoryview` object to ImageDecoder

### LINKED ISSUE #6933: Can support for the `memoryview` type be added as input to _decode (decode.c)?
Data created with help of `PyMemoryView_FromMemory` function.

Overhead for big images when converting `memoryview` to bytes is noticeable.

Code located here:
https://github.com/python-pillow/Pillow/blob/7e3bed6834e639cd0f5a410abfd8224d4e5725c5/src/decode.c#L124

Is this possible to easy add support for such feature or not?

### PR DESCRIPTION
**Pull request by bigcat88**
Resolves #6933

Changes proposed in this pull request:

Checks whether or not input is PyMemoryView object.
If yes, then gets pointer to buffer and size.

This does not change any existing public API, just adds ability to pass `memoryview` to `Image.frombytes` method.

### CODE REVIEW

**Comment by hugovk** [comment]
The CIFuzz failure will be fixed by https://github.com/google/oss-fuzz/pull/9681.

**Comment by radarhere** [comment]
I attempted to [add a test for this](https://github.com/radarhere/Pillow/commit/f5b0aaee0c6bc8dfbd749e6697b2d6ce282f8ea5), and it [passes on macOS/Ubuntu](https://github.com/radarhere/Pillow/actions/runs/4242282787), but fails on [MinGW](https://github.com/radarhere/Pillow/actions/runs/4242282784) and [Windows](https://github.com/radarhere/Pillow/actions/runs/4242282788).

**Comment by radarhere** [comment]
I've created PR #6974 as an alternative to this.

**Comment by bigcat88** [comment]
Thanks, I'll close this PR then as your suggestion is more elegant.

**Pull request closed without merging**
