### PR TITLE
Reorganize imports to penalize file formats without accept

### PR DESCRIPTION
**Pull request by wiredfool**
Reorganize the file imports in three phases.

Core, common formats: Import in specific order relative to usage. 
Non-core, has accept: Import in alpha order.
Non-core, no accept function, reads from disk in _open: demoted to last.

It's hard to tell on my laptop due to thermal throttling, but this appears to run the test suite ~4% faster. (1 sec in 25)

see also #2217

### CODE REVIEW

**Comment by hugovk** [comment]
Checking the build jobs from this PR:
https://travis-ci.org/python-pillow/Pillow/builds/177955285

Ran 813 tests in 39.801s
Ran 813 tests in 132.317s
Ran 813 tests in 24.607s
Ran 813 tests in 17.149s
Ran 813 tests in 30.843s
Ran 813 tests in 23.724s
Ran 813 tests in 31.031s
Ran 813 tests in 28.238s

Total: 327.71s

A master build from about the same time:
https://travis-ci.org/python-pillow/Pillow/builds/177953821

Ran 813 tests in 38.550s
Ran 813 tests in 130.175s
Ran 813 tests in 24.593s
Ran 813 tests in 18.393s
Ran 813 tests in 25.397s
Ran 813 tests in 23.526s
Ran 813 tests in 24.899s
Ran 813 tests in 24.058s

Total: 309.591s

**Comment by radarhere** [comment]
Hey @wiredfool, just curious - this was your PR, and unless I'm misreading the comment, no one voiced opposition. Why close it?

**Comment by wiredfool** [comment]
It didn't appear to be terribly effective.

**Comment by radarhere** [comment]
Ok, thanks.

**Pull request closed without merging**
