### PR TITLE
3.9-dev: Upgrade setuptools

### PR DESCRIPTION
**Pull request by hugovk**
The setuptools fix https://github.com/pypa/setuptools/pull/2249 for python-pillow/Pillow#4769  has been released in [setuptools v49.1.3](https://github.com/pypa/setuptools/releases/tag/v49.1.3), so we can require that version or newer.

Created as draft as there are further build problems from new changes in setuptools, will add comments.

### CODE REVIEW

**Comment by hugovk** [comment]
The newest setuptools v49.2.0 warns:

> /home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.

(From https://github.com/pypa/setuptools/pull/2256 / https://github.com/pypa/setuptools/issues/2230)

And results in a build error:

> /home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/Pillow-7.3.0.dev0-py3.9-linux-x86_64.egg/PIL/Image.py:115: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: None
Pillow version: 7.3.0.dev0

https://travis-ci.org/github/hugovk/Pillow/jobs/707725016

---

Importing `setuptools` before `distuils` in `setup.py` gets rid of the warning but not the build error:

https://github.com/python-pillow/Pillow/compare/master...hugovk:3.9-upgrade-setuptools2

https://travis-ci.org/github/hugovk/Pillow/builds/707729489

---

And upgrading setuptools for all Python versions on Travis also has the same build error (not tested on Mac/Windows/other CIs):

https://github.com/python-pillow/Pillow/compare/master...hugovk:3.9-upgrade-setuptools3

https://travis-ci.org/github/hugovk/Pillow/builds/707730154

---

Will report to setuptools, and they're already reconsidering the strategy: https://github.com/pypa/setuptools/issues/2259.

**Comment by hugovk** [comment]
Reported: https://github.com/pypa/setuptools/issues/2261.

**Comment by hugovk** [comment]
Also macOS (and Linux) on GHA:

* https://github.com/hugovk/Pillow/actions/runs/167763122
* https://github.com/python-pillow/Pillow/compare/master...hugovk:3.9-upgrade-setuptools4

(Not Windows, but I've not checked it actually upgraded.)

**Comment by nulano** [comment]
You only updated the MSYS script, and that build passes with 49.1.3.

I added the upgrade to the main Windows build and it also fails:
* https://github.com/nulano/Pillow/runs/866809418?check_suite_focus=true#step:21:803
* https://github.com/python-pillow/Pillow/compare/master...nulano:upgrade-setuptools

**Comment by radarhere** [comment]
I've concluded that this error was also introduced in setuptools 47.3.2. I've created https://github.com/pypa/setuptools/pull/2297 to resolve.

**Comment by hugovk** [comment]
Hopefully this will pass now https://github.com/pypa/setuptools/pull/2297 is merged and setuptools 49.3.2 is released 🤞

**Comment by nulano** [comment]
Just copying my comment from #4858: GHA 3.9-dev has been updated and now also has a broken setuptools version.

**Comment by hugovk** [comment]
Thanks, updated to upgrade on GHA for 3.9-dev as well.

**Pull request merged**
