### PR TITLE
Added reference to Pillow to COPYING

### PR DESCRIPTION
**Pull request by radarhere**
Keeping it up to date with the changes from #1793, and in sync with the rest of the LICENSE file.

### CODE REVIEW

**Comment by aclark4life** [comment]
Thx

**Comment by wiredfool** [comment]
So, the thing about this one is that "MIT-like license" means less than nothing when applied to legal language. 

Specifically, this clause: 

  Permission to use, copy, modify, and distribute this software and its associated documentation for any purpose and without fee is hereby granted

Is not MIT like. I'm not entirely sure what it does mean, but it dates back to the PIL license, and it is significantly less free than any of the usual open source licenses.

**Comment by aclark4life** [comment]
It also broke the build :-) (Not sure why)

**Comment by hugovk** [comment]
The build broke due to a third-party issue: https://github.com/eliben/pycparser/issues/147, perfectly timed for release day :)

Here's a workaround: PR https://github.com/python-pillow/Pillow/pull/2143.

**Pull request merged**
