### PR TITLE
Remove Tidelift alignment action and badge

### PR DESCRIPTION
**Pull request by aclark4life**
Not sure if we still care about this? cf. #5762 #5763

### CODE REVIEW

**Comment by aclark4life** [comment]
Also not sure why the credential failures in CI are happening :smile:

**Comment by radarhere** [comment]
I've added commits for the "and badge" part of the title

**Comment by auvipy** [comment]
are you removing this in favor of OpenSSF?

**Comment by aclark4life** [comment]
@auvipy No, this was an experimental feature that served its purpose: testing catalog alignments for Tidelift. As far as I can tell, we haven't added any actions for OpenSSF yet e.g. https://github.com/ossf/scorecard

**Comment by radarhere** [comment]
Regarding the removal of the badge, we have separately added an OpenSSF badge - #6597

**Pull request merged**
