### PR TITLE
Fix image loading when rotating by 0 deg

### PR DESCRIPTION
**Pull request by homm**
This fixes image rotation in cases when `angle % 360.0 == 0` and image is not loaded yet.

### CODE REVIEW

**Comment by homm** [comment]
@wiredfool from my point of view, this is critical issue worth 3.3.1, but this is fully up to you.

**Comment by tisdall** [comment]
I did an upgrade and just got stung by this...

**Comment by homm** [comment]
@tisdall You can fix it on your side by explicit `im.load()` before the rotationg.

**Comment by tisdall** [comment]
I actually changed it to test for `angle % 360.0 == 0` before calling rotate.  I just wanted to point out there was at least one person affected by this issue to hopefully add weight to the 3.3.1 suggestion.  Also, I was very lucky to notice this issue mentioned in the change log as the traceback is very cryptic and I likely would have spent a long time trying to sort out the real issue.

**Pull request merged**
