### PR TITLE
Add TIFF save_all writer.

### LINKED ISSUE #733: Add support for saving multipage images, esp. TIFF and PDF
While reading multiple frames/pages is supported, I couldn't find a way to write them, despite some mentions in the code and in the changelog of version 1.1.7c1.

### PR DESCRIPTION
**Pull request by lambdafu**
Fixes #733 .

Changes proposed in this pull request:

 * Open files for reading in addition to writing in Image.save
 * Add AppendingTiffWriter to TiffImagePlugin.py (this code is from @vashek)
 * Add _save_all support to TiffImagePlugin.py.

Note that the resulting multipage tiff files may be mmappable by PIL, requiring #2139 to be loaded correctly after saving.

### CODE REVIEW

**Comment by lambdafu** [comment]
Added tests.

**Comment by lambdafu** [comment]
Mh.  Maybe Windows doesn't allow "w+b" open mode?  Have to check out what's possible there.

**Comment by vashek** [comment]
@lambdafu That can't be it, I've been using it on Windows only.

**Comment by lambdafu** [comment]
Thanks, @vashek!  I'm just warming up for the travis dance... this may take a couple of iterations :dancers:

**Comment by lambdafu** [comment]
All done.

**Comment by piranna** [comment]
When would this be available? How I could be able to fetch that code?

**Comment by piranna** [comment]
Great, thank you. I'll try to use the independent module until that.

**Comment by piranna** [comment]
I have ported your changes to the independent module but I'm not able to make it work, when passing the test I get the error ValueError: bad mode 'r+b'`, and when trying to use it with Pillow setting it as the file-like object where to save the files I have get at most the next error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./imagextractor.py", line 89, in cutAndSave_multiprocessing
    return cutAndSave(CziFile(argv[0]), argv[1], argv[2], argv[3])
  File "./imagextractor.py", line 71, in cutAndSave
    tiff_in.save(tiff_out, 'tiff')
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1685, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 1480, in _save
    raise IOError("encoder error %d when writing image file" % s)
OSError: encoder error -9 when writing image file
```

It has a lot of errors like `TIFFAppendToStrip: Write error at scanline 624.`, too. What could be happening? How could I be able to use it, maybe downloading and compiling your fork?

**Comment by lambdafu** [comment]
@piranna probably better to track the standalone version in #733 rather than this pull request, but can you put up a gist of your most recent version and post the link  in #733?

**Comment by aclark4life** [comment]
OK who wants to merge this one?

**Comment by wiredfool** [comment]
I'm not sure on this one yet.

**Pull request merged**
